import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // Build directories contain generated JavaScript outside this project's
  // TypeScript configuration, so linting them only creates false failures.
  // `.vercel/output` is generated by a local `vercel build` and is absent from
  // CI, so without it a clean local `npm run lint` reported errors that CI
  // could not reproduce.
  globalIgnores(['dist', 'dist_verify', 'android/app/build', '.vercel']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
])
