import type { CaptionDiagnostics, TranscriptLine, BiliPart } from '../types';
import { fetchWithTimeout } from '../utils/resilientFetch';

/**
 * Bilibili transcript fetcher.
 *
 * Uses the same server-side path as YouTube: Cloudflare Worker -> AWS VPS yt-dlp.
 * yt-dlp natively supports Bilibili, so this avoids the previously hardcoded
 * dependency on the local `proxy.echo-learn.uk` Cloudflare Tunnel (which is
 * frequently offline) and also removes CORS issues.
 *
 * Resilience: the Worker can intermittently hang from some mobile networks, so
 * we fall back to the same-origin Vercel proxy, which holds the VPS key.
 */

const CF_WORKER_URL = 'https://yt-transcript-proxy.rng2018520.workers.dev';
const BILIBILI_BVID_RE = /^BV[a-zA-Z0-9]{10}$/i;

export const BILIBILI_ERROR_CODES = {
  CAPTIONS_NOT_FOUND: 'captions_not_found',
  ASR_REQUIRED: 'asr_required',
  PROVIDER_TIMEOUT: 'provider_timeout',
  PROVIDER_FAILURE: 'provider_failure',
  RATE_LIMIT: 'rate_limit',
  INVALID_REQUEST: 'invalid_request',
} as const;

export type BilibiliErrorCode = (typeof BILIBILI_ERROR_CODES)[keyof typeof BILIBILI_ERROR_CODES];

export interface BilibiliTranscriptRecovery {
  canAsr: boolean;
  requiresExplicitOptIn: boolean;
}

export class BilibiliTranscriptError extends Error {
  readonly code: BilibiliErrorCode;
  readonly recovery?: BilibiliTranscriptRecovery;

  constructor(
    code: BilibiliErrorCode,
    message: string,
    recovery?: BilibiliTranscriptRecovery,
  ) {
    super(message);
    this.name = 'BilibiliTranscriptError';
    this.code = code;
    this.recovery = recovery;
  }
}

export interface TranscriptFetchResult {
  lines: TranscriptLine[];
  language: string;
  isAutoGenerated: boolean;
  /** Set to "asr" when the transcript was produced by Whisper on the VPS (no native subtitles). */
  source?: 'asr' | 'vps' | string;
  diagnostics?: CaptionDiagnostics;
}

export interface BilibiliTranscriptOptions {
  /** Deliberately enter the paid/slow ASR recovery route. */
  allowAsr?: boolean;
}

const ERROR_MESSAGES: Record<BilibiliErrorCode, string> = {
  [BILIBILI_ERROR_CODES.CAPTIONS_NOT_FOUND]: 'No captions/subtitles available for this Bilibili video',
  [BILIBILI_ERROR_CODES.ASR_REQUIRED]: 'Bilibili captions are unavailable; explicit ASR recovery is required',
  [BILIBILI_ERROR_CODES.PROVIDER_TIMEOUT]: 'Bilibili caption provider timed out',
  [BILIBILI_ERROR_CODES.PROVIDER_FAILURE]: 'Bilibili caption provider failed',
  [BILIBILI_ERROR_CODES.RATE_LIMIT]: 'Bilibili caption provider rate limited the request',
  [BILIBILI_ERROR_CODES.INVALID_REQUEST]: 'Invalid Bilibili transcript request',
};

function assertTranscriptInput(bvid: string, part?: number): void {
  if (!BILIBILI_BVID_RE.test(bvid)) {
    throw new BilibiliTranscriptError(
      BILIBILI_ERROR_CODES.INVALID_REQUEST,
      'Invalid Bilibili video ID',
    );
  }
  if (part !== undefined && (!Number.isInteger(part) || part < 1 || part > 9999)) {
    throw new BilibiliTranscriptError(
      BILIBILI_ERROR_CODES.INVALID_REQUEST,
      'Invalid Bilibili part number',
    );
  }
}

function bilibiliQuery(
  bvid: string,
  lang: string,
  part?: number,
  allowAsr = false,
): string {
  const params = new URLSearchParams({
    bvid,
    lang,
  });
  if (part !== undefined) params.set('p', String(part));
  if (allowAsr) params.set('allowAsr', '1');
  return params.toString();
}

function isBilibiliErrorCode(value: unknown): value is BilibiliErrorCode {
  return typeof value === 'string'
    && Object.values(BILIBILI_ERROR_CODES).includes(value as BilibiliErrorCode);
}

function errorRank(code: BilibiliErrorCode): number {
  // Preserve uncertainty/explicit recovery signals when the independent
  // fallback has a different result. A timeout or provider failure must never
  // be flattened into "no captions".
  return {
    [BILIBILI_ERROR_CODES.INVALID_REQUEST]: 10,
    [BILIBILI_ERROR_CODES.ASR_REQUIRED]: 5,
    [BILIBILI_ERROR_CODES.PROVIDER_TIMEOUT]: 4,
    [BILIBILI_ERROR_CODES.RATE_LIMIT]: 3,
    [BILIBILI_ERROR_CODES.PROVIDER_FAILURE]: 2,
    [BILIBILI_ERROR_CODES.CAPTIONS_NOT_FOUND]: 1,
  }[code];
}

function parseBilibiliError(
  status: number,
  body: string,
  fallbackCode?: BilibiliErrorCode,
): BilibiliTranscriptError {
  let payload: {
    error?: unknown;
    code?: unknown;
    detail?: { error?: unknown; code?: unknown } | unknown;
    recovery?: unknown;
  } = {};
  try {
    const parsed = JSON.parse(body);
    if (parsed && typeof parsed === 'object') payload = parsed as typeof payload;
  } catch {
    // Keep the bounded status mapping below for non-JSON provider failures.
  }
  const detail = payload.detail && typeof payload.detail === 'object'
    ? payload.detail as { error?: unknown; code?: unknown }
    : undefined;
  const providerCode = payload.code ?? detail?.code ?? payload.error ?? detail?.error;
  const code = isBilibiliErrorCode(providerCode)
    ? providerCode
    : fallbackCode
      ?? (status === 429
        ? BILIBILI_ERROR_CODES.RATE_LIMIT
        : status === 408 || status === 504
          ? BILIBILI_ERROR_CODES.PROVIDER_TIMEOUT
          : status === 404
            ? BILIBILI_ERROR_CODES.CAPTIONS_NOT_FOUND
            : BILIBILI_ERROR_CODES.PROVIDER_FAILURE);
  const recovery = payload.recovery && typeof payload.recovery === 'object'
    && (payload.recovery as { canAsr?: unknown }).canAsr === true
    && (payload.recovery as { requiresExplicitOptIn?: unknown }).requiresExplicitOptIn === true
    ? { canAsr: true, requiresExplicitOptIn: true }
    : undefined;
  return new BilibiliTranscriptError(code, ERROR_MESSAGES[code], recovery);
}

/**
 * Fetch transcript/subtitles for a Bilibili video.
 *
 * Tries the CF Worker first; if it hangs/fails, falls back to the same-origin
 * Vercel proxy, which forwards to the VPS without exposing its key.
 *
 * @param bvid Bilibili video ID (e.g. "BV1GJ411x7hT")
 * @param lang Preferred subtitle language (default: "zh-CN")
 * @param part Optional 1-based part number for multi-part (分p) videos
 */
export async function fetchBilibiliTranscript(
  bvid: string,
  lang: string = 'zh-CN',
  part?: number,
  options: BilibiliTranscriptOptions = {},
): Promise<TranscriptFetchResult> {
  assertTranscriptInput(bvid, part);
  const allowAsr = options.allowAsr === true;
  const qs = bilibiliQuery(bvid, lang, part, allowAsr);
  const endpoints = allowAsr
    ? [{ url: `${CF_WORKER_URL}/api/bilibili?${qs}`, timeoutMs: 90000, label: 'Worker' }]
    : [
        { url: `${CF_WORKER_URL}/api/bilibili?${qs}`, timeoutMs: 15000, label: 'Worker' },
        { url: `/api/bilibili?${qs}`, timeoutMs: 30000, label: 'Vercel' },
      ];
  let bestError: BilibiliTranscriptError | null = null;

  for (const [index, endpoint] of endpoints.entries()) {
    try {
      const candidate = await fetchWithTimeout(endpoint.url, { timeoutMs: endpoint.timeoutMs });
      const body = await candidate.text().catch(() => '');
      if (candidate.ok) {
        let data: TranscriptFetchResult & { error?: unknown; code?: unknown; recovery?: unknown };
        try {
          data = JSON.parse(body) as TranscriptFetchResult;
        } catch {
          const error = new BilibiliTranscriptError(
            BILIBILI_ERROR_CODES.PROVIDER_FAILURE,
            ERROR_MESSAGES[BILIBILI_ERROR_CODES.PROVIDER_FAILURE],
          );
          bestError = !bestError || errorRank(error.code) > errorRank(bestError.code) ? error : bestError;
          console.warn(`[EchoLearn] Bilibili ${endpoint.label} returned malformed transcript JSON`);
          continue;
        }
        if (data.code !== undefined || data.error !== undefined) {
          const error = parseBilibiliError(candidate.status, body, BILIBILI_ERROR_CODES.PROVIDER_FAILURE);
          bestError = !bestError || errorRank(error.code) > errorRank(bestError.code) ? error : bestError;
          continue;
        }
        if (!Array.isArray(data.lines) || data.lines.length === 0) {
          const error = parseBilibiliError(404, '', BILIBILI_ERROR_CODES.CAPTIONS_NOT_FOUND);
          bestError = !bestError || errorRank(error.code) > errorRank(bestError.code) ? error : bestError;
          console.warn(`[EchoLearn] Bilibili ${endpoint.label} returned no usable lines`);
          continue;
        }

        // Mark the source so the UI can tell that the same-origin route was used.
        if (index !== 0) data.source = data.source || 'vps';
        return data;
      }
      const error = parseBilibiliError(candidate.status, body);
      bestError = !bestError || errorRank(error.code) > errorRank(bestError.code) ? error : bestError;
      console.warn(`[EchoLearn] Bilibili ${endpoint.label} returned HTTP ${candidate.status} (${error.code})`);
    } catch (err) {
      const error = err instanceof Error && err.name === 'AbortError'
        ? new BilibiliTranscriptError(
            BILIBILI_ERROR_CODES.PROVIDER_TIMEOUT,
            ERROR_MESSAGES[BILIBILI_ERROR_CODES.PROVIDER_TIMEOUT],
          )
        : new BilibiliTranscriptError(
            BILIBILI_ERROR_CODES.PROVIDER_FAILURE,
            ERROR_MESSAGES[BILIBILI_ERROR_CODES.PROVIDER_FAILURE],
          );
      bestError = !bestError || errorRank(error.code) > errorRank(bestError.code) ? error : bestError;
      console.warn(`[EchoLearn] Bilibili ${endpoint.label} request failed (${error.code})`);
    }
  }

  throw bestError ?? new BilibiliTranscriptError(
    BILIBILI_ERROR_CODES.PROVIDER_FAILURE,
    ERROR_MESSAGES[BILIBILI_ERROR_CODES.PROVIDER_FAILURE],
  );
}

/**
 * Fetch video title and uploader from Bilibili.
 */
export async function getBilibiliVideoTitle(
  bvid: string,
  part?: number,
): Promise<{ title: string; ownerName: string; partCount?: number; parts?: BiliPart[] } | null> {
  if (!BILIBILI_BVID_RE.test(bvid) || (part !== undefined && (!Number.isInteger(part) || part < 1 || part > 9999))) return null;
  const selectedPart = part !== undefined ? `?p=${part}` : '';
  const canonicalUrl = `https://www.bilibili.com/video/${encodeURIComponent(bvid)}${selectedPart}`;
  const workerUrl = `${CF_WORKER_URL}/api/bilibili?bvid=${encodeURIComponent(
    bvid,
  )}&info=1${part ? `&p=${part}` : ''}`;
  const endpoints = [
    { url: workerUrl, timeoutMs: 12000 },
    {
      url: `/api/bilibili?info=1&url=${encodeURIComponent(canonicalUrl)}`,
      timeoutMs: 30000,
    },
  ];

  for (const endpoint of endpoints) {
    try {
      const resp = await fetchWithTimeout(endpoint.url, { timeoutMs: endpoint.timeoutMs });
      if (!resp.ok) continue;
      const data = (await resp.json()) as {
        title?: string;
        ownerName?: string;
        partCount?: number;
        parts?: BiliPart[];
      };
      if (!data.title && !data.ownerName && !data.parts) continue;
      return {
        title: data.title || '',
        ownerName: data.ownerName || '',
        partCount: data.partCount,
        parts: data.parts,
      };
    } catch (err) {
      console.warn(
        '[EchoLearn] Bilibili title request failed:',
        err instanceof Error ? err.message : err,
      );
    }
  }
  return null;
}

/**
 * Resolve a Bilibili URL (including a b23.tv short link) to its metadata via the
 * VPS directly. The VPS runs yt-dlp, which resolves b23.tv redirects and returns
 * the canonical BV id, title, and (for multi-part videos) the part list.
 *
 * This is the only way to recover a BV id from a b23.tv short code on the client,
 * because the redirect target is cross-origin and unreadable from the browser.
 */
export async function getBilibiliMetaByUrl(
  fullUrl: string,
): Promise<{ title: string; ownerName: string; bvid?: string; partCount?: number; parts?: BiliPart[] } | null> {
  const endpoints = [
    `${CF_WORKER_URL}/api/info?${new URLSearchParams({ url: fullUrl })}`,
    `/api/bilibili?info=1&${new URLSearchParams({ url: fullUrl })}`,
  ];

  for (const endpoint of endpoints) {
    // The Worker can have a brief cold-start/network failure. Retry the
    // primary endpoint once, then use the server-side VPS-key fallback.
    for (let attempt = 0; attempt < (endpoint.startsWith(CF_WORKER_URL) ? 2 : 1); attempt++) {
      try {
        const resp = await fetchWithTimeout(endpoint, { timeoutMs: endpoint.startsWith(CF_WORKER_URL) ? 12000 : 30000 });
        if (!resp.ok) continue;
        const data = (await resp.json()) as {
          title?: string;
          ownerName?: string;
          bvid?: string;
          partCount?: number;
          parts?: BiliPart[];
        };
        if (!data.bvid || !BILIBILI_BVID_RE.test(data.bvid)) continue;
        return {
          title: data.title || '',
          ownerName: data.ownerName || '',
          bvid: data.bvid,
          partCount: data.partCount,
          parts: data.parts,
        };
      } catch {
        // Try the next attempt/fallback endpoint.
      }
    }
  }
  return null;
}
