import type { TranscriptLine } from '../types';

/**
 * Bilibili transcript fetcher.
 *
 * Uses the same server-side path as YouTube: Cloudflare Worker -> AWS VPS yt-dlp.
 * yt-dlp natively supports Bilibili, so this avoids the previously hardcoded
 * dependency on the local `proxy.echo-learn.uk` Cloudflare Tunnel (which is
 * frequently offline) and also removes CORS issues.
 */

const CF_WORKER_URL = 'https://yt-transcript-proxy.rng2018520.workers.dev';

interface TranscriptFetchResult {
  lines: TranscriptLine[];
  language: string;
  isAutoGenerated: boolean;
}

/**
 * Fetch transcript/subtitles for a Bilibili video.
 *
 * @param bvid Bilibili video ID (e.g. "BV1GJ411x7hT")
 * @param lang Preferred subtitle language (default: "zh-CN")
 */
export async function fetchBilibiliTranscript(
  bvid: string,
  lang: string = 'zh-CN',
): Promise<TranscriptFetchResult> {
  const url = `${CF_WORKER_URL}/api/bilibili?bvid=${encodeURIComponent(
    bvid,
  )}&lang=${encodeURIComponent(lang)}`;

  const resp = await fetch(url);
  const body = await resp.text().catch(() => '');

  if (!resp.ok) {
    throw new Error(
      `Bilibili transcript error: ${resp.status} ${body.slice(0, 200)}`,
    );
  }

  const data = JSON.parse(body) as TranscriptFetchResult;
  if (!data.lines || data.lines.length === 0) {
    throw new Error(
      'No subtitles available for this Bilibili video. ' +
        'The video may not have CC subtitles. You can import a transcript manually.',
    );
  }

  return data;
}

/**
 * Fetch video title and uploader from Bilibili.
 */
export async function getBilibiliVideoTitle(
  bvid: string,
): Promise<{ title: string; ownerName: string } | null> {
  try {
    const url = `${CF_WORKER_URL}/api/bilibili?bvid=${encodeURIComponent(
      bvid,
    )}&info=1`;
    const resp = await fetch(url);
    if (!resp.ok) return null;

    const data = (await resp.json()) as {
      title?: string;
      ownerName?: string;
    };
    return {
      title: data.title || '',
      ownerName: data.ownerName || '',
    };
  } catch {
    return null;
  }
}
