import type { TranscriptLine, BiliPart } from '../types';
import { fetchWithTimeout } from '../utils/resilientFetch';

/**
 * Bilibili transcript fetcher.
 *
 * Uses the same server-side path as YouTube: Cloudflare Worker -> AWS VPS yt-dlp.
 * yt-dlp natively supports Bilibili, so this avoids the previously hardcoded
 * dependency on the local `proxy.echo-learn.uk` Cloudflare Tunnel (which is
 * frequently offline) and also removes CORS issues.
 *
 * Resilience: the Worker can intermittently hang from some mobile networks, so
 * we fall back to the VPS directly if the Worker fails.
 */

const CF_WORKER_URL = 'https://yt-transcript-proxy.rng2018520.workers.dev';

interface TranscriptFetchResult {
  lines: TranscriptLine[];
  language: string;
  isAutoGenerated: boolean;
  /** Set to "asr" when the transcript was produced by Whisper on the VPS (no native subtitles). */
  source?: 'asr' | 'vps' | string;
}

async function fetchBilibiliFromWorker(
  bvid: string,
  lang: string,
  part?: number,
): Promise<Response> {
  const qs = `bvid=${encodeURIComponent(
    bvid,
  )}&lang=${encodeURIComponent(lang)}${part ? `&p=${part}` : ''}`;
  // API-direct Bilibili ASR normally completes in 40–90s, but cold VPS/audio
  // cache misses on mobile can be slower. Keep the client alive long enough
  // for a valid transcription instead of leaving the old video on screen.
  return fetchWithTimeout(`${CF_WORKER_URL}/api/bilibili?${qs}`, { timeoutMs: 180000 });
}

/**
 * Fallback after the primary Worker transcript call fails/hangs. The VPS now
 * enforces an API key that must never ship in the browser bundle, so we cannot
 * call it directly from the client. Route through the Worker (which holds the
 * key) — its /api/bilibili endpoint already does transcript -> ASR internally,
 * just with a longer timeout budget than the primary path.
 */
async function fetchBilibiliFallback(
  bvid: string,
  lang: string,
  part?: number,
): Promise<Response> {
  const qs = `bvid=${encodeURIComponent(bvid)}&lang=${encodeURIComponent(lang)}${part ? `&p=${part}` : ''}`;
  return fetchWithTimeout(`${CF_WORKER_URL}/api/bilibili?${qs}`, { timeoutMs: 150000 });
}

/**
 * Fetch transcript/subtitles for a Bilibili video.
 *
 * Tries the CF Worker first; if it hangs/fails, falls back to the VPS directly.
 *
 * @param bvid Bilibili video ID (e.g. "BV1GJ411x7hT")
 * @param lang Preferred subtitle language (default: "zh-CN")
 * @param part Optional 1-based part number for multi-part (分p) videos
 */
export async function fetchBilibiliTranscript(
  bvid: string,
  lang: string = 'zh-CN',
  part?: number,
): Promise<TranscriptFetchResult> {
  let resp: Response;
  try {
    resp = await fetchBilibiliFromWorker(bvid, lang, part);
    if (!resp.ok) {
      const detail = await resp.clone().text().catch(() => '');
      console.warn(`[EchoLearn] Bilibili Worker error: ${resp.status} ${detail.slice(0, 200)}`);
      // A structured server response (404/401/413/502) is an authoritative
      // result. Retrying the exact same Worker URL only doubles the mobile
      // wait and hides the useful backend reason. Only network/timeouts use
      // the second attempt below.
      let message = `Bilibili transcript error: ${resp.status}`;
      try {
        const parsed = JSON.parse(detail) as { error?: string; detail?: string; hint?: string };
        message = [parsed.error, parsed.detail, parsed.hint].filter(Boolean).join(' — ') || message;
      } catch {
        if (detail.trim()) message += ` ${detail.slice(0, 200)}`;
      }
      throw new Error(message);
    }
  } catch (err) {
    if (err instanceof Error && err.message.startsWith('Bilibili transcript error:')) {
      throw err;
    }
    console.warn('[EchoLearn] Bilibili Worker path failed, trying Worker fallback:', err instanceof Error ? err.message : err);
    resp = await fetchBilibiliFallback(bvid, lang, part);
  }

  const body = await resp.text().catch(() => '');

  if (!resp.ok) {
    throw new Error(
      `Bilibili transcript error: ${resp.status} ${body.slice(0, 200)}`,
    );
  }

  const data = JSON.parse(body) as TranscriptFetchResult;
  if (!data.lines || data.lines.length === 0) {
    throw new Error(
      'No transcript available for this Bilibili video. ' +
        'It may have neither CC subtitles nor extractable audio. ' +
        'You can import a transcript manually.',
    );
  }

  // Mark the source so the UI can tell the user we fell back to the VPS.
  if (!resp.url.startsWith(CF_WORKER_URL)) {
    data.source = data.source || 'vps';
  }
  return data;
}

/**
 * Fetch video title and uploader from Bilibili.
 */
export async function getBilibiliVideoTitle(
  bvid: string,
  part?: number,
): Promise<{ title: string; ownerName: string; partCount?: number; parts?: BiliPart[] } | null> {
  try {
    const url = `${CF_WORKER_URL}/api/bilibili?bvid=${encodeURIComponent(
      bvid,
    )}&info=1${part ? `&p=${part}` : ''}`;
    const resp = await fetch(url);
    if (!resp.ok) return null;

    const data = (await resp.json()) as {
      title?: string;
      ownerName?: string;
      partCount?: number;
      parts?: BiliPart[];
    };
    return {
      title: data.title || '',
      ownerName: data.ownerName || '',
      partCount: data.partCount,
      parts: data.parts,
    };
  } catch {
    return null;
  }
}

/**
 * Resolve a Bilibili URL (including a b23.tv short link) to its metadata via the
 * VPS directly. The VPS runs yt-dlp, which resolves b23.tv redirects and returns
 * the canonical BV id, title, and (for multi-part videos) the part list.
 *
 * This is the only way to recover a BV id from a b23.tv short code on the client,
 * because the redirect target is cross-origin and unreadable from the browser.
 */
export async function getBilibiliMetaByUrl(
  fullUrl: string,
): Promise<{ title: string; ownerName: string; bvid?: string; partCount?: number; parts?: BiliPart[] } | null> {
  const endpoints = [
    `${CF_WORKER_URL}/api/info?${new URLSearchParams({ url: fullUrl })}`,
    `/api/bilibili?info=1&${new URLSearchParams({ url: fullUrl })}`,
  ];

  for (const endpoint of endpoints) {
    // The Worker can have a brief cold-start/network failure. Retry the
    // primary endpoint once, then use the server-side VPS-key fallback.
    for (let attempt = 0; attempt < (endpoint.startsWith(CF_WORKER_URL) ? 2 : 1); attempt++) {
      try {
        const resp = await fetchWithTimeout(endpoint, { timeoutMs: endpoint.startsWith(CF_WORKER_URL) ? 12000 : 30000 });
        if (!resp.ok) continue;
        const data = (await resp.json()) as {
          title?: string;
          ownerName?: string;
          bvid?: string;
          partCount?: number;
          parts?: BiliPart[];
        };
        if (!data.bvid) continue;
        return {
          title: data.title || '',
          ownerName: data.ownerName || '',
          bvid: data.bvid,
          partCount: data.partCount,
          parts: data.parts,
        };
      } catch {
        // Try the next attempt/fallback endpoint.
      }
    }
  }
  return null;
}
