import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../lib/firebase';

export interface FeedbackInput {
  userId: string;
  /** Account email if the user opted in to be contacted; null otherwise. */
  userEmail: string | null;
  text: string;
  locale?: string;
}

/**
 * Persist user feedback under the submitting user's own path:
 * `feedback/{userId}/messages/{id}`.
 *
 * Nesting the uid is what makes the account-deletion promise keepable — the
 * owner can list and delete their own submissions, which the old flat
 * `feedback/{docId}` design (autogenerated id, no client read or list) never
 * allowed. Writes stay verified-email-only, the developer reads submissions from
 * the Firebase console, and no other signed-in user can read or delete them.
 */
export async function submitFeedback(input: FeedbackInput): Promise<void> {
  await addDoc(collection(db, 'feedback', input.userId, 'messages'), {
    // Contact email only when the user opted in; the uid itself is the path.
    userEmail: input.userEmail ?? null,
    text: input.text,
    locale: input.locale ?? (typeof navigator !== 'undefined' ? navigator.language : 'en'),
    platform: typeof navigator !== 'undefined' ? navigator.userAgent : 'unknown',
    createdAt: serverTimestamp(),
  });
}
