/**
 * YouTube transcript auto-fetch service.
 *
 * Extracts captions/subtitles from YouTube videos client-side
 * by parsing the video page HTML through a CORS proxy.
 */

import type { TranscriptLine } from '../types';

// ── CORS proxies (primary + fallback) ────────────────────────

const CORS_PROXIES = [
  (url: string) => `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
  (url: string) => `https://corsproxy.io/?${encodeURIComponent(url)}`,
];

// ── Types for YouTube's internal structures ──────────────────

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name?: { simpleText?: string };
  kind?: string; // "asr" = auto-generated
}

interface TimedTextEvent {
  tStartMs: number;
  dDurationMs: number;
  segs?: Array<{ utf8: string }>;
}

// ── Helpers ──────────────────────────────────────────────────

/** Decode HTML entities commonly found in YouTube JSON. */
function decodeHtmlEntities(str: string): string {
  return str
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\\u0026/g, '&')
    .replace(/\\"/g, '"');
}

/** Extract ytInitialPlayerResponse JSON from YouTube page HTML. */
function extractPlayerResponse(html: string): Record<string, unknown> | null {
  const patterns = [
    /var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;(?:\s*var\s|<\/script>)/s,
    /ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;/s,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match?.[1]) {
      try {
        return JSON.parse(decodeHtmlEntities(match[1])) as Record<string, unknown>;
      } catch {
        continue;
      }
    }
  }
  return null;
}

/** Extract caption tracks from ytInitialPlayerResponse. */
function getCaptionTracks(playerResponse: Record<string, unknown>): CaptionTrack[] {
  const captions = playerResponse.captions as
    | { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] } }
    | undefined;

  return captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
}

/**
 * Fetch a URL through CORS proxies, trying each in order.
 */
async function fetchViaProxy(url: string): Promise<string> {
  for (const buildUrl of CORS_PROXIES) {
    try {
      const res = await fetch(buildUrl(url));
      if (res.ok) return await res.text();
    } catch {
      continue;
    }
  }
  throw new Error('All CORS proxies failed');
}

// ── Caption parsing ──────────────────────────────────────────

/**
 * Parse YouTube JSON3 timedtext format into TranscriptLine[].
 */
function parseJson3TimedText(json: Record<string, unknown>): TranscriptLine[] {
  const events = (json.events ?? []) as TimedTextEvent[];
  const lines: TranscriptLine[] = [];

  let id = 0;
  for (const event of events) {
    const text = (event.segs ?? []).map((s) => s.utf8).join('').trim();
    if (!text || text === '\n') continue;

    lines.push({
      id: `yt_${++id}`,
      start: event.tStartMs / 1000,
      end: (event.tStartMs + event.dDurationMs) / 1000,
      text,
    });
  }

  return lines;
}

/**
 * Parse YouTube XML (srv3) timedtext format into TranscriptLine[].
 */
function parseXmlTimedText(xml: string): TranscriptLine[] {
  const lines: TranscriptLine[] = [];
  // Match <text start="..." dur="...">content</text>
  const regex = /<text\s+start="([\d.]+)"\s+dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let match: RegExpExecArray | null;
  let id = 0;

  while ((match = regex.exec(xml)) !== null) {
    const start = parseFloat(match[1]);
    const dur = parseFloat(match[2]);
    const text = match[3]
      .replace(/&#39;/g, "'")
      .replace(/&quot;/g, '"')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/\n/g, ' ')
      .trim();

    if (text) {
      lines.push({
        id: `yt_${++id}`,
        start,
        end: start + dur,
        text,
      });
    }
  }

  return lines;
}

// ── Public API ───────────────────────────────────────────────

export interface TranscriptFetchResult {
  lines: TranscriptLine[];
  language: string;
  isAutoGenerated: boolean;
}

/**
 * Fetch the transcript/captions for a YouTube video.
 *
 * Flow:
 *   1. Fetch the YouTube video page HTML via CORS proxy
 *   2. Extract `ytInitialPlayerResponse` from the HTML
 *   3. Get caption track URLs (prefers English, then any)
 *   4. Fetch the caption data (JSON3 or XML format)
 *   5. Parse into TranscriptLine[]
 *
 * @param videoId  The 11-character YouTube video ID
 * @param lang     Preferred language code (default: 'en')
 */
export async function fetchYouTubeTranscript(
  videoId: string,
  lang = 'en',
): Promise<TranscriptFetchResult> {
  // Step 1: Fetch the YouTube page
  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const html = await fetchViaProxy(pageUrl);

  // Step 2: Extract player response
  const playerResponse = extractPlayerResponse(html);
  if (!playerResponse) {
    throw new Error('Could not extract player response from YouTube page');
  }

  // Step 3: Get caption tracks
  const tracks = getCaptionTracks(playerResponse);
  if (tracks.length === 0) {
    throw new Error('No captions/subtitles available for this video');
  }

  // Prefer: manual English > auto English > any preferred lang > first track
  const manualEn = tracks.find((t) => t.languageCode === lang && t.kind !== 'asr');
  const autoEn = tracks.find((t) => t.languageCode === lang && t.kind === 'asr');
  const manualPref = tracks.find((t) => t.languageCode === lang);
  const selected = manualEn ?? autoEn ?? manualPref ?? tracks[0];

  // Step 4: Fetch caption data
  // Add format params: JSON3 for structured data, or fall back to XML
  let captionUrl = selected.baseUrl;
  let isJson3 = false;

  if (captionUrl.includes('fmt=json3') || captionUrl.includes('fmt=srv3')) {
    isJson3 = captionUrl.includes('fmt=json3');
  } else {
    // Try JSON3 format first
    captionUrl += (captionUrl.includes('?') ? '&' : '?') + 'fmt=json3';
    isJson3 = true;
  }

  try {
    const captionData = await fetchViaProxy(captionUrl);

    let lines: TranscriptLine[];

    if (isJson3) {
      try {
        const json = JSON.parse(captionData) as Record<string, unknown>;
        lines = parseJson3TimedText(json);
      } catch {
        // JSON3 failed, try without fmt param (XML)
        const xmlUrl = selected.baseUrl;
        const xmlData = await fetchViaProxy(xmlUrl);
        lines = parseXmlTimedText(xmlData);
      }
    } else {
      lines = parseXmlTimedText(captionData);
    }

    if (lines.length === 0) {
      throw new Error('Parsed transcript is empty');
    }

    return {
      lines,
      language: selected.languageCode,
      isAutoGenerated: selected.kind === 'asr',
    };
  } catch (err) {
    throw new Error(
      `Failed to fetch captions: ${err instanceof Error ? err.message : 'unknown error'}`,
    );
  }
}

/**
 * Quick check if a video likely has captions (just fetches the page).
 */
export async function hasCaptions(videoId: string): Promise<boolean> {
  try {
    const html = await fetchViaProxy(`https://www.youtube.com/watch?v=${videoId}`);
    const pr = extractPlayerResponse(html);
    if (!pr) return false;
    return getCaptionTracks(pr).length > 0;
  } catch {
    return false;
  }
}
