import { describe, expect, it } from 'vitest';
import {
  buildTranscriptMeta,
  currentTranscriptId,
  dropUngroundedSuggestions,
  fingerprintTranscriptLines,
  isAnalysisStale,
} from '../transcriptIdentity';
import type { AIAnalysisResult, TranscriptLine } from '../../types';

const lines: TranscriptLine[] = [
  { start: 10, end: 13, text: 'Good morning everyone.' },
  { start: 14, end: 16, text: "In fact, I'm leaving." },
  { start: 16, end: 18, text: "It's been great, hasn't it?" },
  { start: 43.096, end: 49, text: 'There have been three themes running through the conference.' },
];

const makeAnalysis = (overrides: Partial<AIAnalysisResult> = {}): AIAnalysisResult => ({
  summaryEn: '',
  summaryCn: '',
  keyTakeaways: [],
  vocabularySuggestions: [],
  sentenceSuggestions: [],
  learningTasks: [],
  ...overrides,
});

describe('fingerprintTranscriptLines', () => {
  it('is empty for an empty transcript', () => {
    expect(fingerprintTranscriptLines([])).toBe('');
  });

  it('is deterministic for identical content', () => {
    expect(fingerprintTranscriptLines(lines)).toBe(fingerprintTranscriptLines([...lines]));
  });

  it('changes when any line content or time changes', () => {
    const base = fingerprintTranscriptLines(lines);
    const reworded = lines.map((l, i) => (i === 1 ? { ...l, text: "In fact, I'm staying." } : l));
    const retimed = lines.map((l, i) => (i === 1 ? { ...l, start: 14.5 } : l));
    const reordered = [lines[1], lines[0], ...lines.slice(2)];
    expect(fingerprintTranscriptLines(reworded)).not.toBe(base);
    expect(fingerprintTranscriptLines(retimed)).not.toBe(base);
    expect(fingerprintTranscriptLines(reordered)).not.toBe(base);
  });

  it('carries a version prefix and the line count', () => {
    const id = fingerprintTranscriptLines(lines);
    expect(id).toMatch(/^t1-[0-9a-f]{8}-4$/);
  });
});

describe('buildTranscriptMeta', () => {
  it('always carries the fingerprint and passes through declared fields', () => {
    const meta = buildTranscriptMeta(lines, {
      language: 'en',
      isAutoGenerated: false,
      source: 'vps',
    });
    expect(meta).toEqual({
      transcriptId: fingerprintTranscriptLines(lines),
      language: 'en',
      isAutoGenerated: false,
      source: 'vps',
    });
  });

  it('omits undeclared fields instead of storing undefined', () => {
    const meta = buildTranscriptMeta(lines);
    expect(meta).toEqual({ transcriptId: fingerprintTranscriptLines(lines) });
    expect(Object.keys(meta)).toEqual(['transcriptId']);
  });
});

describe('isAnalysisStale', () => {
  it('never marks a legacy analysis (no transcriptId) stale', () => {
    expect(isAnalysisStale(makeAnalysis(), lines, [])).toBe(false);
    expect(isAnalysisStale(undefined, lines, [])).toBe(false);
  });

  it('is not stale when the analysis was produced from the same transcript', () => {
    const analysis = makeAnalysis({ transcriptId: fingerprintTranscriptLines(lines) });
    expect(isAnalysisStale(analysis, lines, [])).toBe(false);
  });

  it('is stale when the transcript was replaced', () => {
    const analysis = makeAnalysis({ transcriptId: fingerprintTranscriptLines(lines) });
    const replaced = lines.map((l, i) => (i === 0 ? { ...l, text: 'Different opening line.' } : l));
    expect(isAnalysisStale(analysis, replaced, [])).toBe(true);
  });

  it('falls back to sentence lines when no raw blocks exist, and is silent without any transcript', () => {
    const analysis = makeAnalysis({ transcriptId: fingerprintTranscriptLines(lines) });
    expect(isAnalysisStale(analysis, [], lines)).toBe(false);
    expect(isAnalysisStale(analysis, [], [{ ...lines[0], text: 'changed' }])).toBe(true);
    expect(isAnalysisStale(analysis, [], [])).toBe(false);
  });
});

describe('currentTranscriptId', () => {
  it('prefers raw blocks and matches the fingerprint of that basis', () => {
    expect(currentTranscriptId(lines, [])).toBe(fingerprintTranscriptLines(lines));
    expect(currentTranscriptId([], lines)).toBe(fingerprintTranscriptLines(lines));
    expect(currentTranscriptId([], [])).toBe('');
  });
});

describe('dropUngroundedSuggestions', () => {
  it('keeps grounded suggestions and drops hallucinated quotes', () => {
    const analysis = makeAnalysis({
      sentenceSuggestions: [
        { text: "In fact, I'm leaving.", meaningCn: '', reason: '' },
        // Spans two neighbouring lines — the matcher accepts windows, so a
        // stitched-but-real quote must survive.
        { text: "In fact, I'm leaving. It's been great, hasn't it?", meaningCn: '', reason: '' },
        { text: 'Quantum mechanics explains the double slit experiment.', meaningCn: '', reason: '' },
      ],
    });
    const result = dropUngroundedSuggestions(analysis, lines, []);
    expect(result.sentenceSuggestions.map((s) => s.text)).toEqual([
      "In fact, I'm leaving.",
      "In fact, I'm leaving. It's been great, hasn't it?",
    ]);
  });

  it('returns the analysis untouched when everything grounds', () => {
    const analysis = makeAnalysis({
      sentenceSuggestions: [{ text: "In fact, I'm leaving.", meaningCn: '', reason: '' }],
    });
    expect(dropUngroundedSuggestions(analysis, lines, [])).toBe(analysis);
  });

  it('does not invent a verdict without a transcript to ground against', () => {
    const analysis = makeAnalysis({
      sentenceSuggestions: [{ text: 'Quantum mechanics explains the double slit experiment.', meaningCn: '', reason: '' }],
    });
    expect(dropUngroundedSuggestions(analysis, [], [])).toBe(analysis);
  });

  it('leaves vocabulary suggestions alone (only quotes are checked)', () => {
    const analysis = makeAnalysis({
      vocabularySuggestions: [{ word: 'quantum', context: 'invented context', meaningCn: '', reason: '' }],
      sentenceSuggestions: [{ text: "In fact, I'm leaving.", meaningCn: '', reason: '' }],
    });
    const result = dropUngroundedSuggestions(analysis, lines, []);
    expect(result.vocabularySuggestions).toHaveLength(1);
  });
});
