import test from 'node:test';
import assert from 'node:assert/strict';
import worker, { handleBilibili } from '../src/index.js';

const BVID = 'BV1xx411c7mD';
const env = {
  YTDLP_API_URL: 'https://vps.test',
  YTDLP_API_KEY: 'test-key',
};

function response(payload, status = 200) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

function requestUrl(query) {
  return new URL(`https://worker.test/api/bilibili?${query}`);
}

function withFetchMock(impl, callback) {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = impl;
  return Promise.resolve()
    .then(callback)
    .finally(() => {
      globalThis.fetch = originalFetch;
    });
}

test('Bilibili default route is caption-only and returns a usable native-caption result', async () => {
  const calls = [];
  await withFetchMock(async (input, init) => {
    calls.push({ url: String(input), init });
    return response({
      lines: [{ start: 0, end: 1, text: 'Native caption' }],
      language: 'en',
      isAutoGenerated: false,
    });
  }, async () => {
    const result = await handleBilibili(requestUrl(`bvid=${BVID}&lang=en&p=2`), env);

    assert.equal(result.status, 200);
    assert.equal(calls.length, 1);
    assert.match(calls[0].url, /\/api\/transcript\?/);
    assert.doesNotMatch(calls[0].url, /\/api\/asr\?/);
    assert.doesNotMatch(calls[0].url, /allowAsr=1/);
    assert.equal((await result.json()).source, 'bilibili');
  });
});

test('Bilibili no-caption default returns ASR_REQUIRED without invoking ASR', async () => {
  const calls = [];
  await withFetchMock(async (input) => {
    calls.push(String(input));
    return response({ error: 'captions_not_found', code: 'captions_not_found' }, 404);
  }, async () => {
    const result = await handleBilibili(requestUrl(`bvid=${BVID}`), env);
    const body = await result.json();

    assert.equal(result.status, 409);
    assert.equal(body.code, 'asr_required');
    assert.deepEqual(body.recovery, { canAsr: true, requiresExplicitOptIn: true });
    assert.equal(calls.length, 1);
    assert.doesNotMatch(calls[0], /\/api\/asr\?/);
  });
});

test('Bilibili explicit recovery is the only route that calls VPS ASR', async () => {
  const calls = [];
  await withFetchMock(async (input, init) => {
    calls.push({ url: String(input), init });
    return response({
      lines: [{ start: 0, end: 1, text: 'Recovered speech' }],
      language: 'en',
      isAutoGenerated: true,
      source: 'asr',
    });
  }, async () => {
    const result = await handleBilibili(requestUrl(`bvid=${BVID}&lang=en&allowAsr=1`), env);
    const body = await result.json();

    assert.equal(result.status, 200);
    assert.equal(body.source, 'asr');
    assert.equal(calls.length, 1);
    assert.match(calls[0].url, /\/api\/asr\?/);
    assert.doesNotMatch(calls[0].url, /\/api\/transcript\?/);
    assert.equal(calls[0].init.headers['X-Api-Key'], 'test-key');
  });
});

test('Bilibili default provider outcomes remain typed at the Worker boundary', async (t) => {
  const cases = [
    { name: 'timeout', status: 504, code: 'provider_timeout', expectedStatus: 504 },
    { name: 'rate limit', status: 429, code: 'rate_limit', expectedStatus: 429 },
    { name: 'provider failure', status: 502, code: 'provider_failure', expectedStatus: 502 },
  ];

  for (const item of cases) {
    await t.test(item.name, async () => {
      await withFetchMock(async () => response({ error: item.code, code: item.code }, item.status), async () => {
        const result = await handleBilibili(requestUrl(`bvid=${BVID}`), env);
        const body = await result.json();
        assert.equal(result.status, item.expectedStatus);
        assert.equal(body.code, item.code);
      });
    });
  }
});

test('Worker public fetch exposes the same typed Bilibili contract with CORS', async () => {
  await withFetchMock(async () => response({
    lines: [{ start: 0, end: 1, text: 'Caption' }],
    language: 'en',
  }), async () => {
    const result = await worker.fetch(
      new Request(`https://worker.test/api/bilibili?bvid=${BVID}&lang=en`, {
        headers: { Origin: 'http://localhost:5173' },
      }),
      env,
    );
    assert.equal(result.status, 200);
    assert.equal(result.headers.get('access-control-allow-origin'), 'http://localhost:5173');
  });
});

test('Worker rejects malformed Bilibili IDs and numeric part selectors before provider calls', async () => {
  let called = false;
  await withFetchMock(async () => {
    called = true;
    return response({});
  }, async () => {
    const badId = await handleBilibili(requestUrl('bvid=not-a-bvid'), env);
    const badPart = await handleBilibili(requestUrl(`bvid=${BVID}&p=0`), env);
    assert.equal(badId.status, 400);
    assert.equal(badPart.status, 400);
    assert.equal(called, false);
  });
});
