import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  fetchBilibiliTranscript,
  BILIBILI_ERROR_CODES,
  getBilibiliMetaByUrl,
  getBilibiliVideoTitle,
} from '../bilibiliTranscript';

const CF_WORKER_URL = 'https://yt-transcript-proxy.rng2018520.workers.dev';

/**
 * Response-like stand-in. We cannot use `new Response()` for the Worker case
 * because Response.url is read-only and only set by a real fetch — the code
 * under test reads resp.url to decide whether the VPS fallback was used.
 */
function mockResponse(
  body: string,
  opts: { status?: number; url?: string } = {},
): Response {
  const status = opts.status ?? 200;
  const resp = {
    ok: status >= 200 && status < 300,
    status,
    url: opts.url ?? '',
    text: async () => body,
    json: async () => JSON.parse(body),
    arrayBuffer: async () => new TextEncoder().encode(body).buffer,
    clone: () => mockResponse(body, opts),
  };
  return resp as unknown as Response;
}

function transcriptPayload(overrides: Record<string, unknown> = {}): string {
  return JSON.stringify({
    lines: [{ start: 0, end: 2, text: 'Hello world.' }],
    language: 'zh-CN',
    isAutoGenerated: false,
    ...overrides,
  });
}

const fetchMock = vi.fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>();

beforeEach(() => {
  fetchMock.mockReset();
  vi.stubGlobal('fetch', fetchMock as unknown as typeof fetch);
});

afterEach(() => {
  vi.unstubAllGlobals();
});

// ── fetchBilibiliTranscript — happy paths ─────────────────────

describe('fetchBilibiliTranscript', () => {
  it('returns parsed data from the Worker on the first successful call', async () => {
    fetchMock.mockResolvedValueOnce(
      mockResponse(transcriptPayload(), { url: `${CF_WORKER_URL}/api/bilibili?bvid=BV1xx411c7mD` }),
    );

    const result = await fetchBilibiliTranscript('BV1xx411c7mD');

    expect(fetchMock).toHaveBeenCalledTimes(1);
    const called = String(fetchMock.mock.calls[0][0]);
    expect(called).toContain(`${CF_WORKER_URL}/api/bilibili?`);
    expect(called).not.toContain('allowAsr=1');
    expect(result.lines).toHaveLength(1);
    expect(result.language).toBe('zh-CN');
    // Worker responses must NOT be re-labelled as the VPS fallback source.
    expect(result.source).toBeUndefined();
  });

  it('encodes bvid, lang and part into the request', async () => {
    fetchMock.mockResolvedValueOnce(mockResponse(transcriptPayload(), { url: `${CF_WORKER_URL}/x` }));

    await fetchBilibiliTranscript('BV1xx411c7mD', 'en', 2);

    const called = String(fetchMock.mock.calls[0][0]);
    expect(called).toContain('bvid=BV1xx411c7mD');
    expect(called).toContain('lang=en');
    expect(called).toContain('p=2');
  });

  // ── fallback behavior ─────────────────────────────────────────

  it('falls back to the same-origin Vercel endpoint when the Worker returns 5xx', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse('upstream boom', { status: 502, url: `${CF_WORKER_URL}/x` }))
      .mockResolvedValueOnce(
        mockResponse(transcriptPayload({ source: 'asr' }), { url: '/api/bilibili' }),
      );

    const result = await fetchBilibiliTranscript('BV1xx411c7mD');

    expect(fetchMock).toHaveBeenCalledTimes(2);
    expect(String(fetchMock.mock.calls[1][0])).toMatch(/^\/api\/bilibili\?/);
    expect(result.lines).toHaveLength(1);
  });

  it('falls back to Vercel when the Worker request rejects (network/timeout)', async () => {
    fetchMock
      .mockRejectedValueOnce(new Error('network down'))
      .mockResolvedValueOnce(mockResponse(transcriptPayload(), { url: '/api/bilibili' }));

    const result = await fetchBilibiliTranscript('BV1xx411c7mD');

    expect(result.lines).toHaveLength(1);
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it('returns a typed provider failure when BOTH endpoints return non-2xx', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse('worker err', { status: 500, url: `${CF_WORKER_URL}/x` }))
      .mockResolvedValueOnce(mockResponse('vercel err', { status: 503, url: '/api/bilibili' }));

    await expect(fetchBilibiliTranscript('BV1xx411c7mD')).rejects.toMatchObject({
      code: BILIBILI_ERROR_CODES.PROVIDER_FAILURE,
    });
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it('returns a typed provider failure when both endpoints fail at the network level', async () => {
    fetchMock
      .mockRejectedValueOnce(new Error('worker unreachable'))
      .mockRejectedValueOnce(new Error('vercel unreachable'));

    await expect(fetchBilibiliTranscript('BV1xx411c7mD')).rejects.toMatchObject({
      code: BILIBILI_ERROR_CODES.PROVIDER_FAILURE,
    });
  });

  // ── response body validation ──────────────────────────────────

  it('rejects an empty Worker transcript and accepts the Vercel fallback', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse(JSON.stringify({ lines: [], language: 'zh-CN', isAutoGenerated: true })))
      .mockResolvedValueOnce(mockResponse(transcriptPayload(), { url: '/api/bilibili' }));

    await expect(fetchBilibiliTranscript('BV1xx411c7mD')).resolves.toMatchObject({
      source: 'vps',
      lines: [{ text: 'Hello world.' }],
    });
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it('rejects malformed Worker JSON and accepts the Vercel fallback', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse('<html>not json</html>'))
      .mockResolvedValueOnce(mockResponse(transcriptPayload(), { url: '/api/bilibili' }));

    await expect(fetchBilibiliTranscript('BV1xx411c7mD')).resolves.toMatchObject({
      source: 'vps',
      lines: [{ text: 'Hello world.' }],
    });
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it('returns a typed provider failure when both endpoints return unusable payloads', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse('<html>not json</html>'))
      .mockResolvedValueOnce(mockResponse(JSON.stringify({ lines: [] })));

    await expect(fetchBilibiliTranscript('BV1xx411c7mD')).rejects.toMatchObject({
      code: BILIBILI_ERROR_CODES.PROVIDER_FAILURE,
    });
  });

  it('keeps the default request caption-only and surfaces explicit ASR recovery', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse(JSON.stringify({
        error: 'asr_required',
        code: 'asr_required',
        recovery: { canAsr: true, requiresExplicitOptIn: true },
      }), { status: 409, url: `${CF_WORKER_URL}/api/bilibili` }))
      .mockResolvedValueOnce(mockResponse(JSON.stringify({
        error: 'captions_not_found',
        code: 'captions_not_found',
      }), { status: 404, url: '/api/bilibili' }));

    await expect(fetchBilibiliTranscript('BV1xx411c7mD')).rejects.toMatchObject({
      code: BILIBILI_ERROR_CODES.ASR_REQUIRED,
      recovery: { canAsr: true, requiresExplicitOptIn: true },
    });
    expect(String(fetchMock.mock.calls[0][0])).not.toContain('allowAsr=1');
    expect(String(fetchMock.mock.calls[1][0])).not.toContain('allowAsr=1');
  });

  it('sends allowAsr=1 only for an explicit recovery request and does not fall back to Vercel', async () => {
    fetchMock.mockResolvedValueOnce(
      mockResponse(transcriptPayload({ source: 'asr' }), { url: `${CF_WORKER_URL}/api/bilibili` }),
    );

    const result = await fetchBilibiliTranscript('BV1xx411c7mD', 'en', 2, { allowAsr: true });

    expect(result.source).toBe('asr');
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const called = String(fetchMock.mock.calls[0][0]);
    expect(called).toContain('allowAsr=1');
    expect(called).toContain('p=2');
    expect(called).toContain('lang=en');
  });

  it.each([
    [504, BILIBILI_ERROR_CODES.PROVIDER_TIMEOUT],
    [429, BILIBILI_ERROR_CODES.RATE_LIMIT],
    [502, BILIBILI_ERROR_CODES.PROVIDER_FAILURE],
  ])('maps HTTP %s to the typed %s outcome', async (status, code) => {
    fetchMock.mockResolvedValueOnce(mockResponse('', { status }));

    await expect(fetchBilibiliTranscript('BV1xx411c7mD', 'en', undefined, { allowAsr: true }))
      .rejects.toMatchObject({ code });
  });

  it('rejects invalid video and part inputs before any network request', async () => {
    await expect(fetchBilibiliTranscript('not-a-bvid')).rejects.toMatchObject({
      code: BILIBILI_ERROR_CODES.INVALID_REQUEST,
    });
    await expect(fetchBilibiliTranscript('BV1xx411c7mD', 'en', 0)).rejects.toMatchObject({
      code: BILIBILI_ERROR_CODES.INVALID_REQUEST,
    });
    expect(fetchMock).not.toHaveBeenCalled();
  });
});

// ── getBilibiliMetaByUrl — short-link resolution ───────────────

describe('getBilibiliMetaByUrl', () => {
  const metaPayload = JSON.stringify({
    title: 'Test video',
    ownerName: 'Uploader',
    bvid: 'BV1xx411c7mD',
    partCount: 2,
  });

  it('resolves via the Worker on the first success without retrying', async () => {
    fetchMock.mockResolvedValueOnce(mockResponse(metaPayload, { url: `${CF_WORKER_URL}/api/info` }));

    const meta = await getBilibiliMetaByUrl('https://b23.tv/hbSyQzx');

    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(String(fetchMock.mock.calls[0][0])).toContain('/api/info?url=');
    expect(meta?.bvid).toBe('BV1xx411c7mD');
    expect(meta?.title).toBe('Test video');
  });

  it('retries the Worker once after a cold-start failure', async () => {
    fetchMock
      .mockRejectedValueOnce(new Error('cold start'))
      .mockResolvedValueOnce(mockResponse(metaPayload, { url: `${CF_WORKER_URL}/api/info` }));

    const meta = await getBilibiliMetaByUrl('https://b23.tv/hbSyQzx');

    expect(fetchMock).toHaveBeenCalledTimes(2);
    expect(meta?.bvid).toBe('BV1xx411c7mD');
  });

  it('falls back to the Vercel endpoint when the Worker fails twice', async () => {
    fetchMock
      .mockRejectedValueOnce(new Error('fail 1'))
      .mockRejectedValueOnce(new Error('fail 2'))
      .mockResolvedValueOnce(mockResponse(metaPayload, { url: '/api/bilibili' }));

    const meta = await getBilibiliMetaByUrl('https://b23.tv/hbSyQzx');

    expect(fetchMock).toHaveBeenCalledTimes(3);
    expect(String(fetchMock.mock.calls[2][0])).toContain('/api/bilibili?info=1&url=');
    expect(meta?.bvid).toBe('BV1xx411c7mD');
  });

  it('rejects a 2xx response that has no bvid and moves on — documents current behavior', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse(JSON.stringify({ title: 'no id here' }), {
        url: `${CF_WORKER_URL}/api/info`,
      }))
      .mockResolvedValueOnce(mockResponse(metaPayload, { url: `${CF_WORKER_URL}/api/info` }));

    const meta = await getBilibiliMetaByUrl('https://b23.tv/hbSyQzx');

    // Attempt 1 was discarded (no bvid); attempt 2 succeeded.
    expect(fetchMock).toHaveBeenCalledTimes(2);
    expect(meta?.bvid).toBe('BV1xx411c7mD');
  });

  it('returns null when every endpoint and attempt fails', async () => {
    fetchMock.mockRejectedValue(new Error('all down'));

    const meta = await getBilibiliMetaByUrl('https://b23.tv/hbSyQzx');

    // 2 Worker attempts + 1 Vercel attempt.
    expect(fetchMock).toHaveBeenCalledTimes(3);
    expect(meta).toBeNull();
  });
});

// ── getBilibiliVideoTitle ─────────────────────────────────────

describe('getBilibiliVideoTitle', () => {
  it('returns title metadata from the Worker', async () => {
    fetchMock.mockResolvedValueOnce(
      mockResponse(JSON.stringify({ title: 'T', ownerName: 'O' }), {
        url: `${CF_WORKER_URL}/api/bilibili`,
      }),
    );

    const result = await getBilibiliVideoTitle('BV1xx411c7mD', 2);

    expect(result).toEqual({ title: 'T', ownerName: 'O', partCount: undefined, parts: undefined });
    const called = String(fetchMock.mock.calls[0][0]);
    expect(called).toContain('info=1');
    expect(called).toContain('p=2');
  });

  it('returns null on a non-2xx Worker response', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse('err', { status: 500 }))
      .mockResolvedValueOnce(mockResponse('vercel', { status: 500 }));

    expect(await getBilibiliVideoTitle('BV1xx411c7mD')).toBeNull();
  });

  it('returns null when the Worker is unreachable', async () => {
    fetchMock
      .mockRejectedValueOnce(new Error('network down'))
      .mockRejectedValueOnce(new Error('vercel down'));

    expect(await getBilibiliVideoTitle('BV1xx411c7mD')).toBeNull();
  });

  it('falls back to the same-origin proxy after a Worker failure and preserves the selected part', async () => {
    fetchMock
      .mockResolvedValueOnce(mockResponse('worker err', { status: 502 }))
      .mockResolvedValueOnce(
        mockResponse(JSON.stringify({ title: 'Fallback title', ownerName: 'O', partCount: 3 }), {
          url: '/api/bilibili',
        }),
      );

    const result = await getBilibiliVideoTitle('BV1xx411c7mD', 2);

    expect(result?.title).toBe('Fallback title');
    expect(fetchMock).toHaveBeenCalledTimes(2);
    const fallbackUrl = String(fetchMock.mock.calls[1][0]);
    expect(fallbackUrl).toContain('/api/bilibili?info=1&url=');
    expect(decodeURIComponent(fallbackUrl)).toContain('https://www.bilibili.com/video/BV1xx411c7mD?p=2');
  });

  it('uses the same-origin proxy after a Worker timeout', async () => {
    const timeout = new Error('aborted');
    timeout.name = 'AbortError';
    fetchMock
      .mockRejectedValueOnce(timeout)
      .mockResolvedValueOnce(
        mockResponse(JSON.stringify({ title: 'After timeout', ownerName: 'O' }), { url: '/api/bilibili' }),
      );

    await expect(getBilibiliVideoTitle('BV1xx411c7mD')).resolves.toMatchObject({
      title: 'After timeout',
    });
  });
});
