import { describe, expect, it, vi } from 'vitest';
// Vite's raw import lets this contract test run in the browser-oriented
// TypeScript project without adding Node-only test types to the app build.
import source from '../../../cf-worker/src/index.js?raw';
import {
  CAPTION_DEADLINE_MS,
  createCaptionContext,
  createProviderContext,
  handleTranscript,
  proxiedFetch,
  readResponseBody,
  runCaptionStage,
// @ts-expect-error The Worker is plain JavaScript; this import is test-only.
} from '../../../cf-worker/src/index.js';

describe('CF Worker transcript routing contract', () => {
  it('uses ScrapingBee Bearer auth without putting the key in the gateway URL', async () => {
    const originalFetch = globalThis.fetch;
    let requestUrl = '';
    let requestInit: RequestInit | undefined;
    globalThis.fetch = vi.fn((input, init) => {
      requestUrl = String(input);
      requestInit = init;
      return Promise.resolve(new Response('<html>caption source</html>', { status: 200 }));
    }) as typeof fetch;

    try {
      const response = await proxiedFetch(
        'https://www.youtube.com/watch?v=video-id',
        {},
        1000,
        { SCRAPE_API_KEY: 'test-scrape-key' },
        () => undefined,
      );

      expect(response.status).toBe(200);
      expect(new URL(requestUrl).searchParams.has('api_key')).toBe(false);
      expect(new Headers(requestInit?.headers).get('Authorization')).toBe('Bearer test-scrape-key');
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('preserves ZenRows query authentication and helper invocation', async () => {
    const originalFetch = globalThis.fetch;
    let requestUrl = '';
    let requestInit: RequestInit | undefined;
    globalThis.fetch = vi.fn((input, init) => {
      requestUrl = String(input);
      requestInit = init;
      return Promise.resolve(new Response('<html>caption source</html>', { status: 200 }));
    }) as typeof fetch;

    try {
      const response = await proxiedFetch(
        'https://www.youtube.com/watch?v=video-id',
        {},
        1000,
        { SCRAPE_API_KEY: 'test-zenrows-key', SCRAPE_API_PROVIDER: 'zenrows' },
        () => undefined,
      );

      const gatewayUrl = new URL(requestUrl);
      expect(response.status).toBe(200);
      expect(gatewayUrl.hostname).toBe('api.zenrows.com');
      expect(gatewayUrl.searchParams.get('apikey')).toBe('test-zenrows-key');
      expect(new Headers(requestInit?.headers).get('Authorization')).toBeNull();
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('serves a valid cached caption without contacting a provider', async () => {
    const originalFetch = globalThis.fetch;
    const globals = globalThis as unknown as { caches?: unknown };
    const originalCaches = globals.caches;
    const match = vi.fn(async () => new Response(JSON.stringify({
      lines: [{ id: 'yt_1', start: 0, end: 1, text: 'cached' }],
      language: 'en',
      isAutoGenerated: false,
    }), { status: 200 }));
    const put = vi.fn();
    globals.caches = { default: { match, put } };
    const fetchMock = vi.fn(() => Promise.reject(new Error('provider should not be called')));
    globalThis.fetch = fetchMock as typeof fetch;

    try {
      const result = await handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=video-id&lang=en'),
        {},
        'cache-hit-trace',
      );
      expect(result.status).toBe(200);
      expect(result.headers.get('X-EchoLearn-Transcript-Cache')).toBe('HIT');
      expect(await result.json()).toMatchObject({ lines: [{ text: 'cached' }] });
      expect(match).toHaveBeenCalledTimes(1);
      expect(put).not.toHaveBeenCalled();
      expect(fetchMock).not.toHaveBeenCalled();
    } finally {
      globalThis.fetch = originalFetch;
      if (originalCaches === undefined) delete globals.caches;
      else globals.caches = originalCaches;
    }
  });

  it('writes only a usable caption result to the edge cache', async () => {
    const originalFetch = globalThis.fetch;
    const globals = globalThis as unknown as { caches?: unknown };
    const originalCaches = globals.caches;
    const put = vi.fn();
    globals.caches = { default: { match: vi.fn(async () => null), put } };
    globalThis.fetch = vi.fn((input) => {
      const requestUrl = String(input);
      if (requestUrl.includes('youtubei/v1/player')) {
        return Promise.resolve(new Response(JSON.stringify({
          playabilityStatus: { status: 'OK' },
          captions: {
            playerCaptionsTracklistRenderer: {
              captionTracks: [{
                baseUrl: 'https://www.youtube.com/api/timedtext?v=cache-write',
                languageCode: 'en',
              }],
            },
          },
        }), { status: 200 }));
      }
      if (requestUrl.includes('timedtext')) {
        return Promise.resolve(new Response(
          '<transcript><text start="0" dur="1">hello</text></transcript>',
          { status: 200 },
        ));
      }
      return Promise.resolve(new Response('', { status: 404 }));
    }) as typeof fetch;

    try {
      const result = await handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=cache-write&lang=en'),
        {},
        'cache-write-trace',
      );
      expect(result.status).toBe(200);
      expect(put).toHaveBeenCalledTimes(1);
      const stored = await put.mock.calls[0][1].json();
      expect(stored).toMatchObject({ lines: [{ text: 'hello' }], language: 'en' });
      expect(put.mock.calls[0][1].status).toBe(200);
    } finally {
      globalThis.fetch = originalFetch;
      if (originalCaches === undefined) delete globals.caches;
      else globals.caches = originalCaches;
    }
  });

  it('does not accept a cached JSON error as a caption response', async () => {
    const originalFetch = globalThis.fetch;
    const globals = globalThis as unknown as { caches?: unknown };
    const originalCaches = globals.caches;
    const match = vi.fn(async () => new Response(JSON.stringify({ error: 'provider_timeout' }), { status: 200 }));
    const put = vi.fn();
    globals.caches = { default: { match, put } };
    const fetchMock = vi.fn(() => Promise.resolve(new Response('', { status: 404 })));
    globalThis.fetch = fetchMock as typeof fetch;

    try {
      const result = await handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=cache-error&lang=en'),
        {},
        'cache-error-trace',
      );
      expect(result.status).toBe(502);
      expect(await result.json()).toMatchObject({ error: 'provider_failure' });
      expect(fetchMock).toHaveBeenCalled();
      expect(put).not.toHaveBeenCalled();
    } finally {
      globalThis.fetch = originalFetch;
      if (originalCaches === undefined) delete globals.caches;
      else globals.caches = originalCaches;
    }
  });

  it('keeps the direct ASR block before caption providers', () => {
    const providers = [
      'const innerTubeResult = await runBoundedCaptionStage',
      'const webResult = await runCaptionStageWithContext',
      'const invidiousResult = await runCaptionStageWithContext',
      'const pipedResult = await runCaptionStageWithContext',
    ].map((marker) => source.indexOf(marker));
    const asr = source.indexOf('if (allowAsr)');

    expect(Math.min(...providers)).toBeGreaterThan(-1);
    expect(asr).toBeLessThan(Math.min(...providers));
  });

  it('requires explicit allowAsr=1 before generation paths', () => {
    expect(source).toContain("const allowAsr = url.searchParams.get('allowAsr') === '1'");
    expect(source).toContain("error: 'asr_required'");
    expect(source).toContain('} else if (env && env.GROQ_API_KEY)');
    expect(source).toContain('if (allowAsr)');
    expect(source).toContain('clearTimeout(timer)');
    expect(source).toContain('const asrAvailable = !!(env && (env.YTDLP_API_URL || env.GROQ_API_KEY))');
  });

  it('records only trace-safe stage fields for every caption provider', () => {
    for (const stage of ['innertube', 'webpage', 'invidious', 'piped', 'deadline']) {
      expect(source).toContain(`'${stage}'`);
    }
    expect(source).toContain("traceLog('caption_stage'");
    expect(source).not.toContain('caption_stage", { url');
  });

  it('logs stage outcome and elapsed time without provider error content', async () => {
    const log = vi.spyOn(console, 'log').mockImplementation(() => undefined);
    try {
      await expect(runCaptionStage('webpage', 'safe-trace', async () => null)).resolves.toBeNull();
      const payload = JSON.parse(String(log.mock.calls[0][0]));
      expect(payload).toMatchObject({
        service: 'cf-worker-transcript',
        event: 'caption_stage',
        traceId: 'safe-trace',
        stage: 'webpage',
        outcome: 'unusable',
      });
      expect(payload).toHaveProperty('elapsedMs');
      expect(JSON.stringify(payload)).not.toContain('secret-provider-error');
    } finally {
      log.mockRestore();
    }
  });

  it('keeps a VPS-local timeout cancellable without aborting the global caption budget', () => {
    vi.useFakeTimers();
    const globalContext = createCaptionContext();
    const vpsContext = createProviderContext(globalContext, 5000);

    vi.advanceTimersByTime(5000);

    expect(vpsContext.signal.aborted).toBe(true);
    expect(globalContext.signal.aborted).toBe(false);
    expect(globalContext.remainingBudget()).toBeGreaterThan(0);

    vpsContext.dispose();
    globalContext.dispose();
    vi.useRealTimers();
  });

  it('returns provider_timeout when a caption body read hangs until the global deadline', async () => {
    const context = createCaptionContext(20);
    const response = { text: () => new Promise<string>(() => {}) } as unknown as Response;

    await expect(readResponseBody(response, 'text', context)).rejects.toMatchObject({
      code: 'provider_timeout',
    });
    context.dispose();
  });
});

describe('CF Worker caption deadline behavior', () => {
  it('returns a typed 504 when the caption cascade reaches its global deadline', async () => {
    vi.useFakeTimers();
    const originalFetch = globalThis.fetch;
    globalThis.fetch = vi.fn((_input, init) => new Promise<Response>((_, reject) => {
      init?.signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError')), { once: true });
    })) as typeof fetch;

    try {
      const resultPromise = handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=video-id&lang=en'),
        { YTDLP_API_URL: 'https://vps.test' },
        'deadline-trace',
      );
      await vi.advanceTimersByTimeAsync(CAPTION_DEADLINE_MS);
      const result = await resultPromise;
      expect(result.status).toBe(504);
      expect(result.headers.get('X-EchoLearn-Trace-Id')).toBe('deadline-trace');
      expect(await result.json()).toMatchObject({
        error: 'provider_timeout',
        recovery: { canAsr: true, requiresExplicitOptIn: true },
      });
    } finally {
      globalThis.fetch = originalFetch;
      vi.useRealTimers();
    }
  });

  it('does not advertise ASR recovery when no ASR route is configured', async () => {
    vi.useFakeTimers();
    const originalFetch = globalThis.fetch;
    globalThis.fetch = vi.fn((_input, init) => new Promise<Response>((_, reject) => {
      init?.signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError')), { once: true });
    })) as typeof fetch;

    try {
      const resultPromise = handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=video-id&lang=en'),
        {},
        'no-asr-trace',
      );
      await vi.advanceTimersByTimeAsync(CAPTION_DEADLINE_MS);
      const result = await resultPromise;
      expect(result.status).toBe(504);
      expect(await result.json()).toEqual({ error: 'provider_timeout', message: 'Caption providers timed out.' });
    } finally {
      globalThis.fetch = originalFetch;
      vi.useRealTimers();
    }
  });

  it('routes explicit ASR directly and preserves VPS acquisition blocking', async () => {
    const originalFetch = globalThis.fetch;
    const calls: string[] = [];
    globalThis.fetch = vi.fn((input) => {
      const url = String(input);
      calls.push(url);
      return Promise.resolve(new Response(JSON.stringify({ error: 'youtube_acquisition_blocked' }), { status: 424 }));
    }) as typeof fetch;

    try {
      const result = await handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=video-id&lang=en&allowAsr=1'),
        { YTDLP_API_URL: 'https://vps.test' },
        'asr-trace',
      );
      expect(result.status).toBe(403);
      expect(result.headers.get('X-EchoLearn-Trace-Id')).toBe('asr-trace');
      expect(await result.json()).toMatchObject({ error: 'youtube_acquisition_blocked' });
      expect(calls).toHaveLength(1);
      expect(calls[0]).toContain('/api/asr?');
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('routes explicit ASR to only the preferred configured branch', async () => {
    const originalFetch = globalThis.fetch;
    const calls: string[] = [];
    globalThis.fetch = vi.fn((input) => {
      calls.push(String(input));
      return Promise.resolve(new Response(JSON.stringify({ lines: [{ text: 'audio' }], language: 'en' }), { status: 200 }));
    }) as typeof fetch;

    try {
      const result = await handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=video-id&lang=en&allowAsr=1'),
        { YTDLP_API_URL: 'https://vps.test', GROQ_API_KEY: 'configured' },
        'asr-preferred-trace',
      );
      expect(result.status).toBe(200);
      expect(calls).toHaveLength(1);
      expect(calls[0]).toContain('/api/asr?');
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('gives InnerTube the first synchronous chance before the VPS fallback', async () => {
    const originalFetch = globalThis.fetch;
    const calls: string[] = [];
    globalThis.fetch = vi.fn((input) => {
      const url = String(input);
      calls.push(url);
      if (url.includes('youtubei/v1/player')) {
        return Promise.resolve(new Response(JSON.stringify({
          playabilityStatus: { status: 'OK' },
          captions: {
            playerCaptionsTracklistRenderer: {
              captionTracks: [{
                baseUrl: 'https://www.youtube.com/api/timedtext?v=video-id',
                languageCode: 'en',
              }],
            },
          },
        }), { status: 200 }));
      }
      if (url.includes('timedtext')) {
        return Promise.resolve(new Response(
          '<transcript><text start="0" dur="1">hello</text></transcript>',
          { status: 200 },
        ));
      }
      return Promise.resolve(new Response('', { status: 404 }));
    }) as typeof fetch;

    try {
      const result = await handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=video-id&lang=en'),
        { YTDLP_API_URL: 'https://vps.test' },
        'test-trace',
      );

      expect(calls[0]).toContain('youtubei/v1/player');
      expect(calls.some((url) => url.startsWith('https://vps.test/'))).toBe(false);
      expect(result.status).toBe(200);
      expect(await result.json()).toMatchObject({ lines: [{ text: 'hello' }] });
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('reads a usable caption response without probing a second body stream', async () => {
    vi.useFakeTimers();
    const originalFetch = globalThis.fetch;
    const clone = vi.fn(() => ({ text: () => new Promise<string>(() => {}) }));
    const captionResponse = {
      ok: true,
      status: 200,
      text: async () => '<transcript><text start="0" dur="1">hello</text></transcript>',
      clone,
    } as unknown as Response;

    globalThis.fetch = vi.fn((input) => {
      const url = String(input);
      if (url.includes('youtubei/v1/player')) {
        return Promise.resolve(new Response(JSON.stringify({
          playabilityStatus: { status: 'OK' },
          captions: {
            playerCaptionsTracklistRenderer: {
              captionTracks: [{
                baseUrl: 'https://www.youtube.com/api/timedtext?v=slow-body',
                languageCode: 'en',
              }],
            },
          },
        }), { status: 200 }));
      }
      if (url.includes('timedtext')) return Promise.resolve(captionResponse);
      return Promise.resolve(new Response('', { status: 404 }));
    }) as typeof fetch;

    try {
      const resultPromise = handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=slow-body&lang=en'),
        {},
        'single-body-trace',
      );
      await vi.runAllTimersAsync();
      const result = await resultPromise;

      expect(result.status).toBe(200);
      expect(await result.json()).toMatchObject({ lines: [{ text: 'hello' }] });
      expect(clone).not.toHaveBeenCalled();
    } finally {
      globalThis.fetch = originalFetch;
      vi.useRealTimers();
    }
  });

  it('does not call the known-failed VPS caption path after InnerTube is unusable', async () => {
    const originalFetch = globalThis.fetch;
    const calls: string[] = [];
    const emptyPlayerResponse = {
      playabilityStatus: { status: 'OK' },
      captions: { playerCaptionsTracklistRenderer: { captionTracks: [] } },
    };
    globalThis.fetch = vi.fn((input) => {
      const url = String(input);
      calls.push(url);
      if (url.includes('youtubei/v1/player')) {
        return Promise.resolve(new Response(JSON.stringify(emptyPlayerResponse), { status: 200 }));
      }
      return Promise.resolve(new Response('', { status: 404 }));
    }) as typeof fetch;

    try {
      const result = await handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=video-id&lang=en'),
        { YTDLP_API_URL: 'https://vps.test' },
        'budget-trace',
      );

      expect(calls.some((url) => url.startsWith('https://vps.test/'))).toBe(false);
      expect(result.status).toBe(409);
      expect(await result.json()).toMatchObject({ error: 'asr_required' });
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('returns provider_failure instead of captions_not_found for a gateway 5xx without ASR', async () => {
    const originalFetch = globalThis.fetch;
    const emptyPlayerResponse = {
      playabilityStatus: { status: 'OK' },
      captions: { playerCaptionsTracklistRenderer: { captionTracks: [] } },
    };
    globalThis.fetch = vi.fn((input, init) => {
      const url = String(input);
      if (url.includes('youtubei/v1/player') && init?.method === 'POST') {
        return Promise.resolve(new Response(JSON.stringify(emptyPlayerResponse), { status: 200 }));
      }
      if (url.includes('app.scrapingbee.com/api/v1')) {
        return Promise.resolve(new Response('gateway unavailable', { status: 503 }));
      }
      return Promise.resolve(new Response('', { status: 404 }));
    }) as typeof fetch;

    try {
      const result = await handleTranscript(
        new URL('https://worker.test/api/transcript?videoId=video-id&lang=en'),
        { SCRAPE_API_KEY: 'configured-scrape-key' },
        'gateway-provider-failure-trace',
      );

      expect(result.status).toBe(502);
      expect(await result.json()).toEqual({
        error: 'provider_failure',
        message: 'Caption providers were unavailable.',
      });
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

});
