import { test, expect, type Page } from '@playwright/test';
import { enterGuestMode } from './helpers/guestMode';

const BVID_A = 'BV1xx411c7mD';
const BVID_B = 'BV1ab411c7mD';
const B23_URL = 'https://b23.tv/nbSyQzx';

type BilibiliRouteOptions = {
  recoveryOnDefault?: boolean;
  delayBvid?: string;
  delayMs?: number;
};

function metadata(bvid: string) {
  return {
    title: `Bilibili ${bvid}`,
    ownerName: 'E2E uploader',
    bvid,
    partCount: 2,
    parts: [
      { index: 1, title: 'Part one' },
      { index: 2, title: 'Part two' },
    ],
  };
}

function transcript(bvid: string, part: string | null, source = 'bilibili') {
  const suffix = part === '2' ? 'Part two' : bvid === BVID_B ? 'Video B' : 'Part one';
  return {
    lines: [{ start: 0, end: 2, text: `${suffix} caption` }],
    language: 'en',
    isAutoGenerated: false,
    source,
  };
}

async function seedCleanVisitor(page: Page) {
  await page.addInitScript(() => {
    localStorage.setItem('echolearn_lang', 'en');
    localStorage.setItem('echolearn-lang-chosen', '1');
    localStorage.setItem('echolearn-tour-completed-v1', '1');
    localStorage.removeItem('echolearn_current_session');
    localStorage.removeItem('echolearn_vocabulary');
    localStorage.removeItem('echolearn_sentences');
  });
}

async function routeBilibili(page: Page, options: BilibiliRouteOptions = {}) {
  const transcriptCalls: URL[] = [];
  let recoveryResponsesRemaining = options.recoveryOnDefault ? 2 : 0;

  await page.route('**/*', (route) => {
    const url = route.request().url();
    if (url.startsWith('http://localhost:5173/') || url.startsWith('http://127.0.0.1:5173/')) {
      return route.continue();
    }
    return route.abort();
  });

  // Short-link resolution uses the Worker /api/info route before the same-origin
  // fallback. Keep both local and external metadata calls deterministic.
  await page.route('**/api/info**', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(metadata(BVID_A)),
    });
  });

  await page.route('**/api/bilibili**', async (route) => {
    const requestUrl = new URL(route.request().url());
    if (requestUrl.searchParams.get('info') === '1') {
      const bvid = requestUrl.searchParams.get('bvid') || BVID_A;
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(metadata(bvid)),
      });
      return;
    }

    const bvid = requestUrl.searchParams.get('bvid') || BVID_A;
    const part = requestUrl.searchParams.get('p');
    const allowAsr = requestUrl.searchParams.get('allowAsr') === '1';
    transcriptCalls.push(requestUrl);
    const requiresRecovery = !allowAsr && recoveryResponsesRemaining > 0;
    if (requiresRecovery) recoveryResponsesRemaining -= 1;
    const body = allowAsr
      ? transcript(bvid, part, 'asr')
      : requiresRecovery
        ? {
            error: 'asr_required',
            code: 'asr_required',
            message: 'Explicit recovery required',
            recovery: { canAsr: true, requiresExplicitOptIn: true },
          }
        : transcript(bvid, part);

    const send = async () => {
      await route.fulfill({
        status: allowAsr || !requiresRecovery ? 200 : 409,
        contentType: 'application/json',
        body: JSON.stringify(body),
      });
    };
    if (!allowAsr && options.delayBvid === bvid) {
      await new Promise((resolve) => setTimeout(resolve, options.delayMs ?? 500));
    }
    await send();
  });

  return transcriptCalls;
}

async function openStudy(page: Page) {
  await page.goto('/');
  await enterGuestMode(page);
  await page.getByRole('link', { name: 'Study' }).click();
  await expect(page).toHaveURL(/\/study$/);
}

function visibleText(page: Page, text: string | RegExp) {
  return page.getByText(text).filter({ visible: true }).first();
}

test.describe('Bilibili subtitle reliability', () => {
  test('guest canonical import stays caption-only, offers explicit ASR recovery, switches parts, and restores', async ({ page }) => {
    await seedCleanVisitor(page);
    const calls = await routeBilibili(page, {
      recoveryOnDefault: true,
      delayBvid: BVID_A,
      delayMs: 250,
    });
    await openStudy(page);

    const urlInput = page.locator('#tour-study-url');
    await urlInput.fill(`https://www.bilibili.com/video/${BVID_A}`);
    await page.locator('#tour-study-load').click();

    await expect(page.getByRole('button', { name: /generate transcript/i }).filter({ visible: true })).toHaveCount(0);
    await expect(page.getByRole('button', { name: /generate transcript/i }).filter({ visible: true })).toHaveCount(1, {
      timeout: 20_000,
    });
    await expect(page.getByRole('button', { name: /loading/i }).filter({ visible: true })).toHaveCount(0);

    const ordinaryCalls = calls.filter((call) => call.searchParams.get('allowAsr') !== '1');
    expect(ordinaryCalls.length).toBeGreaterThan(0);
    expect(ordinaryCalls.every((call) => !call.searchParams.has('allowAsr'))).toBe(true);

    await page.getByRole('button', { name: /generate transcript/i }).filter({ visible: true }).first().click();
    await expect(visibleText(page, 'Part one caption')).toBeVisible({ timeout: 20_000 });

    const asrCalls = calls.filter((call) => call.searchParams.get('allowAsr') === '1');
    expect(asrCalls).toHaveLength(1);
    expect(asrCalls[0].pathname).toContain('/api/bilibili');

    // Bilibili starts in audio mode by design. Turn it off to exercise the
    // native iframe and the visible multi-part selector in the same journey.
    await page.getByRole('button', { name: 'Audio mode', exact: true }).click();
    const partSelect = page.locator('#bili-part-select');
    await expect(partSelect).toBeVisible({ timeout: 15_000 });
    await partSelect.selectOption('2');
    await expect(visibleText(page, 'Part two caption')).toBeVisible({ timeout: 20_000 });
    await expect(partSelect).toHaveValue('2');

    await page.reload();
    await enterGuestMode(page);
    await expect(visibleText(page, 'Part two caption')).toBeVisible({ timeout: 20_000 });
    await page.getByRole('button', { name: 'Audio mode', exact: true }).click();
    await expect(page.locator('#bili-part-select')).toHaveValue('2');
  });

  test('b23 resolution reaches the transcript and remains usable on a narrow viewport', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await seedCleanVisitor(page);
    await routeBilibili(page);
    await openStudy(page);

    await page.locator('#tour-study-url').fill(B23_URL);
    await page.locator('#tour-study-load').click();
    await expect(visibleText(page, 'Part one caption')).toBeVisible({ timeout: 20_000 });
    await expect(page.getByRole('button', { name: /generate transcript/i }).filter({ visible: true })).toHaveCount(0);
    await page.getByRole('button', { name: 'Audio mode', exact: true }).click();
    await expect(page.locator('#bili-part-select')).toBeVisible({ timeout: 15_000 });

    const overflow = await page.evaluate(() => ({
      documentWidth: document.documentElement.scrollWidth,
      viewportWidth: window.innerWidth,
    }));
    expect(overflow.documentWidth).toBeLessThanOrEqual(overflow.viewportWidth + 1);
  });

  test('a newer Bilibili import wins over a late older response and loading terminates', async ({ page }) => {
    await seedCleanVisitor(page);
    await routeBilibili(page, { delayBvid: BVID_A, delayMs: 700 });
    await openStudy(page);

    const urlInput = page.locator('#tour-study-url');
    await urlInput.fill(`https://www.bilibili.com/video/${BVID_A}`);
    await page.locator('#tour-study-load').click();

    // The input remains interactive while the first request is in flight. Enter
    // starts a newer request and exercises latest-request-wins at the UI boundary.
    await urlInput.fill(`https://www.bilibili.com/video/${BVID_B}`);
    await urlInput.press('Enter');
    await expect(visibleText(page, 'Video B caption')).toBeVisible({ timeout: 20_000 });
    await expect(page.getByRole('button', { name: /loading/i }).filter({ visible: true })).toHaveCount(0);

    await page.waitForTimeout(900);
    await expect(visibleText(page, 'Video B caption')).toBeVisible();
    await expect(visibleText(page, 'Part one caption')).toHaveCount(0);
  });
});
