/**
 * EchoLearn — Local YouTube Transcript Proxy
 *
 * Runs on your machine and uses your residential IP to fetch YouTube transcripts,
 * bypassing YouTube's datacenter IP blocking that affects Vercel / Cloudflare.
 *
 * Usage:
 *   npm install
 *   npm start
 *
 * Then open EchoLearn (https://echolearnapp.vercel.app) — it will auto-detect
 * the local proxy and use it for subtitle fetching.
 *
 * Endpoints:
 *   GET /api/transcript?videoId=<id>&lang=<en>
 *   GET /health
 */

import express from 'express';
import cors from 'cors';
import { YoutubeTranscript } from 'youtube-transcript';

const PORT = parseInt(process.env.PORT || '8787', 10);
const HOST = '127.0.0.1'; // bind to localhost only

const app = express();

// ── Middleware ──────────────────────────────────────────────────
app.use(cors({ origin: true, credentials: false }));
app.use(express.json());

// ── Health check ───────────────────────────────────────────────
app.get('/health', (_req, res) => {
  res.json({
    status: 'ok',
    service: 'echolearn-local-proxy',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
  });
});

// ── Transcript endpoint ────────────────────────────────────────
app.get('/api/transcript', async (req, res) => {
  const videoId = req.query.videoId;
  const lang = (req.query.lang || 'en').toString();

  if (!videoId) {
    return res.status(400).json({ error: 'Missing videoId parameter' });
  }

  console.log(`[${ts()}] Fetching transcript: ${videoId} (lang=${lang})`);
  const startTime = Date.now();

  // Strategy 1: youtube-transcript npm package (uses your residential IP)
  try {
    const result = await YoutubeTranscript.fetchTranscript(videoId, { lang });

    if (result && result.length > 0) {
      const lines = result.map((item, i) => ({
        id: `yt_${i + 1}`,
        start: item.offset > 1000 ? item.offset / 1000 : item.offset,
        end:
          (item.offset > 1000 ? item.offset / 1000 : item.offset) +
          (item.duration > 1000 ? item.duration / 1000 : item.duration),
        text: item.text,
      }));

      const elapsed = Date.now() - startTime;
      console.log(
        `[${ts()}] OK — ${lines.length} lines in ${elapsed}ms (${result[0]?.lang || lang})`,
      );

      return res.json({
        lines,
        language: result[0]?.lang || lang,
        isAutoGenerated: false,
        source: 'local-proxy (youtube-transcript)',
      });
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[${ts()}] youtube-transcript failed: ${msg}`);
  }

  // Strategy 2: InnerTube API directly (also uses residential IP)
  try {
    const innerTubeResult = await fetchViaInnerTube(videoId, lang);
    if (innerTubeResult) {
      const elapsed = Date.now() - startTime;
      console.log(
        `[${ts()}] OK (InnerTube) — ${innerTubeResult.lines.length} lines in ${elapsed}ms`,
      );
      innerTubeResult.source = 'local-proxy (InnerTube)';
      return res.json(innerTubeResult);
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[${ts()}] InnerTube failed: ${msg}`);
  }

  // Strategy 3: Web page scraping (also uses residential IP)
  try {
    const webResult = await fetchViaWebPage(videoId, lang);
    if (webResult) {
      const elapsed = Date.now() - startTime;
      console.log(
        `[${ts()}] OK (WebPage) — ${webResult.lines.length} lines in ${elapsed}ms`,
      );
      webResult.source = 'local-proxy (WebPage)';
      return res.json(webResult);
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[${ts()}] WebPage failed: ${msg}`);
  }

  const elapsed = Date.now() - startTime;
  console.log(`[${ts()}] FAIL — no transcript found for ${videoId} (${elapsed}ms)`);
  return res.status(404).json({ error: 'No transcript available for this video' });
});

// ── InnerTube API strategy ─────────────────────────────────────

const INNERTUBE_API_URL =
  'https://www.youtube.com/youtubei/v1/player?key=AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8&prettyPrint=false';

const CONSENT_COOKIE =
  'CONSENT=PENDING+987; SOCS=CAISNQgDEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjMwODI5LjA3X3AxGgJlbiACGgYIgJnSmgY';

const ANDROID_UA =
  'com.google.android.youtube/20.10.38 (Linux; U; Android 14)';

const BROWSER_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36';

async function fetchViaInnerTube(videoId, lang) {
  const clients = [
    { name: 'ANDROID', clientVersion: '20.10.38', ua: ANDROID_UA },
    { name: 'WEB', clientVersion: '2.20241201.00.00', ua: BROWSER_UA },
  ];

  for (const client of clients) {
    try {
      const context = {
        clientName: client.name,
        clientVersion: client.clientVersion,
        hl: lang,
      };
      if (client.name === 'WEB') context.userAgent = BROWSER_UA;

      const resp = await fetch(INNERTUBE_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': client.ua,
          Cookie: CONSENT_COOKIE,
        },
        body: JSON.stringify({
          context: { client: context },
          videoId,
          contentCheckOk: true,
          racyCheckOk: true,
        }),
      });

      if (!resp.ok) continue;

      const data = await resp.json();
      if (data.playabilityStatus?.status !== 'OK') continue;

      const tracks =
        data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!Array.isArray(tracks) || tracks.length === 0) continue;

      return await fetchFromTracks(tracks, lang);
    } catch {
      continue;
    }
  }
  return null;
}

// ── Web page scraping strategy ─────────────────────────────────

async function fetchViaWebPage(videoId, lang) {
  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const resp = await fetch(pageUrl, {
    headers: {
      'User-Agent': BROWSER_UA,
      'Accept-Language': 'en-US,en;q=0.9',
      Accept: 'text/html,application/xhtml+xml',
      Cookie: CONSENT_COOKIE,
    },
    redirect: 'follow',
  });

  if (!resp.ok) return null;

  const html = await resp.text();

  // Check for CAPTCHA
  if (
    html.includes('class="g-recaptcha"') ||
    html.includes('id="captcha-form"') ||
    html.includes('<title>Sorry')
  ) {
    return null;
  }

  // Extract ytInitialPlayerResponse
  const patterns = [
    'var ytInitialPlayerResponse = ',
    'ytInitialPlayerResponse = ',
  ];

  for (const token of patterns) {
    const idx = html.indexOf(token);
    if (idx < 0) continue;

    const jsonStart = idx + token.length;
    if (html[jsonStart] !== '{') continue;

    const jsonStr = extractJsonObject(html, jsonStart);
    if (!jsonStr) continue;

    try {
      const playerResponse = JSON.parse(jsonStr);
      const tracks =
        playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!Array.isArray(tracks) || tracks.length === 0) continue;

      return await fetchFromTracks(tracks, lang);
    } catch {
      continue;
    }
  }

  return null;
}

// ── Caption track fetching & parsing ───────────────────────────

async function fetchFromTracks(tracks, lang) {
  const manual = tracks.find((t) => t.languageCode === lang && t.kind !== 'asr');
  const auto = tracks.find((t) => t.languageCode === lang && t.kind === 'asr');
  const anyLang = tracks.find((t) => t.languageCode === lang);
  const track = manual || auto || anyLang || tracks[0];

  const trackLang = track.languageCode || lang;
  const isAutoGenerated = track.kind === 'asr';

  for (const fmt of ['json3', undefined, 'srv3']) {
    try {
      let captionUrl = track.baseUrl;
      if (fmt && !captionUrl.includes('fmt=')) {
        captionUrl += (captionUrl.includes('?') ? '&' : '?') + `fmt=${fmt}`;
      }

      const resp = await fetch(captionUrl, {
        headers: {
          'User-Agent': BROWSER_UA,
          'Accept-Language': lang,
          Cookie: CONSENT_COOKIE,
        },
      });

      if (!resp.ok) continue;
      const text = await resp.text();
      const lines = parseCaptionData(text);
      if (lines.length > 0) {
        return { lines, language: trackLang, isAutoGenerated };
      }
    } catch {
      continue;
    }
  }

  return null;
}

function parseCaptionData(data) {
  // JSON3 format
  if (data.trimStart().startsWith('{')) {
    try {
      const json = JSON.parse(data);
      const events = json.events || [];
      const lines = [];
      let id = 0;
      for (const event of events) {
        const text = (event.segs || []).map((s) => s.utf8).join('').trim();
        if (!text || text === '\n') continue;
        lines.push({
          id: `yt_${++id}`,
          start: event.tStartMs / 1000,
          end: (event.tStartMs + event.dDurationMs) / 1000,
          text,
        });
      }
      if (lines.length > 0) return lines;
    } catch { /* not JSON */ }
  }

  // XML format
  if (data.includes('<')) {
    return parseXml(data);
  }

  return [];
}

function parseXml(xml) {
  const lines = [];
  let id = 0;
  let match;

  // srv3 format
  const pRegex = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
  while ((match = pRegex.exec(xml)) !== null) {
    const startMs = parseInt(match[1], 10);
    const durMs = parseInt(match[2], 10);
    const inner = match[3];
    let text = '';
    const sRegex = /<s[^>]*>([^<]*)<\/s>/g;
    let sMatch;
    while ((sMatch = sRegex.exec(inner)) !== null) {
      text += sMatch[1];
    }
    if (!text) text = inner.replace(/<[^>]+>/g, '');
    text = decodeEntities(text).trim();
    if (text) {
      lines.push({
        id: `yt_${++id}`,
        start: startMs / 1000,
        end: (startMs + durMs) / 1000,
        text,
      });
    }
  }
  if (lines.length > 0) return lines;

  // Classic format
  const classicRegex =
    /<text\s+start="([\d.]+)"\s+dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
  while ((match = classicRegex.exec(xml)) !== null) {
    const start = parseFloat(match[1]);
    const dur = parseFloat(match[2]);
    const text = decodeEntities(match[3]).replace(/\n/g, ' ').trim();
    if (text) {
      lines.push({
        id: `yt_${++id}`,
        start,
        end: start + dur,
        text,
      });
    }
  }
  return lines;
}

function decodeEntities(str) {
  return str
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\\u0026/g, '&')
    .replace(/\\"/g, '"');
}

/**
 * Extract a complete JSON object from a string, properly handling
 * string literals and escape sequences.
 */
function extractJsonObject(src, startIdx) {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = startIdx; i < src.length; i++) {
    const ch = src[i];
    if (escaped) { escaped = false; continue; }
    if (inString) {
      if (ch === '\\') escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === '{') depth++;
    else if (ch === '}') { depth--; if (depth === 0) return src.slice(startIdx, i + 1); }
  }
  return null;
}

// ── Helpers ────────────────────────────────────────────────────

function ts() {
  return new Date().toLocaleTimeString('en-US', { hour12: false });
}

// ── Start server ───────────────────────────────────────────────

app.listen(PORT, HOST, () => {
  console.log('');
  console.log('  ┌──────────────────────────────────────────────┐');
  console.log('  │   EchoLearn Local YouTube Transcript Proxy   │');
  console.log('  ├──────────────────────────────────────────────┤');
  console.log(`  │   Listening on: http://${HOST}:${PORT}       │`);
  console.log('  │                                              │');
  console.log('  │   Using YOUR residential IP for YouTube      │');
  console.log('  │   requests — bypasses datacenter IP blocks.  │');
  console.log('  │                                              │');
  console.log('  │   Keep this running while using EchoLearn.   │');
  console.log('  │   Press Ctrl+C to stop.                      │');
  console.log('  └──────────────────────────────────────────────┘');
  console.log('');
});
