import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import YouTubeEmbed, { type PlayerHandle } from '../components/YouTubeEmbed';
import BilibiliEmbed from '../components/BilibiliEmbed';
import AudioPlayer from '../components/AudioPlayer';
import TranscriptViewer from '../components/TranscriptViewer';
import TranscriptImporter from '../components/TranscriptImporter';
import AIAnalysisPanel from '../components/AIAnalysisPanel';
import MobileTranscriptPanel from '../components/study/MobileTranscriptPanel';
import SavedItemsPanel from '../components/study/SavedItemsPanel';
import { parseYouTubeId, parseStartTime } from '../utils/youtube';
import { detectPlatform, parseBilibiliId, parseBilibiliStartTime, parseBilibiliPage } from '../utils/bilibili';
import { normalizeTranscriptToSentences } from '../utils/transcriptNormalizer';
import { attachTranscriptToSession, createFreshStudySession, normalizeStudyUrl } from '../utils/studySession';
import { lemmatize } from '../utils/lemmatizer';
import { analyzeTranscript } from '../services/aiAnalysis';
import { trackEvent } from '../services/analytics';
import { fetchYouTubeTranscript, YOUTUBE_ACQUISITION_BLOCKED } from '../services/youtubeTranscript';
import { fetchBilibiliTranscript, getBilibiliVideoTitle, getBilibiliMetaByUrl } from '../services/bilibiliTranscript';
import { enrichVocabularyItem } from '../services/vocabularyEnrichment';
import { pushItemsToCloud, pushSessionToCloud } from '../services/firestoreSync';
import { useAuth } from '../contexts/AuthContext';
import { CEFR_LEVELS, type CEFRLevel } from '../services/cefrWordList';
import { useI18n } from '../i18n/I18nContext';
import { useCaptionRequest } from '../hooks/useCaptionRequest';
import { useSleepTimer } from '../hooks/useSleepTimer';
import { useAudioMode } from '../hooks/useAudioMode';
import { usePlaybackPosition } from '../hooks/usePlaybackPosition';
import { useTranscriptSeek } from '../hooks/useTranscriptSeek';
import { getVideoTitle } from '../services/youtubeApi';
import sampleTranscript from '../data/sample-transcript.json';
import {
  loadVocabulary,
  addVocabularyItem,
  removeVocabularyItem,
  updateVocabularyItem,
  loadSentences,
  addSentenceItem,
  removeSentenceItem,
  loadCurrentSession,
  saveCurrentSession,
  clearCurrentSession,
  addCompletedVideoId,
  removeCompletedVideoId,
  loadDailyPlan,
  updateDailyPlanItem,
} from '../utils/storage';
import type {
  TranscriptLine,
  VocabularyItem,
  SentenceItem,
  VideoStudySession,
  BiliPart,
  AIAnalysisResult,
  VideoPlatform,
} from '../types';

/**
 * Turn a transcript-fetch result into a short human-readable source label for
 * the success toast, so the user (and we, via screenshots) can tell which path
 * produced the subtitles: official captions vs AI/Whisper transcription.
 * `t` is injected so the label respects the active locale (no hardcoded Chinese
 * when the UI is English).
 */
function transcriptSourceLabel(
  t: (k: string, vars?: Record<string, string | number>) => string,
  platform: VideoPlatform,
  res: { source?: string; isAutoGenerated?: boolean },
): string {
  if (platform === 'bilibili') {
    return res.source === 'asr'
      ? t('study.sourceWhisper')
      : t('study.sourceBiliOfficial');
  }
  if (res.source && /whisper|asr/i.test(res.source)) return t('study.sourceWhisper');
  if (res.source === 'vps') return t('study.sourceVpsDirect');
  if (res.source === 'auto' || res.isAutoGenerated) return t('study.sourceYoutubeAuto');
  if (res.source === 'youtube' || !res.source) return t('study.sourceYoutubeOfficial');
  return t('study.sourceGeneric', { source: res.source });
}

const SPEED_PRESETS = [0.5, 0.75, 1, 1.25, 1.5, 1.75, 2];

// ── Demo / sample video ──────────────────────────────────────
// When a user opens Study with no saved session, we pre-load a well-known,
// caption-rich English talk so the UI (and the onboarding tour) can showcase
// the live Load / Analyze / Save buttons. The video plays; the transcript is
// fetched from YouTube. If that fetch fails (e.g. blocked), we fall back to a
// small built-in transcript so the buttons still appear for the demo.
const SAMPLE_VIDEO_ID = 'iG9CE55wbtY'; // Ken Robinson — Do schools kill creativity?
const SAMPLE_VIDEO_TITLE = 'Sample · Ken Robinson: Do schools kill creativity?';

// Full sample transcript is bundled so the demo loads instantly without waiting
// for a network fetch from YouTube. See src/data/sample-transcript.json.
const SAMPLE_FALLBACK_TRANSCRIPT: TranscriptLine[] = sampleTranscript;

const StudyPage: React.FC = () => {
  const { t, lang } = useI18n();
  const { user } = useAuth();
  const navigate = useNavigate();

  // Guest mode: toast prompt when trying to use login-required features
  const [loginToast, setLoginToast] = useState(false);
  const [saveToast, setSaveToast] = useState<'vocabulary' | 'sentences' | null>(null);
  const saveToastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const loginToastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const showLoginToast = useCallback(() => {
    setLoginToast(true);
    if (loginToastTimer.current) clearTimeout(loginToastTimer.current);
    loginToastTimer.current = setTimeout(() => setLoginToast(false), 3000);
  }, []);

  // Debounced cloud sync — pushes vocabulary/sentences 2s after last change
  const syncTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const triggerCloudSync = useCallback(() => {
    if (!user?.uid) return;
    if (syncTimerRef.current) clearTimeout(syncTimerRef.current);
    syncTimerRef.current = setTimeout(() => {
      pushItemsToCloud(user.uid).catch(() => { /* silent */ });
    }, 2000);
  }, [user]);

  // Debounced session sync — pushes sessions 5s after last change (they're larger)
  const sessionSyncTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const triggerSessionSync = useCallback(() => {
    if (!user?.uid) return;
    if (sessionSyncTimerRef.current) clearTimeout(sessionSyncTimerRef.current);
    sessionSyncTimerRef.current = setTimeout(() => {
      pushSessionToCloud(user.uid).catch(() => { /* silent */ });
    }, 5000);
  }, [user]);

  // ── Session state ──────────────────────────────────────────
  const [session, setSession] = useState<VideoStudySession | null>(null);

  // Video state
  const [urlInput, setUrlInput] = useState('');
  const [videoId, setVideoId] = useState<string | null>(null);
  const [startTime, setStartTime] = useState<number | undefined>(undefined);
  const [sessionTitle, setSessionTitle] = useState('');
  const [platform, setPlatform] = useState<VideoPlatform>('youtube');
  const [biliPage, setBiliPage] = useState<number | undefined>(undefined);
  const [biliParts, setBiliParts] = useState<BiliPart[] | undefined>(undefined);

  // Audio mode — extracted audio transport + canonical URL derivation + cache
  // pre-warm live in useAudioMode (platform rule: Bilibili auto-enables).
  const { audioMode, setAudioMode, audioSrc, audioFallbackSrc } =
    useAudioMode({ session, platform, videoId, biliPage });

  // Transcript state — raw caption blocks + sentence-level lines
  const [rawBlocks, setRawBlocks] = useState<TranscriptLine[]>([]);
  const [sentenceLines, setSentenceLines] = useState<TranscriptLine[]>([]);

  // Saved data state (all items, filtered by current video for display)
  const [vocabulary, setVocabulary] = useState<VocabularyItem[]>([]);
  const [sentences, setSentences] = useState<SentenceItem[]>([]);

  // Tab state for the bottom panel

  // AI analysis state
  const [analysis, setAnalysis] = useState<AIAnalysisResult | null>(null);
  const [analyzing, setAnalyzing] = useState(false);

  // CEFR level range for vocabulary extraction
  const [cefrMin, setCefrMin] = useState<CEFRLevel>(
    () => (localStorage.getItem('echolearn_cefr_min') as CEFRLevel) || 'B1',
  );
  const [cefrMax, setCefrMax] = useState<CEFRLevel>(
    () => (localStorage.getItem('echolearn_cefr_max') as CEFRLevel) || 'C2',
  );

  // AI analysis output counts (defaults; UI count steppers removed)
  const [vocabCount] = useState(
    () => Number(localStorage.getItem('echolearn_vocab_count')) || 15,
  );
  const [sentenceCount] = useState(
    () => Number(localStorage.getItem('echolearn_sentence_count')) || 4,
  );

  // Streaming progress
  const [streamChars, setStreamChars] = useState(0);

  // Auto-fetch status — request generation, race protection, elapsed ticker
  // and success toast all live in useCaptionRequest; the bindings below keep
  // the historical names so the JSX reads unchanged.
  const {
    fetching: fetchingCaption,
    error: captionError,
    setError: setCaptionError,
    elapsed: fetchElapsed,
    fetchToast,
    clearFetchToast,
    begin: beginCaptionRequest,
    run: runCaptionRequest,
    isCurrent: isCaptionRequestCurrent,
    end: endCaptionRequest,
    fail: failCaptionRequest,
    invalidate: invalidateCaptionRequests,
  } = useCaptionRequest();
  // Distinguish a genuine "this video has no captions" from a network/blocked
  // failure — the backend throws the same error shape for both, so we sniff the
  // message to give the user a precise reason instead of a generic error.
  const isNoCaptions =
    !!captionError &&
    /^No captions\/subtitles available/i.test(captionError.trim());
  const isYoutubeAcquisitionBlocked = captionError === YOUTUBE_ACQUISITION_BLOCKED;

  // Analysis error state
  const [analysisError, setAnalysisError] = useState<string | null>(null);

  // Ref to track if we've done the initial restore
  const restoredRef = useRef(false);
  // Track which session ID we've loaded, so we can detect new sessions from Dashboard
  const loadedSessionIdRef = useRef<string | null>(null);
  const { pathname } = useLocation();

  // YouTube player ref & playback time
  const playerRef = useRef<PlayerHandle>(null);

  // Tracks which videoId the currently-displayed title actually belongs to.
  // We only re-fetch the real title when the loaded video CHANGES, so a title
  // left over from a previously-viewed video can never leak onto a new one.
  // (This was the root cause of a Chinese title showing on an English video on
  // mobile: the old `if (!sessionTitle)` guard skipped the refresh whenever a
  // stale title was already present.)
  const titleSyncedForRef = useRef<string | null>(null);
  // Remembers the last fetched Bilibili part list so switching sessions on the
  // same video doesn't lose the picker (the title fetch is skipped in that case).
  const partsCacheRef = useRef<{ vid: string; parts: BiliPart[] } | null>(null);

  const refreshTitleForVideo = useCallback(
    (
      url: string,
      sessionId: string,
      vid: string,
      fetcher: (u: string) => Promise<{ title: string; partCount?: number; parts?: BiliPart[] } | null>,
    ) => {
      if (titleSyncedForRef.current === vid) {
        // title already correct for this video — just restore the cached parts
        if (partsCacheRef.current?.vid === vid) setBiliParts(partsCacheRef.current.parts);
        return;
      }
      titleSyncedForRef.current = vid;
      setSessionTitle(url); // immediate fallback = raw URL
      fetcher(url)
        .then((info) => {
        if (!info?.title) return;
        const parts = info.parts && info.parts.length ? info.parts : undefined;
        partsCacheRef.current = parts ? { vid, parts } : null;
        setBiliParts(parts);
        setSessionTitle(info.title);
          setSession((prev) => {
            if (prev && prev.id === sessionId) {
              const u = { ...prev, title: info.title };
              saveCurrentSession(u);
              return u;
            }
            return prev;
          });
        })
        .catch(() => {
          /* keep the URL fallback if the title lookup fails */
        });
    },
    [],
  );

  const [resumeToast, setResumeToast] = useState<string | null>(null);

  // ── Sleep timer ────────────────────────────────────────────
  const {
    sleepMinutes,
    setSleepMinutes,
    sleepRemaining,
    setSleepRemaining,
    sleepToast,
    dismissSleepToast,
  } = useSleepTimer({ onExpire: () => playerRef.current?.pauseVideo() });

  // The lines currently shown in TranscriptViewer (always sentence-level)
  const displayLines = sentenceLines;

  const persistPlaybackPosition = useCallback((position: number) => {
    localStorage.setItem('echolearn_last_position', String(position));
    setSession((prev) => {
      if (!prev) return prev;
      const updated = { ...prev, lastPosition: position };
      try {
        localStorage.setItem('echolearn_session', JSON.stringify(updated));
      } catch { /* quota exceeded — ignore */ }
      return updated;
    });
  }, []);

  const {
    currentTime,
    playbackRate,
    setPlaybackRate,
    speedToast,
  } = usePlaybackPosition({
    playerRef,
    videoId,
    platform,
    audioMode,
    onPositionChange: persistPlaybackPosition,
  });

  const { activeLineIndex, seekTo: handleSeekTo } = useTranscriptSeek({
    playerRef,
    videoId,
    pathname,
    currentTime,
    displayLines,
  });

  // ── Restore last session on mount ──────────────────────────
  useEffect(() => {
    if (restoredRef.current) return;
    restoredRef.current = true;

    const saved = loadCurrentSession();
    if (saved) {
      loadedSessionIdRef.current = saved.id;
      // Restore the persisted session once after mount.
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setSession(saved);
      // Heal legacy sessions where youtubeId was accidentally stored as a URL
      // (e.g. a b23.tv short link or bilibili.com URL) instead of a BV id.
      let restoredVideoId = saved.youtubeId;
      if (saved.platform === 'bilibili' && !/^BV[a-zA-Z0-9]{10}$/i.test(saved.youtubeId)) {
        const fromUrl = parseBilibiliId(saved.youtubeUrl);
        if (fromUrl && /^BV[a-zA-Z0-9]{10}$/i.test(fromUrl)) {
          restoredVideoId = fromUrl;
        }
      }
      setVideoId(restoredVideoId);
      setPlatform(saved.platform || 'youtube');
      setUrlInput(saved.youtubeUrl);
      setSessionTitle(saved.title);
      setStartTime(saved.lastPosition && saved.lastPosition > 10 ? saved.lastPosition : undefined);
      if (saved.lastPosition && saved.lastPosition > 10) {
        const mins = Math.floor(saved.lastPosition / 60);
        const secs = saved.lastPosition % 60;
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setResumeToast(t('study.resumedAt', { time: `${mins}:${String(secs).padStart(2, '0')}` }));
        setTimeout(() => setResumeToast(null), 5000);
      }
      setBiliPage(saved.biliPage);

      // Always sync the displayed title to the loaded video. This heals a
      // stale title left from a previously-viewed video (root cause of a
      // Chinese title showing on an English video on mobile) while keeping a
      // user-edited title for the same video.
      refreshTitleForVideo(
        saved.youtubeUrl,
        saved.id,
        saved.youtubeId,
        saved.platform === 'bilibili'
          ? () => getBilibiliVideoTitle(saved.youtubeId, saved.biliPage)
          : getVideoTitle,
      );

      // Migrate: use transcriptData if available, else treat legacy transcriptLines as rawBlocks
      if (saved.transcriptData) {
        setRawBlocks(saved.transcriptData.rawBlocks);
        setSentenceLines(saved.transcriptData.sentenceLines);
      } else if ((saved.transcriptLines?.length ?? 0) > 0) {
        const blocks = saved.transcriptLines;
        const sLines = normalizeTranscriptToSentences(blocks);
        setRawBlocks(blocks);
        setSentenceLines(sLines);
      }

      // Restore saved AI analysis
      if (saved.aiAnalysis) {
        setAnalysis(saved.aiAnalysis);
      }

      // Auto-fetch captions if no transcript exists for this video
      const hasTranscript =
        !!saved.transcriptData || (saved.transcriptLines?.length ?? 0) > 0;
      if (saved.youtubeId && !hasTranscript) {
        runCaptionRequest(
          () =>
            saved.platform === 'bilibili'
              ? fetchBilibiliTranscript(saved.youtubeId, undefined, saved.biliPage)
              : fetchYouTubeTranscript(saved.youtubeId),
          {
            onSuccess: (res) => {
              const lines = res.lines;
              const pf: VideoPlatform = saved.platform === 'bilibili' ? 'bilibili' : 'youtube';
              if (lines.length > 0) {
                const sLines = normalizeTranscriptToSentences(lines);
                setRawBlocks(lines);
                setSentenceLines(sLines);
                const updated: VideoStudySession = {
                  ...saved,
                  transcriptLines: lines,
                  transcriptData: { rawBlocks: lines, sentenceLines: sLines },
                  updatedAt: Date.now(),
                };
                saveCurrentSession(updated);
                setSession(updated);
                return { count: lines.length, source: transcriptSourceLabel(t, pf, res) };
              }
            },
          },
        );
      }
    } else {
      // No saved session → pre-load a sample video so the Study UI (and the
      // onboarding tour) can showcase the real Load / Analyze / Save buttons.
      // We intentionally do NOT persist this as a session — it's a demo default.
      setVideoId(SAMPLE_VIDEO_ID);
      setPlatform('youtube');
      setSessionTitle(SAMPLE_VIDEO_TITLE);
      beginCaptionRequest();
      // Use the bundled full transcript for the sample video so the demo loads
      // instantly and never depends on a network fetch.
      const sLines = normalizeTranscriptToSentences(SAMPLE_FALLBACK_TRANSCRIPT);
      setRawBlocks(SAMPLE_FALLBACK_TRANSCRIPT);
      setSentenceLines(sLines);
      endCaptionRequest();
    }

    setVocabulary(loadVocabulary());
    setSentences(loadSentences());
  }, []);

  // ── Detect new session from Dashboard navigation ──────────
  // Because all pages are always mounted (display:none), the initial
  // useEffect only runs once. When the user clicks a video in Dashboard,
  // it saves a new session to localStorage and navigates to /study.
  // We detect this by watching pathname and comparing session IDs.
  useEffect(() => {
    if (pathname !== '/study') return;

    const saved = loadCurrentSession();
    if (!saved) return;

    // If this is the same session we already loaded, skip
    if (saved.id === loadedSessionIdRef.current) return;

    // New session detected — reload everything
    loadedSessionIdRef.current = saved.id;
    setSession(saved);
    setVideoId(saved.youtubeId);
    setPlatform(saved.platform || 'youtube');
    setUrlInput(saved.youtubeUrl);
    setSessionTitle(saved.title);
    setStartTime(saved.lastPosition && saved.lastPosition > 10 ? saved.lastPosition : undefined);
    if (saved.lastPosition && saved.lastPosition > 10) {
      const mins = Math.floor(saved.lastPosition / 60);
      const secs = saved.lastPosition % 60;
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setResumeToast(t('study.resumedAt', { time: `${mins}:${String(secs).padStart(2, '0')}` }));
      setTimeout(() => setResumeToast(null), 5000);
    }
    setBiliPage(saved.biliPage);
    setBiliParts(undefined);
    setAnalysis(null);
    setStreamChars(0);
    setCaptionError(null);

    refreshTitleForVideo(
      saved.youtubeUrl,
      saved.id,
      saved.youtubeId,
      saved.platform === 'bilibili'
        ? () => getBilibiliVideoTitle(saved.youtubeId, saved.biliPage)
        : getVideoTitle,
    );

    if (saved.transcriptData) {
      setRawBlocks(saved.transcriptData.rawBlocks);
      setSentenceLines(saved.transcriptData.sentenceLines);
    } else if ((saved.transcriptLines?.length ?? 0) > 0) {
      const blocks = saved.transcriptLines;
      const sLines = normalizeTranscriptToSentences(blocks);
      setRawBlocks(blocks);
      setSentenceLines(sLines);
    } else {
      // No transcript — clear and auto-fetch
      setRawBlocks([]);
      setSentenceLines([]);
    }

    if (saved.aiAnalysis) {
      setAnalysis(saved.aiAnalysis);
    }

    // Auto-fetch captions if no transcript exists
    const hasTranscript =
      !!saved.transcriptData || (saved.transcriptLines?.length ?? 0) > 0;
    if (saved.youtubeId && !hasTranscript) {
      runCaptionRequest(
        () =>
          saved.platform === 'bilibili'
            ? fetchBilibiliTranscript(saved.youtubeId, undefined, saved.biliPage)
            : fetchYouTubeTranscript(saved.youtubeId),
        {
          // Note: no source label here — mirrors the original code, which
          // never recorded fetchSourceRef on the dashboard-navigation path.
          onSuccess: ({ lines }) => {
            if (lines.length > 0) {
              const sLines = normalizeTranscriptToSentences(lines);
              setRawBlocks(lines);
              setSentenceLines(sLines);
              const updated: VideoStudySession = {
                ...saved,
                transcriptLines: lines,
                transcriptData: { rawBlocks: lines, sentenceLines: sLines },
                updatedAt: Date.now(),
              };
              saveCurrentSession(updated);
              setSession(updated);
              return { count: lines.length, source: null };
            }
          },
        },
      );
    }

    setVocabulary(loadVocabulary());
    setSentences(loadSentences());
  }, [pathname]);

  // ── Filtered data for current video ────────────────────────
  const filteredVocabulary = useMemo(() => {
    if (videoId) return vocabulary.filter((v) => v.sourceVideoId === videoId);
    // No current video ID. Only fall back to the entire collection when there is
    // genuinely no video loaded at all (the "browse all" / cleared-session view).
    // When a video IS on screen but its ID is still unknown — e.g. a b23.tv
    // short link that hasn't resolved yet, or a failed load on mobile — show
    // nothing instead of dumping every collected item under that one video,
    // which is confusing. `handleClearSession` clears both `session` and
    // `videoId`, so the intentional browse-all view still shows everything.
    return session ? [] : vocabulary;
  }, [vocabulary, videoId, session]);
  const filteredSentences = useMemo(() => {
    if (videoId) return sentences.filter((s) => s.sourceVideoId === videoId);
    return session ? [] : sentences;
  }, [sentences, videoId, session]);

  // Derived sets for quick lookup
  const savedWords = useMemo(
    () => new Set(filteredVocabulary.map((v) => (v.lemma || lemmatize(v.word)).toLowerCase())),
    [filteredVocabulary],
  );
  const savedSentencesSet = useMemo(
    () => new Set(filteredSentences.map((s) => s.text)),
    [filteredSentences],
  );
  const savedSentenceIds = useMemo(
    () => new Map(filteredSentences.map((s) => [s.text, s.id])),
    [filteredSentences],
  );

  // ── Persist session helper ─────────────────────────────────
  const persistSession = useCallback(
    (
      yId: string,
      yUrl: string,
      raw: TranscriptLine[],
      sLines: TranscriptLine[],
      title: string,
      status: VideoStudySession['status'] = 'studying',
    ) => {
      const now = Date.now();
      let pos = session?.lastPosition ?? 0;
      try { pos = Math.floor(playerRef.current?.getCurrentTime?.() ?? pos); } catch { /* noop */ }
      const updated: VideoStudySession = {
        id: session?.id || `session_${now}`,
        youtubeUrl: normalizeStudyUrl(yUrl),
        youtubeId: yId,
        platform,
        title,
        transcriptLines: raw, // legacy compat
        transcriptData: { rawBlocks: raw, sentenceLines: sLines },
        createdAt: session?.createdAt || now,
        updatedAt: now,
        status,
        lastPosition: pos,
      };
      saveCurrentSession(updated);
      setSession(updated);
      if (!session?.id) trackEvent('video_studied', { platform });
      triggerSessionSync();
    },
    [session, platform, triggerSessionSync],
  );

  // ── Shared: import raw blocks → normalize → persist ────────
  const importTranscript = useCallback(
    (raw: TranscriptLine[]) => {
      const sLines = normalizeTranscriptToSentences(raw);
      setRawBlocks(raw);
      setSentenceLines(sLines);
      // Prefer the current session's identity so we never accidentally save
      // under a stale (e.g. sample) video id captured from the render closure.
      const yId = session?.youtubeId ?? videoId;
      const yUrl = session?.youtubeUrl ?? urlInput.trim() ?? yId;
      const title = session?.title ?? sessionTitle ?? urlInput.trim() ?? yId;
      if (yId) {
        persistSession(yId, yUrl, raw, sLines, title);
      }
    },
    [session, videoId, urlInput, sessionTitle, persistSession],
  );

  // ── Load video ─────────────────────────────────────────────
  const handleLoadVideo = useCallback(() => {
    const detected = detectPlatform(urlInput);
    if (!detected) return;

    setPlatform(detected);

    const persistTranscriptInto = (sess: VideoStudySession, lines: TranscriptLine[]) => {
      const sLines = normalizeTranscriptToSentences(lines);
      setRawBlocks(lines);
      setSentenceLines(sLines);
      const updated = attachTranscriptToSession(sess, lines, sLines, Date.now());
      saveCurrentSession(updated);
      setSession(updated);
    };

    if (detected === 'bilibili') {
      const parsed = parseBilibiliId(urlInput);
      // `parsed` is either a BV id ("BV1xx...") or, for a b23.tv short link,
      // the full URL ("https://b23.tv/xxx") that the backend resolves to a BV id.
      const isShortLink = !!parsed && parsed.startsWith('http');
      const st = parseBilibiliStartTime(urlInput);
      const pg = parseBilibiliPage(urlInput);

      // Persist the genuinely-old session (a real studied video) before
      // switching. The sample video has no session, so it is never saved.
      if (session && rawBlocks.length > 0 && videoId) {
        persistSession(videoId, urlInput.trim(), rawBlocks, sentenceLines, sessionTitle || urlInput.trim());
      }

      const now = Date.now();
      const fresh = createFreshStudySession({
        id: `session_${now}_${Math.random().toString(36).slice(2, 8)}`,
        now,
        videoId: parsed && !isShortLink ? parsed : urlInput.trim(),
        url: urlInput.trim(),
        platform: 'bilibili',
        biliPage: pg,
      });
      if (!session) trackEvent('video_studied', { platform: 'bilibili' });
      saveCurrentSession(fresh);
      setSession(fresh);
      // Clear the input as soon as a valid video starts loading, so the next
      // paste is always clean and the user gets immediate "click accepted"
      // feedback (no more "I clicked Load and nothing happened").
      setUrlInput('');
      loadedSessionIdRef.current = fresh.id;
      setVideoId(parsed && !isShortLink ? parsed : '');
      setStartTime(st);
      setBiliPage(pg);
      setBiliParts(undefined);
      setRawBlocks([]);
      setSentenceLines([]);
      setAnalysis(null);

      const req = beginCaptionRequest();

      // Resolve a b23.tv short link to a BV id via the VPS, then proceed exactly
      // like a normal BV-id load. Runs async so the UI can show the loading state.
      (async () => {
        let bvid: string | null = isShortLink ? null : parsed;
        if (isShortLink && parsed) {
          try {
            const meta = await getBilibiliMetaByUrl(parsed);
            if (!isCaptionRequestCurrent(req)) return;
            if (meta?.bvid) {
              bvid = meta.bvid;
              setVideoId(bvid);
              if (meta.title) {
                const updated = { ...fresh, title: meta.title, youtubeId: bvid };
                saveCurrentSession(updated);
                setSession(updated);
              }
              if (meta.partCount && meta.parts) {
                setBiliParts(meta.parts);
              }
            } else {
              // Resolution returned but with no bvid (timeout / 401 / network).
              // Surface it instead of silently leaving an empty player.
              failCaptionRequest(t('study.biliResolveFailed'), req);
              return;
            }
          } catch {
            if (!isCaptionRequestCurrent(req)) return;
            failCaptionRequest(t('study.biliResolveError'), req);
            return;
          }
        }
        if (!isCaptionRequestCurrent(req)) return;
        if (!bvid) {
          failCaptionRequest(t('study.biliUnrecognized'), req);
          return;
        }
        refreshTitleForVideo(urlInput, fresh.id, bvid, () => getBilibiliVideoTitle(bvid!, pg));
        runCaptionRequest(
          () => fetchBilibiliTranscript(bvid!, undefined, pg),
          {
            // Attach to the request opened above so the elapsed timer keeps
            // running from the original Load click (short-link resolution can
            // take tens of seconds on its own).
            begin: false,
            onSuccess: (res) => {
              const lines = res.lines;
              if (lines.length > 0) {
                persistTranscriptInto(fresh, lines);
                return { count: lines.length, source: transcriptSourceLabel(t, 'bilibili', res) };
              }
            },
          },
        );
      })();
    } else {
      // YouTube
      const id = parseYouTubeId(urlInput);
      if (!id) return;
      const st = parseStartTime(urlInput);

      if (session && rawBlocks.length > 0 && videoId) {
        persistSession(videoId, urlInput.trim(), rawBlocks, sentenceLines, sessionTitle || urlInput.trim());
      }

      const now = Date.now();
      const fresh = createFreshStudySession({
        id: `session_${now}_${Math.random().toString(36).slice(2, 8)}`,
        now,
        videoId: id,
        url: urlInput.trim(),
        platform: 'youtube',
      });
      if (!session) trackEvent('video_studied', { platform: 'youtube' });
      saveCurrentSession(fresh);
      setSession(fresh);
      // Clear the input as soon as a valid video starts loading (see bilibili
      // branch for rationale).
      setUrlInput('');
      loadedSessionIdRef.current = fresh.id;
      setVideoId(id);
      setStartTime(st);
      setBiliPage(undefined);
      setBiliParts(undefined);
      setRawBlocks([]);
      setSentenceLines([]);
      setAnalysis(null);

      // Always refresh the title for the newly pasted video. Don't gate on an
      // empty sessionTitle — that let a stale title leak across videos.
      refreshTitleForVideo(urlInput, fresh.id, id, getVideoTitle);

      runCaptionRequest(() => fetchYouTubeTranscript(id), {
        onSuccess: (res) => {
          const lines = res.lines;
          if (lines.length > 0) {
            persistTranscriptInto(fresh, lines);
            return { count: lines.length, source: transcriptSourceLabel(t, 'youtube', res) };
          }
        },
      });
    }
  }, [urlInput, rawBlocks, sentenceLines, sessionTitle, session, videoId, persistSession]);

  // ── Import transcript (from TranscriptImporter) ─────────────
  const handleImportTranscript = useCallback(
    (lines: TranscriptLine[]) => {
      importTranscript(lines);
    },
    [importTranscript],
  );

  // ── Clear current session ──────────────────────────────────
  const handleClearSession = useCallback(() => {
    // Invalidate any in-flight caption request so it cannot repopulate the
    // cleared session when it eventually resolves.
    invalidateCaptionRequests();
    clearCurrentSession();
    setSession(null);
    setVideoId(null);
    setStartTime(undefined);
    setUrlInput('');
    setSessionTitle('');
    setRawBlocks([]);
    setSentenceLines([]);
    setAnalysis(null);
    setCaptionError(null);
    setPlatform('youtube');
    setBiliPage(undefined);
    setBiliParts(undefined);
  }, []);

  // ── Reload transcript for the current video ────────────────
  const handleReloadTranscript = useCallback(() => {
    if (!videoId) {
      failCaptionRequest(t('study.videoNotReady'));
      return;
    }
    runCaptionRequest(
      () =>
        platform === 'bilibili'
          ? fetchBilibiliTranscript(videoId, undefined, biliPage)
          : fetchYouTubeTranscript(videoId),
      {
        onSuccess: (res) => {
          const lines = res.lines;
          if (lines.length > 0) {
            const sLines = normalizeTranscriptToSentences(lines);
            setRawBlocks(lines);
            setSentenceLines(sLines);
            if (session) {
              const updated = { ...session, transcriptLines: lines, transcriptData: { rawBlocks: lines, sentenceLines: sLines } };
              saveCurrentSession(updated);
              setSession(updated);
            }
            return { count: lines.length, source: transcriptSourceLabel(t, platform, res) };
          }
        },
        errorMessage: (err) => (err instanceof Error ? err.message : 'Unknown error'),
      },
    );
  }, [videoId, platform, session, biliPage]);

  // ── Switch Bilibili part (分p) ────────────────────────────
  const handleBiliPartChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => {
      const part = parseInt(e.target.value, 10);
      if (!videoId || !part || part === (biliPage ?? 1)) return;
      setBiliPage(part);
      // Drop the previous part's transcript/analysis immediately so nothing stale shows.
      setRawBlocks([]);
      setSentenceLines([]);
      setAnalysis(null);
      // Each 分p is a different lesson, so retitle from the part list (no network call).
      const partTitle = biliParts?.find((p) => p.index === part)?.title?.trim();
      if (partTitle) setSessionTitle(partTitle);
      // Persist the chosen part right away — a reload should reopen the same part
      // even if the transcript fetch below fails.
      if (session) {
        const withPart = { ...session, biliPage: part, ...(partTitle ? { title: partTitle } : {}) };
        saveCurrentSession(withPart);
        setSession(withPart);
      }
      runCaptionRequest(() => fetchBilibiliTranscript(videoId, undefined, part), {
        onSuccess: (res) => {
          const lines = res.lines;
          if (lines.length > 0) {
            const sLines = normalizeTranscriptToSentences(lines);
            setRawBlocks(lines);
            setSentenceLines(sLines);
            setSession((prev) => {
              if (!prev) return prev;
              const updated = {
                ...prev,
                biliPage: part,
                transcriptLines: lines,
                transcriptData: { rawBlocks: lines, sentenceLines: sLines },
              };
              saveCurrentSession(updated);
              return updated;
            });
            return { count: lines.length, source: transcriptSourceLabel(t, 'bilibili', res) };
          }
        },
        errorMessage: (err) => (err instanceof Error ? err.message : 'Failed to load this part'),
      });
    },
    [videoId, session, biliPage, biliParts],
  );

  // ── Toggle session completion status ───────────────────────
  const handleToggleComplete = useCallback(() => {
    if (!session) return;
    const newStatus = session.status === 'completed' ? 'studying' : 'completed';
    const updated: VideoStudySession = { ...session, status: newStatus, updatedAt: Date.now() };
    saveCurrentSession(updated);
    setSession(updated);
    // Track/untrack in global completed video list
    if (newStatus === 'completed') {
      addCompletedVideoId(session.youtubeId);
    } else {
      removeCompletedVideoId(session.youtubeId);
    }
    // Sync daily plan item status
    const plan = loadDailyPlan();
    const planItem = plan.find((p) => p.videoId === session.youtubeId);
    if (planItem) {
      updateDailyPlanItem(planItem.id, { status: newStatus === 'completed' ? 'completed' : 'studying' });
    }
  }, [session]);

  // ── Persist AI analysis to current session ─────────────────
  const persistAnalysis = useCallback(
    (result: AIAnalysisResult) => {
      if (!session) return;
      const updated: VideoStudySession = { ...session, aiAnalysis: result, updatedAt: Date.now() };
      saveCurrentSession(updated);
      setSession(updated);
    },
    [session],
  );

  // ── Analyze transcript ──────────────────────────────────────
  const handleAnalyze = useCallback(async () => {
    if (!user) { showLoginToast(); return; }
    if (sentenceLines.length === 0) return;
    const text = sentenceLines.map((l) => l.text).join(' ');

    // Persist preferences
    localStorage.setItem('echolearn_cefr_min', cefrMin);
    localStorage.setItem('echolearn_cefr_max', cefrMax);
    localStorage.setItem('echolearn_vocab_count', String(vocabCount));
    localStorage.setItem('echolearn_sentence_count', String(sentenceCount));

    setAnalyzing(true);
    setStreamChars(0);
    setAnalysisError(null);
    try {
      const result = await analyzeTranscript(
        text,
        cefrMin,
        cefrMax,
        vocabCount,
        sentenceCount,
        (chunk) => setStreamChars((prev) => prev + chunk.length),
        lang,
      );
      setAnalysis(result);
      persistAnalysis(result);
      trackEvent('ai_analysis_used');
    } catch (err) {
      setAnalysisError(err instanceof Error ? err.message : 'Analysis failed');
    } finally {
      setAnalyzing(false);
      setStreamChars(0);
    }
  }, [user, sentenceLines, cefrMin, cefrMax, vocabCount, sentenceCount, persistAnalysis, lang, showLoginToast]);

  // ── Vocab / sentence handlers ─────────────────────────────
  // Saving is a core guest-mode feature (README: data stays on device).
  // Cloud sync below no-ops without a signed-in user, so no login gate here.
  const handleAddVocabulary = useCallback((item: VocabularyItem) => {
    setVocabulary(addVocabularyItem(item));
    setSaveToast('vocabulary');
    if (saveToastTimer.current) clearTimeout(saveToastTimer.current);
    saveToastTimer.current = setTimeout(() => setSaveToast(null), 4500);
    trackEvent('word_saved');
    triggerCloudSync();
    // Every save path (AI, transcript, popup and quick-add) is enriched the
    // same way: English definition is canonical; Chinese is a learning aid.
    void enrichVocabularyItem(item).then((patch) => {
      if (Object.keys(patch).length === 0) return;
      setVocabulary(updateVocabularyItem(item.id, patch));
      triggerCloudSync();
    });
  }, [triggerCloudSync, setVocabulary]);

  const handleAddSentence = useCallback((item: SentenceItem) => {
    setSentences(addSentenceItem(item));
    setSaveToast('sentences');
    if (saveToastTimer.current) clearTimeout(saveToastTimer.current);
    saveToastTimer.current = setTimeout(() => setSaveToast(null), 4500);
    trackEvent('sentence_saved');
    triggerCloudSync();
  }, [triggerCloudSync, setSentences]);

  const handleRemoveVocabulary = useCallback((id: string) => {
    if (!window.confirm(t('study.deleteWord'))) return;
    setVocabulary(removeVocabularyItem(id));
    triggerCloudSync();
  }, [t, triggerCloudSync, setVocabulary]);

  const handleRemoveSentence = useCallback((id: string) => {
    if (!window.confirm(t('study.deleteSent'))) return;
    setSentences(removeSentenceItem(id));
    triggerCloudSync();
  }, [t, triggerCloudSync, setSentences]);

  // Silent toggle — no confirm dialog (used by bookmark button)
  const handleToggleSentenceOff = useCallback((id: string) => {
    setSentences(removeSentenceItem(id));
    triggerCloudSync();
  }, [triggerCloudSync, setSentences]);

  // ── Render ─────────────────────────────────────────────────
  return (
    <div className="study-main">
      {/* Study toolbar */}
      <div className="bg-white dark:bg-slate-800 border-b border-gray-200 dark:border-slate-700 px-4 sm:px-6 py-3">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-2">
          <div className="flex items-center gap-4">
            {/* Session title (editable when a session exists) */}
            {session && (
              <input
                type="text"
                value={sessionTitle}
                onChange={(e) => {
                  setSessionTitle(e.target.value);
                  titleSyncedForRef.current = videoId;
                }}
                onBlur={() => {
                  if (videoId && rawBlocks.length > 0) {
                    persistSession(videoId, urlInput.trim(), rawBlocks, sentenceLines, sessionTitle);
                  }
                }}
                className="px-2 py-0.5 text-sm text-gray-600 dark:text-gray-400 border border-transparent hover:border-gray-300 dark:hover:border-gray-600 focus:border-indigo-400 focus:outline-none rounded transition-colors w-full sm:w-[420px] dark:bg-slate-800"
                placeholder={t('study.sessionTitlePh')}
              />
            )}
          </div>

          <div className="flex items-center gap-2 sm:gap-3 flex-wrap">
            <input
              id="tour-study-url"
              type="text"
              value={urlInput}
              onChange={(e) => setUrlInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleLoadVideo()}
              placeholder={t('study.urlPh')}
              className="flex-1 sm:w-80 px-3 py-1.5 text-sm border border-gray-300 dark:border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:border-transparent dark:bg-slate-800 dark:text-gray-200 min-w-[120px]"
            />
            <button
              id="tour-study-load"
              onClick={handleLoadVideo}
              disabled={fetchingCaption}
              className="px-3 sm:px-4 py-1.5 text-sm bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors font-medium cursor-pointer whitespace-nowrap disabled:opacity-60 disabled:cursor-not-allowed flex items-center gap-1.5"
            >
              {fetchingCaption ? (
                <>
                  <svg className="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  {t('common.loading')}
                </>
              ) : (
                t('study.loadVideo')
              )}
            </button>
            {session && (
              <button
                onClick={handleToggleComplete}
                className={`px-3 py-1.5 text-sm rounded-lg font-medium cursor-pointer whitespace-nowrap transition-colors ${
                  session.status === 'completed'
                    ? 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-400 border border-green-300 dark:border-green-700 hover:bg-green-200 dark:hover:bg-green-900/60'
                    : 'bg-white dark:bg-slate-800 border border-green-300 dark:border-green-700 text-green-600 dark:text-green-400 hover:bg-green-50 dark:hover:bg-green-950/30'
                }`}
                title={session.status === 'completed' ? t('study.resumeStudying') : t('study.markComplete')}
              >
                {session.status === 'completed' ? (
                  <span className="flex items-center gap-1">
                    <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    {t('study.completed')}
                  </span>
                ) : (
                  <span className="flex items-center gap-1">
                    <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    {t('study.markComplete')}
                  </span>
                )}
              </button>
            )}
            {session && (
              <button
                onClick={handleClearSession}
                className="px-3 sm:px-4 py-1.5 text-sm bg-white dark:bg-slate-800 border border-red-200 dark:border-red-800 text-red-600 dark:text-red-400 rounded-lg hover:bg-red-50 dark:hover:bg-red-950/30 transition-colors font-medium cursor-pointer whitespace-nowrap"
              >
                {t('study.clear')}
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Main content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-4 sm:py-6">
        <div className="study-layout flex flex-col lg:flex-row gap-4 lg:gap-6">
          {/* Left: video — always visible (mobile: above transcript, desktop: left column) */}
          <div className="w-full lg:w-[55%] flex-shrink-0">
            {videoId ? (
              <>
                {/* Audio mode toggle */}
                <div className="mb-2 flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => {
                      // Stop the extracted transport before unmounting it.
                      // Bilibili's native iframe is cross-origin and cannot
                      // report its pause state back to the transcript clock.
                      if (audioMode) playerRef.current?.pauseVideo();
                      setAudioMode((v) => !v);
                    }}
                    className={`flex items-center gap-1.5 px-3 py-1.5 text-xs sm:text-sm rounded-lg font-medium border transition-colors cursor-pointer ${
                      audioMode
                        ? 'bg-indigo-600 text-white border-indigo-600'
                        : 'bg-white dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-slate-700'
                    }`}
                    title={t('study.audioModeHint')}
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9 19V6l12-3v13M9 19c0 1.1-1.34 2-3 2s-3-.9-3-2 1.34-2 3-2 3 .9 3 2zm12-3c0 1.1-1.34 2-3 2s-3-.9-3-2 1.34-2 3-2 3 .9 3 2zM9 10l12-3" />
                    </svg>
                    {t('study.audioMode')}
                  </button>
                  {audioMode && (
                    <span className="text-[11px] text-gray-400 dark:text-gray-500">{t('study.audioModeOn')}</span>
                  )}
                </div>

                {audioMode ? (
                  <AudioPlayer key={audioSrc ?? 'audio'} ref={playerRef} src={audioSrc ?? ''} fallbackSrc={audioFallbackSrc ?? undefined} bilibili={platform === 'bilibili'} startTime={startTime} playbackRate={playbackRate} />
                ) : platform === 'bilibili' ? (
                  <>
                    {!/^BV[a-zA-Z0-9]{10}$/i.test(videoId) ? (
                      <div className="flex items-center justify-center rounded-xl bg-black/5 dark:bg-white/5 px-4 py-8 text-sm text-gray-500 dark:text-gray-400">
                        {t('study.biliResolving')}
                      </div>
                    ) : (
                      <>
                        {biliParts && biliParts.length > 1 && (
                          <div className="mb-2 flex items-center gap-2">
                            <label
                              htmlFor="bili-part-select"
                              className="text-xs sm:text-sm text-gray-500 dark:text-gray-400 flex-shrink-0"
                            >
                              {t('study.selectPart')}
                            </label>
                            <select
                              id="bili-part-select"
                              value={biliPage ?? 1}
                              onChange={handleBiliPartChange}
                              disabled={fetchingCaption}
                              className="flex-1 min-w-0 px-2 py-1.5 text-xs sm:text-sm bg-white dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded-lg text-gray-700 dark:text-gray-200 focus:outline-none focus:ring-2 focus:ring-indigo-400 disabled:opacity-60 cursor-pointer truncate"
                            >
                              {biliParts.map((p) => (
                                <option key={p.index} value={p.index}>
                                  P{p.index}
                                  {p.title ? ` · ${p.title}` : ''}
                                </option>
                              ))}
                            </select>
                          </div>
                        )}
                        <BilibiliEmbed ref={playerRef} bvid={videoId} page={biliPage} startTime={startTime} />
                      </>
                    )}
                  </>
                ) : (
                  <YouTubeEmbed key={lang} ref={playerRef} youtubeId={videoId} startTime={startTime} playbackRate={playbackRate} lang={lang} />
                )}
              </>
            ) : (
              <div className="w-full aspect-video rounded-xl bg-gray-100 dark:bg-slate-800 border-2 border-dashed border-gray-300 dark:border-slate-600 flex items-center justify-center">
                <div className="text-center">
                  <svg
                    className="mx-auto w-12 h-12 text-gray-300 dark:text-gray-500 mb-3"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={1.5}
                      d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"
                    />
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={1.5}
                      d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <p className="text-gray-400 dark:text-gray-500 text-sm">{t('study.pasteStart')}</p>
                </div>
              </div>
            )}

            {videoId && displayLines.length > 0 && !audioMode && platform === 'youtube' && (
              <p className="mt-2 px-3 py-2 text-xs text-slate-600 dark:text-slate-300 bg-slate-100 dark:bg-slate-800/80 rounded-lg" role="status">
                {t('study.playerStillLoading')}
              </p>
            )}

            {/* Sleep timer toast */}
            {sleepToast && (
              <div className="mt-2 flex items-center gap-2 px-3 py-2 bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800 rounded-lg text-sm text-amber-700 dark:text-amber-300">
                <svg className="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M21.752 15.002A9.718 9.718 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z" />
                </svg>
                <span>{t('study.timerPaused')}</span>
                <button
                  onClick={() => {
                    playerRef.current?.playVideo();
                    dismissSleepToast();
                  }}
                  className="ml-auto px-2 py-0.5 text-xs rounded bg-amber-200 dark:bg-amber-800/50 text-amber-800 dark:text-amber-200 hover:bg-amber-300 dark:hover:bg-amber-700/60 transition-colors cursor-pointer"
                >
                  {t('study.timerUndo')}
                </button>
                <button
                  onClick={dismissSleepToast}
                  className="text-amber-400 hover:text-amber-600 dark:hover:text-amber-200 cursor-pointer"
                >
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            )}

            {/* Resume position toast */}
            {resumeToast && (
              <div className="mt-2 flex items-center gap-2 px-3 py-2 bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-800 rounded-lg text-sm text-blue-700 dark:text-blue-300">
                <svg className="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
                </svg>
                <span>{resumeToast}</span>
                <button
                  onClick={() => setResumeToast(null)}
                  className="ml-auto text-blue-400 hover:text-blue-600 dark:hover:text-blue-200 cursor-pointer"
                >
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            )}

            {/* Transcript fetch success toast (with elapsed time) */}
            {fetchToast && (
              <div className="mt-2 flex items-center gap-2 px-3 py-2 bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800 rounded-lg text-sm text-emerald-700 dark:text-emerald-300">
                <svg className="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span>
                  {t('study.transcriptLoaded', {
                    count: fetchToast.count,
                    time: t('study.fetchElapsed', { sec: fetchToast.seconds }),
                  })}
                  {fetchToast.source ? (
                    <span className="ml-1 text-emerald-600/80 dark:text-emerald-300/70">
                      {' · '}
                      {transcriptSourceLabel(t, 'youtube', { source: fetchToast.source })}
                    </span>
                  ) : null}
                </span>
                <button
                  onClick={clearFetchToast}
                  aria-label={t('common.close') || 'Close'}
                  className="ml-auto text-emerald-400 hover:text-emerald-600 dark:hover:text-emerald-200 cursor-pointer"
                >
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            )}

            {/* Quick info */}
            {videoId && (
              <div className="mt-2 flex flex-col gap-1.5">
                {/* Playback speed + timer — merged on mobile */}
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="text-[10px] text-gray-400 dark:text-gray-500 font-medium shrink-0">
                    {t('study.speed')}:
                  </span>
                  <div className="flex items-center gap-1 sm:gap-0.5">
                    {SPEED_PRESETS.map((rate) => (
                      <button
                        key={rate}
                        onClick={() => setPlaybackRate(rate)}
                        className={`px-2 py-1 sm:px-1.5 sm:py-0.5 text-[11px] sm:text-[10px] rounded transition-colors cursor-pointer ${
                          playbackRate === rate
                            ? 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300 font-semibold'
                            : 'text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-slate-700'
                        }`}
                      >
                        {rate}x
                      </button>
                    ))}
                  </div>
                  {/* Slider — compact on mobile, wider on desktop */}
                  <div className="flex items-center gap-1 flex-1 min-w-[100px] sm:min-w-[140px] relative">
                    <input
                      type="range"
                      min={0.25}
                      max={3}
                      step={0.05}
                      value={playbackRate}
                      onChange={(e) => setPlaybackRate(parseFloat(e.target.value))}
                      className="flex-1 h-1 accent-indigo-500 cursor-pointer"
                    />
                    <span className={`text-[10px] font-mono w-10 tabular-nums shrink-0 transition-opacity duration-300 ${
                      speedToast
                        ? 'text-indigo-600 dark:text-indigo-400 font-semibold opacity-100'
                        : 'text-gray-500 dark:text-gray-400 opacity-0 sm:opacity-100'
                    }`}>
                      {playbackRate.toFixed(2)}x
                    </span>
                  </div>
                  {/* Timer — on same row as speed on mobile */}
                  <div className="flex items-center gap-1">
                    <span className="text-[10px] text-gray-400 dark:text-gray-500 font-medium shrink-0 ml-1">
                      {t('study.timer')}:
                    </span>
                    <div className="flex items-center gap-0.5">
                      {[0, 15, 30, 45, 60].map((min) => (
                        <button
                          key={min}
                          onClick={() => setSleepMinutes(min)}
                          className={`px-1 py-0.5 text-[10px] rounded transition-colors cursor-pointer ${
                            sleepMinutes === min
                              ? 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300 font-semibold'
                              : 'text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-slate-700'
                          }`}
                        >
                          {min === 0 ? t('study.timerOff') : `${min}`}
                        </button>
                      ))}
                    </div>
                    {/* Manual minute input */}
                    <input
                      type="number"
                      min={1}
                      max={180}
                      placeholder="min"
                      value=""
                      onChange={(e) => {
                        const v = Math.max(0, Math.min(180, Number(e.target.value) || 0));
                        if (v > 0) setSleepMinutes(v);
                        e.target.value = '';
                      }}
                      className="w-10 px-1 py-0.5 text-[10px] border border-gray-200 dark:border-slate-700 rounded bg-white dark:bg-slate-800 text-gray-600 dark:text-gray-400 focus:outline-none text-center"
                      title={t('study.timerCustom')}
                    />
                  </div>
                </div>
                {sleepRemaining > 0 && (
                  <span className="flex items-center gap-1.5 text-[10px] text-amber-600 dark:text-amber-400 font-mono tabular-nums">
                    {t('study.timerRemaining', {
                      time: `${Math.floor(sleepRemaining / 60)}:${String(sleepRemaining % 60).padStart(2, '0')}`,
                    })}
                    <button
                      onClick={() => { setSleepMinutes(0); setSleepRemaining(0); }}
                      className="text-[9px] font-sans px-1.5 py-0.5 rounded bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300 hover:bg-amber-200 dark:hover:bg-amber-800/50 transition-colors cursor-pointer"
                    >
                      {t('study.timerCancel')}
                    </button>
                  </span>
                )}
                {/* Video info — hidden on mobile, visible on desktop */}
                <div className="hidden sm:flex items-center gap-3 text-xs text-gray-400 dark:text-gray-500">
                  <span>{platform === 'bilibili' ? 'Bilibili' : 'YouTube'}: {videoId}</span>
                  {startTime !== undefined && <span>Start: {startTime}s</span>}
                  {session && (
                    <span className={`px-1.5 py-0.5 rounded text-[10px] font-medium ${
                      session.status === 'studying'
                        ? 'bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400'
                        : session.status === 'completed'
                          ? 'bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400'
                          : 'bg-gray-100 text-gray-500 dark:bg-slate-700 dark:text-gray-400'
                    }`}>
                      {session.status === 'completed' ? t('study.completed') : session.status === 'studying' ? t('study.resumeStudying') : t('dash.statusDraft')}
                    </span>
                  )}
                </div>
              </div>
            )}

            {/* ── Mobile inline transcript — visible below video on small screens ── */}
            {videoId && displayLines.length > 0 && (
              <div translate="no" className="notranslate lg:hidden mt-2 bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm overflow-hidden">
                {/* Header with Analyze button on same row */}
                <div className="flex items-center justify-between px-3 py-1.5 border-b border-gray-100 dark:border-slate-700">
                  <span className="text-[10px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                    {t('study.subtitles')}
                  </span>
                  <div className="flex items-center gap-2">
                    {fetchingCaption && (
                      <span className="flex items-center gap-1 text-[10px] text-amber-500">
                        <svg className="animate-spin w-2.5 h-2.5" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                        </svg>
                        {t(platform === 'bilibili' ? 'study.fetchingShortBili' : 'study.fetchingShort')}
                      </span>
                    )}
                    {displayLines.length > 0 && (
                      <button
                        data-tour="study-ai"
                        onClick={handleAnalyze}
                        disabled={analyzing}
                        title={t('study.analyzeTooltip')}
                        className="flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 rounded-lg hover:bg-indigo-100 dark:hover:bg-indigo-900 transition-colors cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        {analyzing ? (
                          <>
                            <svg className="animate-spin w-2.5 h-2.5" fill="none" viewBox="0 0 24 24">
                              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                            </svg>
                            {streamChars > 0 ? `${streamChars}` : t('study.analyzing')}
                          </>
                        ) : (
                          <>
                            <svg className="w-2.5 h-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
                            </svg>
                            {analysis ? t('study.reAnalyze') : t('study.analyze')}
                          </>
                        )}
                      </button>
                    )}
                    {displayLines.length > 0 && (
                      <button
                        onClick={handleReloadTranscript}
                        disabled={fetchingCaption}
                        className="flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium text-gray-500 dark:text-gray-400 hover:text-indigo-500 dark:hover:text-indigo-400 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
                      >
                        <svg className={`w-2.5 h-2.5 ${fetchingCaption ? 'animate-spin' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                          <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                        </svg>
                        {t('study.reloadTranscript')}
                      </button>
                    )}
                  </div>
                </div>
                {/* Mobile analysis controls — words/sents/level only */}
                {displayLines.length > 0 && (
                  <div data-tour="study-controls" className="flex items-center gap-2 px-3 py-1.5 border-b border-gray-100 dark:border-slate-700 flex-wrap">
                    <div className="flex items-center gap-1 text-[10px]" title={t('study.levelTooltip')}>
                      <span className="text-gray-400">{t('study.level')}</span>
                      <select
                        value={cefrMin}
                        title={t('study.levelTooltip')}
                        onChange={(e) => {
                          const v = e.target.value as CEFRLevel;
                          setCefrMin(v);
                          if (CEFR_LEVELS.indexOf(v) > CEFR_LEVELS.indexOf(cefrMax)) setCefrMax(v);
                        }}
                        className="px-1 py-0.5 border border-gray-200 dark:border-slate-700 rounded text-[10px] bg-white dark:bg-slate-800 text-gray-600 dark:text-gray-400 focus:outline-none cursor-pointer"
                      >
                        {CEFR_LEVELS.map((l) => (
                          <option key={l} value={l}>{l}</option>
                        ))}
                      </select>
                      <span className="text-gray-300">–</span>
                      <select
                        value={cefrMax}
                        title={t('study.levelTooltip')}
                        onChange={(e) => {
                          const v = e.target.value as CEFRLevel;
                          setCefrMax(v);
                          if (CEFR_LEVELS.indexOf(v) < CEFR_LEVELS.indexOf(cefrMin)) setCefrMin(v);
                        }}
                        className="px-1 py-0.5 border border-gray-200 dark:border-slate-700 rounded text-[10px] bg-white dark:bg-slate-800 text-gray-600 dark:text-gray-400 focus:outline-none cursor-pointer"
                      >
                        {CEFR_LEVELS.map((l) => (
                          <option key={l} value={l}>{l}</option>
                        ))}
                      </select>
                    </div>
                  </div>
                )}
                <p className="px-3 py-1.5 text-[11px] text-indigo-600 dark:text-indigo-300 bg-indigo-50/70 dark:bg-indigo-950/30 border-b border-indigo-100 dark:border-indigo-900">
                  {t('study.transcriptHint')}
                </p>
                <MobileTranscriptPanel
                  lines={displayLines}
                  activeLineIndex={activeLineIndex}
                  videoId={videoId || 'unknown'}
                  videoTitle={sessionTitle}
                  savedWords={savedWords}
                  savedSentences={savedSentencesSet}
                  savedSentenceIds={savedSentenceIds}
                  onAddVocabulary={handleAddVocabulary}
                  onAddSentence={handleAddSentence}
                  onRemoveSentence={handleToggleSentenceOff}
                  onSeekTo={(seconds) => playerRef.current?.seekTo(seconds)}
                />
              </div>
            )}

            {/* ── Mobile subtitle status — below the video on small screens ──
                On phones the desktop transcript column (hidden lg:flex) is not
                rendered, so loading / no-captions / manual-import states must be
                shown here, otherwise the user sees a blank area after pasting a URL. */}
            {videoId && !displayLines.length && fetchingCaption && (
              <div className="lg:hidden mt-2 bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm px-4 py-7 flex flex-col items-center justify-center text-gray-400 dark:text-gray-500">
                <svg className="animate-spin w-7 h-7 mb-3 text-indigo-400" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                <p className="text-sm">{platform === 'bilibili' ? t('study.fetchingFullBili') : t('study.fetchingFull')}</p>
                <p className="text-xs mt-1 text-gray-300 dark:text-gray-500">
                  {platform === 'bilibili' ? t('study.mayTakeBili') : t('study.mayTake')}
                  {' · '}{t('study.fetchElapsed', { sec: fetchElapsed })}
                </p>
              </div>
            )}

            {!displayLines.length && captionError && (
              <div className="lg:hidden mt-2 bg-white dark:bg-slate-800 rounded-xl border border-red-200 dark:border-red-800 shadow-sm px-4 py-5">
                <div className="flex flex-col items-center text-center">
                  <svg className="w-7 h-7 text-red-400 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
                  </svg>
                  <p className="text-sm text-red-600 dark:text-red-400 font-medium mb-1">
                    {isYoutubeAcquisitionBlocked ? t('study.captionBlockedTitle') : isNoCaptions ? t('study.captionNoneTitle') : t('study.captionErrorFriendly')}
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mb-3">
                    {isYoutubeAcquisitionBlocked ? t('study.captionBlockedReason') : isNoCaptions ? t('study.captionNoneReason') : t('study.captionErrorSuggestions')}
                  </p>
                  <div className="flex gap-3">
                    {!isYoutubeAcquisitionBlocked && <>
                      <button
                        onClick={handleReloadTranscript}
                        disabled={!videoId || fetchingCaption}
                        title={!videoId ? t('study.videoNotReady') : undefined}
                        className="text-xs text-indigo-500 hover:text-indigo-700 dark:hover:text-indigo-300 cursor-pointer"
                      >
                        {t('study.retry')}
                      </button>
                      <span className="text-gray-300 dark:text-gray-600">|</span>
                    </>}
                    <button
                      onClick={() => setCaptionError(null)}
                      className="text-xs text-indigo-500 hover:text-indigo-700 dark:hover:text-indigo-300 cursor-pointer"
                    >
                      {t('study.dismiss')}
                    </button>
                  </div>
                </div>
              </div>
            )}

            {videoId && !displayLines.length && !fetchingCaption && !captionError && (
              <div className="lg:hidden mt-2">
                <TranscriptImporter onImport={handleImportTranscript} />
              </div>
            )}
          </div>

          {/* Right: Transcript — always visible on desktop, tab-gated on mobile */}
          <div translate="no" className="notranslate hidden lg:flex flex-1 flex-col min-w-0 h-[calc(100vh-160px)]">
            {/* Panel header */}
            <div className="flex-shrink-0 order-1 px-3 py-2 border-b border-gray-200 dark:border-slate-700">
              <h2 className="text-xs font-semibold text-gray-600 dark:text-gray-400 uppercase tracking-wider">
                {t('study.transcript')}
              </h2>
            </div>

            {/* Toolbar — footer below transcript content */}
            <div className="flex-shrink-0 order-3 flex items-center justify-end px-2 py-1 border-t border-gray-200 dark:border-slate-700 gap-1 sm:gap-2">
              <div className="flex items-center gap-1.5 sm:gap-3 flex-wrap">
                {/* Caption fetch status */}
                {fetchingCaption && (
                  <span className="flex items-center gap-1 text-[11px] text-amber-500">
                    <svg className="animate-spin w-3 h-3" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    {t('study.fetchingCaption')} <span className="tabular-nums opacity-80">· {fetchElapsed}s</span>
                  </span>
                )}
                {/* Count selectors + CEFR + Analyze (only when transcript loaded) */}
                {displayLines.length > 0 && (
                  <div data-tour="study-controls" className="flex items-center gap-1.5 sm:gap-3 flex-wrap">
                    {/* CEFR level range selector */}
                    <div className="flex items-center gap-1 text-[11px]" title={t('study.levelTooltip')}>
                      <span className="text-gray-400 dark:text-gray-500 mr-0.5">{t('study.level')}</span>
                      <select
                        value={cefrMin}
                        title={t('study.levelTooltip')}
                        onChange={(e) => {
                          const v = e.target.value as CEFRLevel;
                          setCefrMin(v);
                          if (CEFR_LEVELS.indexOf(v) > CEFR_LEVELS.indexOf(cefrMax)) {
                            setCefrMax(v);
                          }
                        }}
                        className="px-1.5 py-1 border border-gray-200 dark:border-slate-700 rounded text-[11px] bg-white dark:bg-slate-800 text-gray-600 dark:text-gray-400 focus:outline-none focus:ring-1 focus:ring-indigo-300 cursor-pointer"
                      >
                        {CEFR_LEVELS.map((l) => (
                          <option key={l} value={l}>{l}</option>
                        ))}
                      </select>
                      <span className="text-gray-300 dark:text-gray-500">–</span>
                      <select
                        value={cefrMax}
                        title={t('study.levelTooltip')}
                        onChange={(e) => {
                          const v = e.target.value as CEFRLevel;
                          setCefrMax(v);
                          if (CEFR_LEVELS.indexOf(v) < CEFR_LEVELS.indexOf(cefrMin)) {
                            setCefrMin(v);
                          }
                        }}
                        className="px-1.5 py-1 border border-gray-200 dark:border-slate-700 rounded text-[11px] bg-white dark:bg-slate-800 text-gray-600 dark:text-gray-400 focus:outline-none focus:ring-1 focus:ring-indigo-300 cursor-pointer"
                      >
                        {CEFR_LEVELS.map((l) => (
                          <option key={l} value={l}>{l}</option>
                        ))}
                      </select>
                    </div>
                  </div>
                )}
                {/* Analyze button */}
                {displayLines.length > 0 && (
                  <button
                    data-tour="study-ai"
                    onClick={handleAnalyze}
                    disabled={analyzing}
                    title={t('study.analyzeTooltip')}
                    className="flex items-center gap-1.5 px-3 py-1 text-[11px] font-medium bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 rounded-lg hover:bg-indigo-100 dark:hover:bg-indigo-900 transition-colors cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {analyzing ? (
                      <>
                        <svg className="animate-spin w-3 h-3" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                        </svg>
                        {streamChars > 0 ? `${streamChars} ${t('study.chars')}` : t('study.analyzing')}
                      </>
                    ) : (
                      <>
                        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                          <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
                        </svg>
                        {analysis ? t('study.reAnalyze') : t('study.analyze')}
                      </>
                    )}
                  </button>
                )}
                <span
                  className="text-[10px] text-gray-400 dark:text-gray-500 cursor-help"
                  title={t('study.totalLinesTooltip')}
                >
                  {`${sentenceLines.length} ${t('study.totalLines')}`}
                </span>
                {videoId && (
                  <button
                    onClick={handleReloadTranscript}
                    disabled={fetchingCaption}
                    title={t('study.reloadTranscript')}
                    className="flex items-center gap-1 px-2 py-1 text-[11px] text-gray-500 dark:text-gray-400 hover:text-indigo-500 dark:hover:text-indigo-400 disabled:opacity-40 disabled:cursor-not-allowed cursor-pointer"
                  >
                    <svg className={`w-3.5 h-3.5 ${fetchingCaption ? 'animate-spin' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                    <span className="hidden sm:inline">{t('study.reloadTranscript')}</span>
                  </button>
                )}
              </div>
            </div>

            {/* Scrollable content area — fills the space between header and toolbar */}
            <div className="flex-1 overflow-y-auto min-h-0 pr-1 order-2">
            {displayLines.length > 0 ? (
              <>
                <p className="mb-2 px-3 py-2 text-xs text-indigo-700 dark:text-indigo-300 bg-indigo-50/70 dark:bg-indigo-950/30 border border-indigo-100 dark:border-indigo-900 rounded-lg">
                  {t('study.transcriptHint')}
                </p>
                <TranscriptViewer
                lines={displayLines}
                videoId={videoId || 'unknown'}
                videoTitle={sessionTitle}
                onAddVocabulary={handleAddVocabulary}
                onAddSentence={handleAddSentence}
                onRemoveSentence={handleToggleSentenceOff}
                savedWords={savedWords}
                savedSentences={savedSentencesSet}
                savedSentenceIds={savedSentenceIds}
                activeLineIndex={activeLineIndex}
                onSeekTo={handleSeekTo}
                />
              </>
            ) : fetchingCaption ? (
              <div className="flex flex-col items-center justify-center py-16 text-gray-400 dark:text-gray-500">
                <svg className="animate-spin w-8 h-8 mb-3 text-indigo-400" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                <p className="text-sm">{platform === 'bilibili' ? t('study.fetchingFullBili') : t('study.fetchingFull')}</p>
                <p className="text-xs mt-1 text-gray-300 dark:text-gray-500">
                  {platform === 'bilibili' ? t('study.mayTakeBili') : t('study.mayTake')}
                  {' · '}{t('study.fetchElapsed', { sec: fetchElapsed })}
                </p>
              </div>
            ) : captionError ? (
              <div className="flex flex-col items-center justify-center py-12">
                <div className="bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded-xl p-5 max-w-md text-center">
                  <svg className="w-8 h-8 text-red-400 mx-auto mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
                  </svg>
                  <p className="text-sm text-red-600 dark:text-red-400 font-medium mb-1">
                    {isYoutubeAcquisitionBlocked ? t('study.captionBlockedTitle') : isNoCaptions ? t('study.captionNoneTitle') : t('study.captionErrorFriendly')}
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mb-3">
                    {isYoutubeAcquisitionBlocked ? t('study.captionBlockedReason') : isNoCaptions ? t('study.captionNoneReason') : t('study.captionErrorSuggestions')}
                  </p>
                  <details className="text-left mt-2">
                    <summary className="text-xs text-gray-400 dark:text-gray-500 cursor-pointer hover:text-gray-600 dark:hover:text-gray-300">{t('study.captionErrorDetails')}</summary>
                    <p className="text-xs text-red-500/50 dark:text-red-400/40 mt-1 whitespace-pre-line break-all">{captionError}</p>
                  </details>
                </div>
                <div className="flex gap-3 mt-3">
                  {!isYoutubeAcquisitionBlocked && <>
                    <button
                      onClick={handleReloadTranscript}
                      disabled={!videoId || fetchingCaption}
                      title={!videoId ? '视频仍在准备中' : undefined}
                      className="text-xs text-indigo-500 hover:text-indigo-700 dark:hover:text-indigo-300 cursor-pointer"
                    >
                      {t('study.retry')}
                    </button>
                    <span className="text-gray-300 dark:text-gray-600">|</span>
                  </>}
                  <button
                    onClick={() => setCaptionError(null)}
                    className="text-xs text-indigo-500 hover:text-indigo-700 dark:hover:text-indigo-300 cursor-pointer"
                  >
                    {t('study.dismiss')}
                  </button>
                </div>
              </div>
            ) : videoId ? (
              <TranscriptImporter onImport={handleImportTranscript} />
            ) : (
              <div className="text-center py-12 text-gray-400 dark:text-gray-500 text-sm">
                <p>{t('study.noVideo')}</p>
                <p className="mt-1">{t('study.loadToStart')}</p>
              </div>
            )}
            </div>
          </div>
        </div>

        {/* Analysis error banner */}
        {analysisError && (
          <div className="mt-4 flex items-center gap-2 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded-lg px-4 py-3">
            <svg className="w-4 h-4 text-red-500 dark:text-red-400 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
            </svg>
            <p className="text-sm text-red-600 dark:text-red-400 flex-1">{analysisError}</p>
            <button onClick={() => setAnalysisError(null)} className="text-red-400 dark:text-red-500 hover:text-red-600 dark:hover:text-red-300 cursor-pointer">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        )}

        {/* AI Analysis Panel */}
        {analysis && (
          <div>
            <AIAnalysisPanel
              analysis={analysis}
              videoId={videoId || 'unknown'}
              videoTitle={sessionTitle}
              onAddVocabulary={handleAddVocabulary}
              onAddSentence={handleAddSentence}
              savedWords={savedWords}
              savedSentences={savedSentencesSet}
              onClose={() => setAnalysis(null)}
            />
          </div>
        )}

        <SavedItemsPanel
          vocabulary={filteredVocabulary}
          sentences={filteredSentences}
          onRemoveVocabulary={handleRemoveVocabulary}
          onRemoveSentence={handleRemoveSentence}
          onSeekSentence={(seconds) => handleSeekTo(seconds, true)}
        />
      </main>

      {/* Guest login toast */}
      {loginToast && (
        <div className="fixed bottom-20 md:bottom-6 left-4 right-4 md:left-auto md:right-6 md:max-w-sm z-50 px-4 py-3 rounded-xl shadow-lg border text-sm flex items-center gap-2 bg-violet-50 dark:bg-violet-950 border-violet-200 dark:border-violet-800 text-violet-700 dark:text-violet-300">
          <svg className="w-4 h-4 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
          </svg>
          <span className="flex-1">{t('study.loginRequired')}</span>
          <button onClick={() => setLoginToast(false)} className="flex-shrink-0 opacity-60 hover:opacity-100 cursor-pointer">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      )}

      {saveToast && (
        <div className="fixed bottom-20 md:bottom-6 left-4 right-4 md:left-6 md:right-auto md:max-w-md z-50 px-4 py-3 rounded-xl shadow-lg border text-sm flex items-center gap-3 bg-emerald-50 dark:bg-emerald-950 border-emerald-200 dark:border-emerald-800 text-emerald-700 dark:text-emerald-300" role="status">
          <span className="font-medium flex-1">{t(saveToast === 'vocabulary' ? 'study.wordSaved' : 'study.sentenceSaved')}</span>
          <button
            type="button"
            onClick={() => navigate(saveToast === 'vocabulary' ? '/vocabulary' : '/sentences')}
            className="shrink-0 font-semibold underline underline-offset-2 hover:text-emerald-900 dark:hover:text-emerald-100 cursor-pointer"
          >
            {t(saveToast === 'vocabulary' ? 'study.openVocabulary' : 'study.openSentences')}
          </button>
          <button type="button" onClick={() => setSaveToast(null)} aria-label={t('common.close')} className="shrink-0 text-emerald-500 hover:text-emerald-800 cursor-pointer">×</button>
        </div>
      )}
    </div>
  );
};

export default StudyPage;
