import type { VideoPlatform } from '../types';

export function transcriptSourceLabel(
  t: (key: string, vars?: Record<string, string | number>) => string,
  platform: VideoPlatform,
  result: { source?: string; isAutoGenerated?: boolean },
): string {
  if (platform === 'bilibili') {
    return result.source === 'asr'
      ? t('study.sourceWhisper')
      : t('study.sourceBiliOfficial');
  }
  if (result.source && /whisper|asr/i.test(result.source)) return t('study.sourceWhisper');
  if (result.source === 'vps') return t('study.sourceVpsDirect');
  if (result.source === 'auto' || result.isAutoGenerated) return t('study.sourceYoutubeAuto');
  if (result.source === 'youtube' || !result.source) return t('study.sourceYoutubeOfficial');
  return t('study.sourceGeneric', { source: result.source });
}
