import type {
  AIAnalysisResult,
  TranscriptLine,
  TranscriptMeta,
} from '../types';
import { matchSuggestionToLineStart } from './matchTranscriptLine';

/**
 * Content-derived transcript identity.
 *
 * A session can end up with a different transcript than the one its saved data
 * was produced from: the same videoId re-acquires (reload, ASR, another
 * provider), the cloud copy carries no transcript at all, or a learner imports
 * one by hand. Nothing downstream could previously tell "same transcript" from
 * "same video, different transcript". These helpers give every acquisition a
 * stable identity without a migration: the fingerprint derives from the line
 * content itself, so legacy sessions gain one the first time it is computed.
 *
 * The hash is deliberately NOT cryptographic (no SHA-256 / async Web Crypto):
 * it only needs to answer "is this the same transcript as before" for data the
 * app itself produced, and a synchronous deterministic fingerprint keeps it
 * recomputable from anything already in localStorage.
 */

/** FNV-1a 32-bit — short, synchronous, and stable across sessions. */
function fnv1a(input: string): string {
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i += 1) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

/**
 * Fingerprint a transcript by its exact line sequence. `t1-` versions the
 * algorithm; the line count rides along so a (vanishingly unlikely) hash
 * collision between different transcripts is at least visible in the value.
 */
export function fingerprintTranscriptLines(lines: TranscriptLine[]): string {
  if (lines.length === 0) return '';
  const basis = lines.map((line) => `${line.start}:${line.text}`).join('\n');
  return `t1-${fnv1a(basis)}-${lines.length}`;
}

/** Identity for one acquisition, from the lines plus whatever is declared. */
export function buildTranscriptMeta(
  rawBlocks: TranscriptLine[],
  declared?: { language?: string; isAutoGenerated?: boolean; source?: string },
): TranscriptMeta {
  const meta: TranscriptMeta = { transcriptId: fingerprintTranscriptLines(rawBlocks) };
  if (declared?.language !== undefined) meta.language = declared.language;
  if (declared?.isAutoGenerated !== undefined) meta.isAutoGenerated = declared.isAutoGenerated;
  if (declared?.source !== undefined) meta.source = declared.source;
  return meta;
}

/** The lines the analysis/alignment pipeline anchors to (raw blocks preferred). */
function alignmentBasis(rawBlocks: TranscriptLine[], sentenceLines: TranscriptLine[]): TranscriptLine[] {
  return rawBlocks.length > 0 ? rawBlocks : sentenceLines;
}

/** Fingerprint of whatever transcript is currently attached, '' when none. */
export function currentTranscriptId(
  rawBlocks: TranscriptLine[],
  sentenceLines: TranscriptLine[],
): string {
  return fingerprintTranscriptLines(alignmentBasis(rawBlocks, sentenceLines));
}

/**
 * True when a restored aiAnalysis was produced from a DIFFERENT transcript than
 * the one now on screen. Analyses without a `transcriptId` (legacy) and
 * sessions without a transcript are never stale — that keeps today's behavior
 * for old data; new analyses bind at analyze time via `currentTranscriptId`.
 */
export function isAnalysisStale(
  analysis: AIAnalysisResult | undefined,
  rawBlocks: TranscriptLine[],
  sentenceLines: TranscriptLine[],
): boolean {
  if (!analysis?.transcriptId) return false;
  const basis = alignmentBasis(rawBlocks, sentenceLines);
  if (basis.length === 0) return false;
  return analysis.transcriptId !== fingerprintTranscriptLines(basis);
}

/**
 * Grounding gate for AI output: a suggested "quote" that cannot be re-anchored
 * to the transcript it claims to come from is dropped rather than stored as
 * learning material. Uses the same matcher and threshold as the seek
 * alignment, so what the panel can jump to is exactly what survives here.
 * Returns the analysis unchanged when everything grounds (or when there is no
 * transcript to ground against).
 */
export function dropUngroundedSuggestions(
  analysis: AIAnalysisResult,
  rawBlocks: TranscriptLine[],
  sentenceLines: TranscriptLine[],
): AIAnalysisResult {
  const basis = alignmentBasis(rawBlocks, sentenceLines);
  if (basis.length === 0) return analysis;
  const grounded = analysis.sentenceSuggestions.filter(
    (sug) => matchSuggestionToLineStart(sug.text, basis) !== null,
  );
  if (grounded.length === analysis.sentenceSuggestions.length) return analysis;
  return { ...analysis, sentenceSuggestions: grounded };
}
