"""
EchoLearn — server-side YouTube transcript service (FastAPI + yt-dlp)

Runs on a small always-on VPS. yt-dlp does the heavy lifting: it rotates
YouTube client signatures (web / android / tv / ios) and the TVHTML5 client
bypasses YouTube's datacenter-IP bot check, so captions can be fetched
without a residential proxy for the vast majority of videos.

Endpoints
  GET /api/transcript?videoId=<id>&lang=<en>
  GET /api/transcript?url=<any yt-dlp supported url>&lang=<zh-CN>
  GET /api/asr?url=<any yt-dlp supported url>
  GET /api/info?url=<any yt-dlp supported url>
  GET /api/health

Response shape (matches the EchoLearn web/Worker contract):
  {
    "lines": [{"id": "yt_1", "start": 0.0, "end": 1.23, "text": "..."}, ...],
    "language": "en",
    "isAutoGenerated": false
  }

Environment
  YTDLP_TIMEOUT   subprocess hard timeout in seconds (default 90)
  YTDLP_PROXY     optional upstream proxy passed to yt-dlp (e.g. a residential
                  proxy endpoint). Applied to YouTube and Bilibili — the latter
                  needs it because Bilibili's watch page returns HTTP 412 from
                  datacenter IPs (even though its JSON API is reachable without it).
                  Also used for Groq calls: Groq blocks many VPS/datacenter IPs
                  with HTTP 403 (error 1010), so the residential exit fixes that too.
  YTDLP_API_KEY   if set, /api/transcript and /api/asr require header X-Api-Key to match
  YTDLP_CACHE_TTL in-memory cache TTL in seconds for fetched transcripts (default 3600)
  YTDLP_COOKIES   optional path to a Netscape cookies.txt used for non-YouTube
                  sites. Bilibili only exposes subtitle tracks to logged-in
                  sessions, so a SESSDATA cookie is required there.
  YTDLP_RETRIES   number of yt-dlp subprocess attempts before giving up (default 5).
                  Useful when the residential proxy tunnel drops mid-transfer.
  GROQ_API_KEY    enables /api/asr (Whisper transcription via Groq)
  GROQ_MODEL      Groq speech model (default whisper-large-v3-turbo)
  ASR_MAX_DURATION  reject ASR requests longer than this many seconds (default 1800)

Note on the proxy: YTDLP_PROXY is applied to YouTube and Bilibili URLs. The
Bilibili *watch page* returns HTTP 412 from the VPS datacenter IP (only its
JSON API is reachable cleanly). yt-dlp's Bilibili extractor fetches that page
first, so Bilibili extraction must go through the residential proxy to bypass
the 412. Quota impact is modest at EchoLearn's scale (~30 MB per audio).

Note on Bilibili transcripts: Bilibili gates *subtitle tracks* behind a login,
but audio streams are served to anonymous clients. With a SESSDATA cookie in
YTDLP_COOKIES, the transcript route can fetch the real (or auto) subtitle tracks
— this is the preferred, fast, free path. When that fails (no cookie, or a video
with no subtitle track), the caller falls back to ASR, which sidesteps the login
wall by transcribing the audio instead — no SESSDATA cookie needed for that.
"""

import json
import os
import re
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
import uuid
from collections import OrderedDict
from typing import Optional

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

app = FastAPI(title="EchoLearn yt-dlp transcript service")

# Permissive CORS: this is a private service fronted by Cloudflare; the CF
# Worker calls it server-to-server (no Origin), but allow all origins so it
# can also be called directly during local testing.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "OPTIONS"],
    allow_headers=["*"],
)

YTDLP_TIMEOUT = int(os.environ.get("YTDLP_TIMEOUT", "180"))
YTDLP_PROXY = os.environ.get("YTDLP_PROXY") or ""
YTDLP_API_KEY = os.environ.get("YTDLP_API_KEY") or ""
YTDLP_CACHE_TTL = int(os.environ.get("YTDLP_CACHE_TTL", "3600"))  # seconds
YTDLP_COOKIES = os.environ.get("YTDLP_COOKIES") or ""
YTDLP_RETRIES = int(os.environ.get("YTDLP_RETRIES", "5"))  # yt-dlp subprocess attempts

GROQ_API_KEY = os.environ.get("GROQ_API_KEY") or ""
GROQ_MODEL = os.environ.get("GROQ_MODEL", "whisper-large-v3-turbo")
GROQ_ENDPOINT = "https://api.groq.com/openai/v1/audio/transcriptions"
GROQ_TIMEOUT = int(os.environ.get("GROQ_TIMEOUT", "180"))
# Groq's free tier rejects files above 25 MB. At 16 kHz mono 32 kbps that is
# roughly 108 minutes of audio, so ASR_MAX_DURATION is the binding limit.
GROQ_MAX_BYTES = 25 * 1024 * 1024
ASR_MAX_DURATION = int(os.environ.get("ASR_MAX_DURATION", "1800"))  # 30 min

_VIDEO_ID_RE = re.compile(r"^[a-zA-Z0-9_-]{6,15}$")
_ALLOWED_HOSTS = ("youtube.com", "youtu.be", "bilibili.com", "b23.tv")


def _is_youtube(target_url: str) -> bool:
    return "youtube.com" in target_url or "youtu.be" in target_url


def _is_bilibili(target_url: str) -> bool:
    return "bilibili.com" in target_url or "b23.tv" in target_url


def _host_allowed(target_url: str) -> bool:
    """Only let known hosts through so the endpoint can't be used as an
    open yt-dlp relay for arbitrary sites."""
    if not target_url.startswith(("http://", "https://")):
        return False
    return any(h in target_url for h in _ALLOWED_HOSTS)


def _site_args(target_url: str) -> list:
    """Per-site yt-dlp flags.

    - The residential proxy is applied to YouTube and Bilibili (Bilibili's watch
      page returns HTTP 412 from datacenter IPs).
    - Cookies (YTDLP_COOKIES, e.g. a Bilibili SESSDATA jar) are applied whenever
      the file exists. Bilibili only exposes subtitle tracks to logged-in
      sessions, so the cookie is what unlocks real subtitles there — without it
      the transcript route falls through to ASR.
    """
    args: list = []
    if YTDLP_PROXY and (_is_youtube(target_url) or _is_bilibili(target_url)):
        args += ["--proxy", YTDLP_PROXY]
    if YTDLP_COOKIES and os.path.exists(YTDLP_COOKIES):
        args += ["--cookies", YTDLP_COOKIES]
    return args

# ── In-memory TTL cache (keyed by video_id:lang) ──────────────
# Protects the single VPS IP from repeat YouTube hits on popular videos and
# speeds up repeated fetches of the same video+lang. Only successful results
# are cached; failures are always retried.
_CACHE: "OrderedDict[str, tuple[float, dict]]" = OrderedDict()
_CACHE_MAX = 2000


def _cache_get(video_id: str, lang: str):
    key = f"{video_id}:{lang}"
    item = _CACHE.get(key)
    if item is None:
        return None
    expiry, payload = item
    if expiry < time.time():
        _CACHE.pop(key, None)
        return None
    _CACHE.move_to_end(key)  # LRU touch
    return payload


def _cache_put(video_id: str, lang: str, payload: dict):
    key = f"{video_id}:{lang}"
    _CACHE[key] = (time.time() + YTDLP_CACHE_TTL, payload)
    _CACHE.move_to_end(key)
    if len(_CACHE) > _CACHE_MAX:
        _CACHE.popitem(last=False)  # evict oldest


# ── Parsers ───────────────────────────────────────────────────────

def _parse_json3(raw: dict) -> list:
    events = raw.get("events", []) if isinstance(raw, dict) else []
    lines = []
    idx = 0
    for ev in events:
        segs = ev.get("segs") or []
        text = "".join(s.get("utf8", "") for s in segs).strip()
        if not text:
            continue
        start = (ev.get("tStartMs") or 0) / 1000.0
        dur = ev.get("dDurationMs") or 0
        lines.append(
            {
                "id": f"yt_{idx + 1}",
                "start": round(start, 3),
                "end": round(start + dur / 1000.0, 3),
                "text": text,
            }
        )
        idx += 1
    return lines


def _parse_vtt(text: str) -> list:
    # Strip WEBVTT header and any NOTE blocks.
    lines = []
    idx = 0
    # Split into cues by blank lines.
    blocks = re.split(r"\n\s*\n", text)
    cue_re = re.compile(
        r"(\d{1,2}:)?\d{1,2}:\d{2}\.\d{1,3}\s*-->\s*(\d{1,2}:)?\d{1,2}:\d{2}\.\d{1,3}"
    )
    for block in blocks:
        block = block.strip()
        if not block or block.startswith("WEBVTT") or block.startswith("NOTE"):
            continue
        parts = block.split("\n")
        # First line may be a cue index or the timestamp; find the timestamp line.
        ts_line = None
        text_lines = []
        for line in parts:
            if cue_re.search(line):
                ts_line = line
            elif not line.strip().isdigit() or ts_line is None:
                text_lines.append(line)
        if not ts_line:
            continue
        m = cue_re.search(ts_line)
        start_str, end_str = m.group(0).split("-->")
        start = _vtt_time_to_sec(start_str.strip())
        end = _vtt_time_to_sec(end_str.strip())
        text = " ".join(text_lines).strip()
        # Strip inline tags like <c>, <i>, <00:00:00.000>
        text = re.sub(r"<[^>]+>", "", text).strip()
        if not text:
            continue
        lines.append(
            {
                "id": f"yt_{idx + 1}",
                "start": round(start, 3),
                "end": round(end, 3),
                "text": text,
            }
        )
        idx += 1
    return lines


def _vtt_time_to_sec(s: str) -> float:
    s = s.strip()
    # Formats: HH:MM:SS.mmm or MM:SS.mmm
    parts = s.split(":")
    parts = [float(p) for p in parts]
    if len(parts) == 3:
        h, m, sec = parts
    else:
        h, m, sec = 0, parts[0], parts[1]
    return h * 3600 + m * 60 + sec


def _read_subtitle_file(td: str):
    """Return (lines, language, is_auto) for the best usable subtitle file.

    Hand-written subtitles are preferred over auto-generated ones; this matters
    most for Bilibili, where real tracks (when present) are far cleaner than the
    auto captions.
    """
    parsed = []
    for fname in sorted(os.listdir(td)):
        path = os.path.join(td, fname)
        if fname.endswith(".json3"):
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    raw = json.load(fh)
            except Exception:
                continue
            lines = _parse_json3(raw)
        elif fname.endswith(".vtt"):
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    raw = fh.read()
            except Exception:
                continue
            lines = _parse_vtt(raw)
        else:
            continue
        if not lines:
            continue
        m = re.search(r"\.([a-zA-Z]{2}(?:-[A-Za-z]+)?(?:-orig)?)\.(?:json3|vtt)$", fname)
        language = m.group(1) if m else "en"
        is_auto = "auto" in fname or "-orig" in fname
        parsed.append((is_auto, language, lines))
    if not parsed:
        return None
    # Real (False) sorts before auto (True); stable within each group.
    parsed.sort(key=lambda c: c[0])
    is_auto, language, lines = parsed[0]
    return lines, language, is_auto


# ── yt-dlp invocation ────────────────────────────────────────────

def _run_ytdlp(video_id_or_url: str, lang: str, *, is_url: bool = False):
    base = lang.split("-")[0]
    target_url = video_id_or_url if is_url else f"https://www.youtube.com/watch?v={video_id_or_url}"
    with tempfile.TemporaryDirectory() as td:
        out_tmpl = os.path.join(td, "%(id)s")
        # Try the exact requested lang, then its base code with variants
        # (covers en-US / en-orig auto captions).
        for sub_langs in (lang, f"{base}.*"):
            cmd = [
                sys.executable,
                "-m",
                "yt_dlp",
                "--skip-download",
                "--write-subs",
                "--write-auto-subs",
                "--sub-langs",
                sub_langs,
                "--sub-format",
                "vtt",
                "--quiet",
                "--no-warnings",
                "--no-playlist",
                "--no-overwrites",
                "-o",
                out_tmpl,
                target_url,
            ]
            cmd += _site_args(target_url)
            try:
                subprocess.run(
                    cmd,
                    cwd=td,
                    capture_output=True,
                    text=True,
                    timeout=YTDLP_TIMEOUT,
                )
            except subprocess.TimeoutExpired:
                continue
            result = _read_subtitle_file(td)
            if result:
                return result
        return None


def _fetch_meta(target_url: str) -> dict:
    """Title / uploader / duration / thumbnail via `yt-dlp -J`, memoised."""
    cached = _cache_get(target_url, "__info__")
    if cached is not None:
        return cached

    cmd = [
        sys.executable,
        "-m",
        "yt_dlp",
        "--skip-download",
        "--dump-single-json",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        target_url,
    ]
    cmd += _site_args(target_url)

    # The residential proxy is flaky for large Bilibili watch pages (tunnel
    # drops with IncompleteRead). A fresh process often lands on a stable IP.
    proc = None
    last_err = ""
    for attempt in range(1, YTDLP_RETRIES + 1):
        try:
            proc = subprocess.run(
                cmd, capture_output=True, text=True, timeout=YTDLP_TIMEOUT
            )
        except subprocess.TimeoutExpired:
            raise HTTPException(status_code=504, detail="Metadata lookup timed out")
        if proc.returncode == 0 and proc.stdout.strip():
            break
        last_err = proc.stderr.strip().splitlines()[-1] if proc.stderr else ""
        if attempt == YTDLP_RETRIES:
            detail = "Could not fetch video info"
            if last_err:
                detail += f" ({last_err})"
            raise HTTPException(status_code=404, detail=detail)

    if proc is None or proc.returncode != 0 or not proc.stdout.strip():
        raise HTTPException(status_code=404, detail="Could not fetch video info")

    try:
        meta = json.loads(proc.stdout)
    except json.JSONDecodeError:
        raise HTTPException(status_code=502, detail="Malformed metadata")

    payload = {
        "title": meta.get("title") or "",
        "ownerName": meta.get("uploader") or meta.get("channel") or "",
        "duration": meta.get("duration") or 0,
        "thumbnail": meta.get("thumbnail") or "",
    }
    _cache_put(target_url, "__info__", payload)
    return payload


# ── Whisper ASR via Groq ─────────────────────────────────────────

def _multipart(fields: dict, filename: str, blob: bytes, content_type: str):
    """Minimal multipart/form-data encoder.

    Hand-rolled so the service keeps its three-package dependency list and can
    be redeployed by copying a single file — no pip install on the VPS.
    """
    boundary = "----EchoLearn" + uuid.uuid4().hex
    body = bytearray()
    for key, value in fields.items():
        body += f"--{boundary}\r\n".encode()
        body += f'Content-Disposition: form-data; name="{key}"\r\n\r\n'.encode()
        body += f"{value}\r\n".encode()
    body += f"--{boundary}\r\n".encode()
    body += (
        f'Content-Disposition: form-data; name="file"; filename="{filename}"\r\n'
    ).encode()
    body += f"Content-Type: {content_type}\r\n\r\n".encode()
    body += blob
    body += b"\r\n"
    body += f"--{boundary}--\r\n".encode()
    return bytes(body), f"multipart/form-data; boundary={boundary}"


def _download_audio(target_url: str, td: str) -> Optional[str]:
    """Grab the audio track and transcode to 16 kHz mono mp3 (Whisper's native
    sample rate — anything richer just inflates the upload)."""
    cmd = [
        sys.executable,
        "-m",
        "yt_dlp",
        "-f",
        "bestaudio/best",
        "--extract-audio",
        "--audio-format",
        "mp3",
        "--postprocessor-args",
        "ffmpeg:-ar 16000 -ac 1 -b:a 32k",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--no-overwrites",
        "-o",
        os.path.join(td, "audio.%(ext)s"),
        target_url,
    ]
    cmd += _site_args(target_url)

    for attempt in range(1, YTDLP_RETRIES + 1):
        # Clear any partial download from a previous flaky attempt so the
        # --no-overwrites flag doesn't skip because of a broken fragment.
        for fname in os.listdir(td):
            try:
                os.remove(os.path.join(td, fname))
            except OSError:
                pass
        try:
            subprocess.run(
                cmd, cwd=td, capture_output=True, text=True, timeout=YTDLP_TIMEOUT
            )
        except subprocess.TimeoutExpired:
            return None
        for fname in sorted(os.listdir(td)):
            if fname.endswith(".mp3"):
                return os.path.join(td, fname)
    return None


def _groq_transcribe(path: str) -> dict:
    """Send one audio file to Groq Whisper and return the EchoLearn payload.

    The language is deliberately auto-detected rather than hinted: the point of
    ASR on Bilibili is the English-language content hosted there, and pinning
    the hint to zh would wreck exactly those videos.
    """
    with open(path, "rb") as fh:
        blob = fh.read()

    if len(blob) > GROQ_MAX_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"Audio is {len(blob) // 1024 // 1024} MB, over the 25 MB Groq limit",
        )

    body, content_type = _multipart(
        {"model": GROQ_MODEL, "response_format": "verbose_json"},
        "audio.mp3",
        blob,
        "audio/mpeg",
    )
    req = urllib.request.Request(
        GROQ_ENDPOINT,
        data=body,
        headers={
            "Authorization": f"Bearer {GROQ_API_KEY}",
            "Content-Type": content_type,
        },
        method="POST",
    )

    # Groq blocks many datacenter/VPS IP ranges with HTTP 403 (error 1010), so
    # route the call through the residential proxy when configured — the same
    # one yt-dlp uses for Bilibili. This is the standard fix for
    # "Groq HTTP 403: error code: 1010" originating from a cloud server.
    opener = (
        urllib.request.build_opener(
            urllib.request.ProxyHandler({"https": YTDLP_PROXY})
        )
        if YTDLP_PROXY
        else urllib.request.build_opener()
    )

    try:
        with opener.open(req, timeout=GROQ_TIMEOUT) as resp:
            raw = json.load(resp)
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "ignore")[:400]
        # Surface 429 as-is so callers can distinguish "out of quota" from
        # "this video simply cannot be transcribed".
        status = 429 if exc.code == 429 else 502
        raise HTTPException(status_code=status, detail=f"Groq HTTP {exc.code}: {detail}")
    except Exception as exc:  # noqa: BLE001 - network errors are all equivalent here
        raise HTTPException(status_code=502, detail=f"Groq request failed: {exc}")

    segments = raw.get("segments") or []
    lines = [
        {
            "id": f"yt_{i + 1}",
            "start": round(float(seg.get("start") or 0), 3),
            "end": round(float(seg.get("end") or 0), 3),
            "text": (seg.get("text") or "").strip(),
        }
        for i, seg in enumerate(segments)
        if (seg.get("text") or "").strip()
    ]

    if not lines:
        text = (raw.get("text") or "").strip()
        if not text:
            raise HTTPException(status_code=404, detail="Whisper returned no speech")
        lines = [{"id": "yt_1", "start": 0, "end": 0, "text": text}]

    return {
        "lines": lines,
        "language": raw.get("language") or "unknown",
        "isAutoGenerated": True,
        "source": "asr",
    }


# ── Routes ───────────────────────────────────────────────────────

@app.get("/api/transcript")
def transcript(
    video_id: Optional[str] = Query(default=None, alias="videoId"),
    url: Optional[str] = Query(default=None),
    lang: str = Query("en"),
    request: Request = None,
):
    target = url or video_id
    if not target:
        raise HTTPException(status_code=400, detail="Missing videoId or url")

    is_url = bool(url)
    if is_url:
        if not _host_allowed(url):
            raise HTTPException(status_code=400, detail="Unsupported url host")
    elif not _VIDEO_ID_RE.match(video_id or ""):
        raise HTTPException(status_code=400, detail="Invalid videoId")

    if YTDLP_API_KEY:
        provided = (request.headers.get("X-Api-Key") or "") if request else ""
        if provided != YTDLP_API_KEY:
            raise HTTPException(status_code=401, detail="Unauthorized")

    # Serve from cache (short TTL) to avoid re-hitting YouTube for the same
    # video+lang and to protect the single AWS IP from rate limits.
    cached = _cache_get(target, lang)
    if cached is not None:
        return JSONResponse(cached)

    result = _run_ytdlp(target, lang, is_url=is_url)
    if not result:
        raise HTTPException(
            status_code=404, detail="No transcript available for this video"
        )

    lines, language, is_auto = result
    payload = {
        "lines": lines,
        "language": language,
        "isAutoGenerated": bool(is_auto),
    }
    _cache_put(target, lang, payload)
    return JSONResponse(payload)


@app.get("/api/info")
def info(
    url: str = Query(...),
    request: Request = None,
):
    """Lightweight metadata lookup (title / uploader / duration).

    Exists mainly so the Cloudflare Worker doesn't have to call Bilibili
    directly — Bilibili answers Cloudflare Worker egress IPs with HTTP 412,
    while the VPS IP is fine.
    """
    if not _host_allowed(url):
        raise HTTPException(status_code=400, detail="Unsupported url host")

    if YTDLP_API_KEY:
        provided = (request.headers.get("X-Api-Key") or "") if request else ""
        if provided != YTDLP_API_KEY:
            raise HTTPException(status_code=401, detail="Unauthorized")

    return JSONResponse(_fetch_meta(url))


@app.get("/api/asr")
def asr(
    url: str = Query(...),
    request: Request = None,
):
    """Transcribe a video's audio with Whisper.

    This is the fallback for videos that expose no subtitle track at all — most
    notably Bilibili, which serves audio anonymously but hides subtitle tracks
    behind a login.
    """
    if not GROQ_API_KEY:
        raise HTTPException(status_code=503, detail="ASR not configured (no GROQ_API_KEY)")

    if not _host_allowed(url):
        raise HTTPException(status_code=400, detail="Unsupported url host")

    if YTDLP_API_KEY:
        provided = (request.headers.get("X-Api-Key") or "") if request else ""
        if provided != YTDLP_API_KEY:
            raise HTTPException(status_code=401, detail="Unauthorized")

    # ASR costs real quota, so a cache hit is worth much more here than on the
    # subtitle routes.
    cached = _cache_get(url, "__asr__")
    if cached is not None:
        return JSONResponse(cached)

    duration = int(_fetch_meta(url).get("duration") or 0)
    if duration > ASR_MAX_DURATION:
        raise HTTPException(
            status_code=413,
            detail=(
                f"Video is {duration // 60} min, over the "
                f"{ASR_MAX_DURATION // 60} min ASR limit"
            ),
        )

    with tempfile.TemporaryDirectory() as td:
        audio_path = _download_audio(url, td)
        if not audio_path:
            raise HTTPException(status_code=502, detail="Could not download audio")
        payload = _groq_transcribe(audio_path)

    _cache_put(url, "__asr__", payload)
    return JSONResponse(payload)


@app.get("/api/health")
def health():
    return {
        "status": "ok",
        "asr": bool(GROQ_API_KEY),
        "asrMaxDuration": ASR_MAX_DURATION,
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", "8000")))
