"""
EchoLearn — server-side YouTube transcript service (FastAPI + yt-dlp)

Runs on a small always-on VPS. yt-dlp does the heavy lifting: it rotates
YouTube client signatures (web / android / tv / ios) and the TVHTML5 client
bypasses YouTube's datacenter-IP bot check, so captions can be fetched
without a residential proxy for the vast majority of videos.

Endpoints
  GET /api/transcript?videoId=<id>&lang=<en>
  GET /api/transcript?url=<any yt-dlp supported url>&lang=<zh-CN>
  GET /api/asr?url=<any yt-dlp supported url>
  GET /api/audio?url=<any yt-dlp supported url>  (mp3 stream for audio-only mode)
  GET /api/info?url=<any yt-dlp supported url>
  GET /api/health

Response shape (matches the EchoLearn web/Worker contract):
  {
    "lines": [{"id": "yt_1", "start": 0.0, "end": 1.23, "text": "..."}, ...],
    "language": "en",
    "isAutoGenerated": false
  }

Environment
  YTDLP_TIMEOUT   subprocess hard timeout in seconds (default 90)
  YTDLP_PROXY     optional upstream proxy passed to yt-dlp (e.g. a residential
                  proxy endpoint). Now used ONLY as a fallback for YouTube when a
                  direct (no-proxy) extraction fails — the TVHTML5 client normally
                  bypasses YouTube's datacenter bot-check without it. Bilibili no
                  longer uses yt-dlp at all: its audio is pulled via the public
                  view + playurl APIs (which answer the VPS IP fine) and the media
                  CDN directly, so the proxy is never touched for Bilibili.
                  NOT used for Groq: Groq works directly from this VPS, and the
                  proxy only adds a flaky hop (Broken pipe).
  YTDLP_API_KEY   if set, /api/transcript and /api/asr require header X-Api-Key to match
  YTDLP_CACHE_TTL in-memory cache TTL in seconds for fetched transcripts (default 3600)
  YTDLP_COOKIES   optional path to a Netscape cookies.txt used for non-YouTube
                  sites. Bilibili only exposes subtitle tracks to logged-in
                  sessions, so a SESSDATA cookie is required there.
  YTDLP_RETRIES   number of yt-dlp subprocess attempts before giving up (default 5).
                  Useful when the residential proxy tunnel drops mid-transfer.
  GROQ_API_KEY    enables /api/asr (Whisper transcription via Groq)
  GROQ_MODEL      Groq speech model (default whisper-large-v3-turbo)
  ASR_MAX_DURATION  reject ASR requests longer than this many seconds (default 1800)

Note on the proxy: YTDLP_PROXY is now a YOUTUBE-ONLY fallback. Bilibili's
*watch page* returns HTTP 412 from both the VPS datacenter IP and the entire
residential-proxy IP pool, so the proxy can't help Bilibili — and Bilibili
doesn't need it anyway, because its JSON APIs (view/playurl) and media CDN are
reachable directly from the VPS. Bilibili audio/ASR/info therefore bypass yt-dlp
entirely and use zero proxy bandwidth. YouTube is tried with NO proxy first
(TVHTML5 client) and only falls back to the proxy if that fails.

Note on Bilibili transcripts: Bilibili gates *subtitle tracks* behind a login,
but audio streams are served to anonymous clients. With a SESSDATA cookie in
YTDLP_COOKIES, the transcript route can fetch the real (or auto) subtitle tracks
— this is the preferred, fast, free path. When that fails (no cookie, or a video
with no subtitle track), the caller falls back to ASR, which sidesteps the login
wall by transcribing the audio instead — no SESSDATA cookie needed for that.
"""

import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from collections import OrderedDict
from typing import Optional

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse

app = FastAPI(title="EchoLearn yt-dlp transcript service")

# Permissive CORS: this is a private service fronted by Cloudflare; the CF
# Worker calls it server-to-server (no Origin), but allow all origins so it
# can also be called directly during local testing.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "OPTIONS"],
    allow_headers=["*"],
)

YTDLP_TIMEOUT = int(os.environ.get("YTDLP_TIMEOUT", "180"))
YTDLP_PROXY = os.environ.get("YTDLP_PROXY") or ""
YTDLP_API_KEY = os.environ.get("YTDLP_API_KEY") or ""
YTDLP_CACHE_TTL = int(os.environ.get("YTDLP_CACHE_TTL", "3600"))  # seconds
YTDLP_COOKIES = os.environ.get("YTDLP_COOKIES") or ""
YTDLP_RETRIES = int(os.environ.get("YTDLP_RETRIES", "5"))  # yt-dlp subprocess attempts

# Audio-only extraction budgets. A single yt-dlp call can blow the Cloudflare
# Worker's ~180s window if the residential proxy is slow, so we cap the
# per-attempt subprocess timeout tightly and allow several attempts
# with exponential backoff. A rotating residential proxy hands each attempt a
# fresh egress IP, so a retry often completes where the previous dropped.
# Bilibili's metadata must go through that proxy (datacenter IPs get 412), and
# the proxy is flaky (500 / IncompleteRead), so we favour MORE attempts over a
# long single shot — failures are usually fast (seconds), so 4 attempts still
# fit comfortably under the Worker window.
AUDIO_DL_TIMEOUT = int(os.environ.get("YTDLP_AUDIO_TIMEOUT", "55"))   # hard cap per yt-dlp call
AUDIO_MAX_ATTEMPTS = int(os.environ.get("YTDLP_AUDIO_RETRIES", "4"))  # attempts (+ backoff)
# Hard wall-clock ceiling for the whole extraction (metadata + download loop).
# Kept comfortably under the Worker's 180s so the request never 502s purely
# because the VPS was still working — if we can't finish in time we return
# immediately and let the frontend auto-retry with a fresh proxy IP.
AUDIO_OVERALL_TIMEOUT = int(os.environ.get("YTDLP_AUDIO_OVERALL_TIMEOUT", "172"))

GROQ_API_KEY = os.environ.get("GROQ_API_KEY") or ""
GROQ_MODEL = os.environ.get("GROQ_MODEL", "whisper-large-v3-turbo")
GROQ_ENDPOINT = "https://api.groq.com/openai/v1/audio/transcriptions"
GROQ_TIMEOUT = int(os.environ.get("GROQ_TIMEOUT", "180"))
# Groq's free tier rejects files above 25 MB. At 16 kHz mono 32 kbps that is
# roughly 108 minutes of audio, so ASR_MAX_DURATION is the binding limit.
GROQ_MAX_BYTES = 25 * 1024 * 1024
ASR_MAX_DURATION = int(os.environ.get("ASR_MAX_DURATION", "1800"))  # 30 min

_VIDEO_ID_RE = re.compile(r"^[a-zA-Z0-9_-]{6,15}$")
_ALLOWED_HOSTS = ("youtube.com", "youtu.be", "bilibili.com", "b23.tv")

# Opener that NEVER consults a proxy — used for all Bilibili API + CDN traffic
# so the residential proxy (which Bilibili blocks wholesale) can never be
# slipped in via a parent env var. The VPS datacenter IP reaches these hosts
# directly and far faster than through the proxy.
_NO_PROXY_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))
_BILI_VIEW_CACHE = {}
_BILI_VIEW_CACHE_TTL = 60


def _urlopen_no_proxy(req, timeout: int = 10):
    return _NO_PROXY_OPENER.open(req, timeout=timeout)

# Persistent on-disk cache for extracted audio (audio-only player). Keyed by a
# hash of the target URL + part so repeat plays are served instantly without
# re-downloading. The Cloudflare Worker streams these files to the browser.
AUDIO_CACHE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "audio_cache")
os.makedirs(AUDIO_CACHE_DIR, exist_ok=True)


def _is_youtube(target_url: str) -> bool:
    return "youtube.com" in target_url or "youtu.be" in target_url


def _is_bilibili(target_url: str) -> bool:
    return "bilibili.com" in target_url or "b23.tv" in target_url


def _is_english(language: Optional[str]) -> bool:
    """Whether a subtitle language code denotes English (incl. Bilibili 'ai-en')."""
    l = (language or "").lower()
    return l in ("en", "ai-en") or l.startswith("en")


def _lang_rank(language: Optional[str]) -> int:
    """Sort rank for subtitle language: English first, then Chinese, then rest."""
    l = (language or "").lower()
    if l in ("en", "ai-en") or l.startswith("en"):
        return 0
    if l.startswith("zh") or l == "ai-zh":
        return 1
    return 2


def _extract_bvid(target_url: str):
    """Pull the BV id out of a Bilibili URL (or return None).

    Bilibili BV ids are case-sensitive after the ``BV`` prefix. Match the
    prefix case-insensitively, but preserve every character in the payload;
    uppercasing the whole id turns e.g. ``BV1emBiYcEAV`` into a different id.
    """
    m = re.search(r"(BV[0-9A-Za-z]+)", target_url, re.IGNORECASE)
    return ("BV" + m.group(1)[2:]) if m else None


def _clean_bvid(raw_id: str | None):
    """Strip yt-dlp's playlist `_pN` suffix from a Bilibili id.

    When a b23.tv short link points at a specific part of a multi-part video,
    yt-dlp reports the id as e.g. `BV1xx_p1`. The player iframe and the Bilibili
    view API need the base id (`BV1xx`), so strip the suffix and report the part
    separately. Returns (base_bvid, part_or_None).
    """
    if not raw_id:
        return None, None
    m = re.match(r"^(BV[0-9A-Za-z]+)_p(\d+)$", raw_id)
    if m:
        return m.group(1), int(m.group(2))
    return raw_id, None


def _bilibili_parts(bvid: str):
    """Return the part list for a Bilibili video via its public view API.

    The view API (api.bilibili.com/x/web-interface/view) answers the VPS
    datacenter IP fine — only the *watch page* returns HTTP 412 — so no
    proxy is needed. Returns {"partCount": N, "parts": [{"index", "title"}]}
    or None on any failure (the caller then simply skips the part picker).
    """
    api = f"https://api.bilibili.com/x/web-interface/view?bvid={bvid}"
    req = urllib.request.Request(
        api,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            ),
            "Referer": "https://www.bilibili.com/",
        },
    )
    try:
        with _urlopen_no_proxy(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8", "ignore"))
    except Exception:
        return None
    if data.get("code") != 0:
        return None
    pages = (data.get("data") or {}).get("pages") or []
    parts = [{"index": p.get("page"), "title": p.get("part") or ""} for p in pages]
    return {"partCount": len(parts), "parts": parts}


# ── Bilibili API-direct extraction (no proxy, no yt-dlp watch-page 412) ──
#
# Bilibili's JSON APIs (view + playurl) answer the VPS datacenter IP fine,
# and the media CDN (bilivideo.com) serves anonymous clients directly. The
# only thing that 412s from a datacenter IP is the *watch page* HTML, which
# yt-dlp's extractor hits — so we bypass yt-dlp entirely for Bilibili and
# pull the audio straight from the DASH manifest. This also means the
# residential proxy (which Bilibili blocks wholesale anyway) is never used
# for Bilibili, saving both latency and Proxy-Cheap bandwidth.

_BILI_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
_BILI_REFERER = "https://www.bilibili.com/"


def _resolve_bilibili_url(url: str) -> str:
    """Follow b23.tv short links to the canonical bilibili.com URL."""
    if "b23.tv" not in url:
        return url
    headers = {"User-Agent": _BILI_UA, "Referer": _BILI_REFERER}
    req = urllib.request.Request(url, headers=headers)
    try:
        with _urlopen_no_proxy(req, timeout=10) as resp:
            return resp.geturl()
    except Exception:
        # b23.tv is a webpage redirect and can return 412 to datacenter IPs,
        # even though api.bilibili.com and the media CDN remain public. Use
        # the configured residential proxy only for this redirect step; all
        # subsequent view/playurl/API and CDN requests stay direct.
        if not YTDLP_PROXY:
            return url
        try:
            proxy = urllib.request.ProxyHandler({"http": YTDLP_PROXY, "https": YTDLP_PROXY})
            class _NoRedirect(urllib.request.HTTPRedirectHandler):
                def redirect_request(self, req, fp, code, msg, headers, new):
                    return None
            opener = urllib.request.build_opener(proxy, _NoRedirect())
            try:
                with opener.open(req, timeout=20) as resp:
                    location = resp.headers.get("Location")
            except urllib.error.HTTPError as exc:
                location = exc.headers.get("Location")
            if location:
                return urllib.parse.urljoin(url, location)
        except Exception:
            pass
        # Some HTTPS proxies fail when urllib follows the redirect, but still
        # return the Location header. Ask curl for headers only as a final
        # redirect-resolution fallback and never follow the destination page.
        try:
            proc = subprocess.run(
                ["curl", "-sS", "-I", "--max-redirs", "0", "--proxy", YTDLP_PROXY,
                 "-A", _BILI_UA, url],
                capture_output=True, text=True, timeout=20,
            )
            for line in proc.stdout.splitlines():
                if line.lower().startswith("location:"):
                    return urllib.parse.urljoin(url, line.split(":", 1)[1].strip())
        except Exception:
            pass
        return url


def _bilibili_view(bvid: str):
    """Full view-API payload: title, owner, duration, and per-part cids."""
    cached = _BILI_VIEW_CACHE.get(bvid)
    if cached and cached[0] > time.time():
        return cached[1]
    api = f"https://api.bilibili.com/x/web-interface/view?bvid={bvid}"
    headers = {
        "User-Agent": _BILI_UA,
        "Referer": _BILI_REFERER,
        "Origin": "https://www.bilibili.com",
        "Accept": "application/json, text/plain, */*",
    }
    # The API is normally reliable from the VPS, but occasional upstream
    # connection resets/empty responses were causing the whole ASR request to
    # fail before audio extraction. Retry the cheap metadata call briefly.
    for attempt in range(3):
        req = urllib.request.Request(api, headers=headers)
        try:
            with _urlopen_no_proxy(req, timeout=15) as resp:
                data = json.loads(resp.read().decode("utf-8", "ignore"))
            if data.get("code") == 0:
                d = data.get("data") or {}
                pages = [
                    {"index": p.get("page"), "cid": p.get("cid"),
                     "title": p.get("part") or "", "duration": p.get("duration") or 0}
                    for p in (d.get("pages") or [])
                ]
                result = {
                    "title": d.get("title") or "",
                    "owner": (d.get("owner") or {}).get("name") or "",
                    "duration": d.get("duration") or 0,
                    "pages": pages,
                }
                _BILI_VIEW_CACHE[bvid] = (time.time() + _BILI_VIEW_CACHE_TTL, result)
                return result
        except Exception:
            pass
        if attempt < 2:
            time.sleep(0.75 * (attempt + 1))
    return None


def _bilibili_play_parse(data):
    """Extract a usable audio baseUrl from a playurl API response, or None."""
    if not isinstance(data, dict) or data.get("code") != 0:
        return None
    payload = data.get("data")
    # Legacy shape: data is a list of durl entries (muxed FLV/MP4 with audio).
    # The playurl API returns this intermittently (e.g. on some CDN nodes).
    if isinstance(payload, list):
        if not payload:
            return None
        return payload[0].get("url") or payload[0] if isinstance(payload[0], str) else payload[0].get("baseUrl")
    dash = (payload or {}).get("dash") or {}
    audios = dash.get("audio") or []
    if audios:
        audios.sort(key=lambda a: a.get("bandwidth") or 0, reverse=True)
        return audios[0].get("baseUrl")
    # Fallback: some playurl responses omit the DASH audio track but still
    # return a muxed stream via `durl`. That carries audio, fine for ASR.
    durl = (payload or {}).get("durl") or []
    if durl:
        return durl[0].get("url") or durl[0].get("baseUrl")
    return None


def _bilibili_playurl(bvid: str, cid: int):
    """Best audio baseUrl for a (bvid, cid), or None.

    Retries once because the playurl API occasionally returns a malformed /
    audio-less payload on the first hit (CDN-node dependent).
    """
    api = (
        f"https://api.bilibili.com/x/player/playurl?bvid={bvid}"
        f"&cid={cid}&qn=64&fnval=16&fourk=1"
    )
    req = urllib.request.Request(
        api, headers={"User-Agent": _BILI_UA, "Referer": _BILI_REFERER}
    )
    last = None
    for _ in range(2):
        try:
            with _urlopen_no_proxy(req, timeout=10) as resp:
                last = json.loads(resp.read().decode("utf-8", "ignore"))
        except Exception:
            last = None
        url = _bilibili_play_parse(last)
        if url:
            return url
    return None


def _bilibili_cid_for_part(view, part: Optional[int]):
    """Return the cid for the requested part (1-indexed), defaulting to part 1."""
    pages = (view or {}).get("pages") or []
    if not pages:
        return None
    if part and part > 1:
        for p in pages:
            if p.get("index") == part:
                return p.get("cid")
    return pages[0].get("cid")


def _download_bilibili_audio(base_url: str, out_path: str, ar: int = 16000, ab: int = 32) -> bool:
    """Download a Bilibili DASH audio URL (CDN, no proxy) and transcode to mp3.

    `ar`/`ab` select the Whisper-friendly 16 kHz/32 kbps profile for ASR, or a
    listenable 44.1 kHz/64 kbps profile for the audio player.
    """
    raw = out_path + ".raw"
    req = urllib.request.Request(
        base_url, headers={"User-Agent": _BILI_UA, "Referer": _BILI_REFERER}
    )
    try:
        with _urlopen_no_proxy(req, timeout=90) as resp, open(raw, "wb") as fh:
            while True:
                chunk = resp.read(1 << 16)
                if not chunk:
                    break
                fh.write(chunk)
    except Exception:
        try:
            os.remove(raw)
        except OSError:
            pass
        return False
    try:
        subprocess.run(
            ["ffmpeg", "-y", "-i", raw, "-ar", str(ar), "-ac", "1",
             "-b:a", f"{ab}k", out_path],
            capture_output=True, text=True, timeout=120,
        )
    except Exception:
        pass
    finally:
        try:
            os.remove(raw)
        except OSError:
            pass
    return os.path.exists(out_path) and os.path.getsize(out_path) > 0


def _bilibili_asr(url: str, part: Optional[int] = None) -> dict:
    """Full ASR pipeline for a Bilibili video via the public APIs (no proxy)."""
    resolved = _resolve_bilibili_url(url)
    bvid = _extract_bvid(resolved)
    if not bvid:
        raise HTTPException(status_code=400, detail="Could not parse Bilibili id")
    view = _bilibili_view(bvid)
    if not view:
        raise HTTPException(status_code=404, detail="Bilibili view API failed")
    cid = _bilibili_cid_for_part(view, part)
    if not cid:
        raise HTTPException(status_code=404, detail="Bilibili part not found")
    base_url = _bilibili_playurl(bvid, cid)
    if not base_url:
        raise HTTPException(status_code=404, detail="Bilibili playurl API failed")
    with tempfile.TemporaryDirectory() as td:
        mp3 = os.path.join(td, "audio.mp3")
        if not _download_bilibili_audio(base_url, mp3, ar=16000, ab=32):
            raise HTTPException(status_code=502, detail="Could not download Bilibili audio")
        return _groq_transcribe(mp3)


def _bilibili_audio(url: str, part: Optional[int], out_path: str) -> bool:
    """Fetch + transcode a listenable Bilibili audio track into out_path."""
    resolved = _resolve_bilibili_url(url)
    bvid = _extract_bvid(resolved)
    if not bvid:
        return False
    view = _bilibili_view(bvid)
    if not view:
        return False
    cid = _bilibili_cid_for_part(view, part)
    if not cid:
        return False
    base_url = _bilibili_playurl(bvid, cid)
    if not base_url:
        return False
    return _download_bilibili_audio(base_url, out_path, ar=44100, ab=64)


def _host_allowed(target_url: str) -> bool:
    """Only let known hosts through so the endpoint can't be used as an
    open yt-dlp relay for arbitrary sites."""
    if not target_url.startswith(("http://", "https://")):
        return False
    return any(h in target_url for h in _ALLOWED_HOSTS)


def _site_args(target_url: str) -> list:
    """Per-site yt-dlp flags.

    - The residential proxy is applied via *environment variables* (see
      `_proxy_env`), NOT the `--proxy` CLI flag. Doing it in the env lets us set
      NO_PROXY so Bilibili's media CDN (bilivideo.com / akamaized.net) is reached
      directly from the datacenter IP while the watch page still rides the proxy
      (it returns 412 otherwise). Downloading the multi-MB audio straight from
      the CDN is ~17x faster and far less prone to the proxy dropping mid-transfer
      — this is "Plan C".
    - Cookies (YTDLP_COOKIES, e.g. a Bilibili SESSDATA jar) are applied whenever
      the file exists. Bilibili only exposes subtitle tracks to logged-in
      sessions, so the cookie is what unlocks real subtitles there — without it
      the transcript route falls through to ASR.
    """
    args: list = []
    if YTDLP_COOKIES and os.path.exists(YTDLP_COOKIES):
        args += ["--cookies", YTDLP_COOKIES]
    return args


def _cookie_args(target_url: str) -> list:
    """Like _site_args but cookies only — no proxy.

    Used as a fallback when the residential proxy tunnel is down: with a valid
    YouTube account cookie in YTDLP_COOKIES plus the --remote-components n-solver,
    yt-dlp can fetch captions directly from the datacenter IP without the proxy.
    """
    args: list = []
    if YTDLP_COOKIES and os.path.exists(YTDLP_COOKIES):
        args += ["--cookies", YTDLP_COOKIES]
    return args


# Bilibili media CDNs that serve fine from the datacenter IP without the
# residential proxy. Routing these direct (instead of through the flaky proxy)
# is the core of Plan C: the watch page still needs the proxy (412 otherwise)
# but the multi-MB audio/video download no longer rides the proxy that tends to
# drop large transfers.
_BILI_MEDIA_NO_PROXY = "bilivideo.com,akamaized.net,mcdn.bilivideo.cn"


def _proxy_env(target_url: str) -> dict:
    """Build a subprocess env that routes yt-dlp through the residential proxy
    for YouTube and Bilibili, but sends Bilibili's media CDN traffic direct.

    We set the proxy via environment variables (not the ``--proxy`` CLI flag) so
    that NO_PROXY can carve out the Bilibili media hosts. yt-dlp honours NO_PROXY
    for its urllib-based downloads, so the large audio transfer goes straight to
    the CDN — ~17x faster and far more reliable than the proxy.
    """
    env = dict(os.environ)
    if YTDLP_PROXY and (_is_youtube(target_url) or _is_bilibili(target_url)):
        for k in ("HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY",
                  "http_proxy", "https_proxy", "all_proxy"):
            env[k] = YTDLP_PROXY
        if _is_bilibili(target_url):
            # Watch page + playurl API still use the proxy; only the media CDN
            # (bilivideo.com / akamaized.net) is reached directly.
            for k in ("NO_PROXY", "no_proxy"):
                env[k] = _BILI_MEDIA_NO_PROXY
        else:
            # YouTube: keep everything on the proxy (it's what unblocks it).
            env.pop("NO_PROXY", None)
            env.pop("no_proxy", None)
    else:
        # No proxy wanted — make sure none leaks from the parent env.
        for k in ("HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY",
                  "http_proxy", "https_proxy", "all_proxy",
                  "NO_PROXY", "no_proxy"):
            env.pop(k, None)
    return env


def _no_proxy_env() -> dict:
    """Subprocess env with the proxy fully removed — used by the YouTube cookie
    fallback that fetches captions straight from the datacenter IP."""
    env = dict(os.environ)
    for k in ("HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY",
              "http_proxy", "https_proxy", "all_proxy",
              "NO_PROXY", "no_proxy"):
        env.pop(k, None)
    return env


def _has_youtube_cookies() -> bool:
    """True if the cookie jar contains a YouTube session (so the no-proxy
    fallback is worth attempting)."""
    if not (YTDLP_COOKIES and os.path.exists(YTDLP_COOKIES)):
        return False
    try:
        with open(YTDLP_COOKIES, encoding="utf-8") as fh:
            return any(".youtube.com" in line for line in fh)
    except OSError:
        return False

# ── In-memory TTL cache (keyed by video_id:lang) ──────────────
# Protects the single VPS IP from repeat YouTube hits on popular videos and
# speeds up repeated fetches of the same video+lang. Only successful results
# are cached; failures are always retried.
_CACHE: "OrderedDict[str, tuple[float, dict]]" = OrderedDict()
_CACHE_MAX = 2000


def _cache_get(video_id: str, lang: str):
    key = f"{video_id}:{lang}"
    item = _CACHE.get(key)
    if item is None:
        return None
    expiry, payload = item
    if expiry < time.time():
        _CACHE.pop(key, None)
        return None
    _CACHE.move_to_end(key)  # LRU touch
    return payload


def _cache_put(video_id: str, lang: str, payload: dict):
    key = f"{video_id}:{lang}"
    _CACHE[key] = (time.time() + YTDLP_CACHE_TTL, payload)
    _CACHE.move_to_end(key)
    if len(_CACHE) > _CACHE_MAX:
        _CACHE.popitem(last=False)  # evict oldest


# ── Parsers ───────────────────────────────────────────────────────

def _parse_json3(raw: dict) -> list:
    events = raw.get("events", []) if isinstance(raw, dict) else []
    lines = []
    idx = 0
    for ev in events:
        segs = ev.get("segs") or []
        text = "".join(s.get("utf8", "") for s in segs).strip()
        if not text:
            continue
        start = (ev.get("tStartMs") or 0) / 1000.0
        dur = ev.get("dDurationMs") or 0
        lines.append(
            {
                "id": f"yt_{idx + 1}",
                "start": round(start, 3),
                "end": round(start + dur / 1000.0, 3),
                "text": text,
            }
        )
        idx += 1
    return lines


def _parse_vtt(text: str) -> list:
    # Parse every cue (timestamp line + text) into a raw record. We keep the
    # RAW text so we can later detect YouTube's auto-caption (ASR) overlap format.
    cues = []
    idx = 0
    cue_re = re.compile(
        r"(\d{1,2}:)?\d{1,2}:\d{2}\.\d{1,3}\s*-->\s*(\d{1,2}:)?\d{1,2}:\d{2}\.\d{1,3}"
    )
    ts_matches = list(cue_re.finditer(text))
    for i, m in enumerate(ts_matches):
        start = _vtt_time_to_sec(m.group(0).split("-->")[0].strip())
        end = _vtt_time_to_sec(m.group(0).split("-->")[1].strip())
        # The cue body runs from the end of this timestamp *line* to the start of
        # the next one. Grouping this way is robust to the blank line YouTube
        # sometimes inserts between a timestamp and its text (which a naive
        # blank-line split would otherwise orphan into a timestamp-less block).
        # We skip to after the newline so trailing timestamp params such as
        # "align:start position:0%" are not treated as caption text.
        nl = text.find("\n", m.end())
        body_start = nl + 1 if nl != -1 else len(text)
        body_end = ts_matches[i + 1].start() if i + 1 < len(ts_matches) else len(text)
        raw = text[body_start:body_end]
        # ASR cues carry per-word timing tags like <00:00:00.880> or <c>word</c>.
        had_inline = bool(re.search(r"<\d\d:\d\d|<\s*c[ >]", raw))
        cues.append(
            {"start": round(start, 3), "end": round(end, 3), "raw": raw, "had_inline": had_inline}
        )

    if not cues:
        return []

    # YouTube auto-captions (ASR) emit a "growing window" of text per word-timed
    # cue (each window is a super-set of the previous one) followed by a ~0.01s
    # "echo" cue that repeats the just-finalised line. Keeping every cue therefore
    # produces heavily overlapping / duplicated transcript lines. Collapse them into
    # clean, non-overlapping lines by retaining only the *new* text introduced at
    # each window transition. Manually-written captions have no inline tags, so they
    # fall through to the simple one-cue-per-line path below.
    # ASR_COLLAPSE_V1
    asr = any(c["had_inline"] for c in cues)
    if not asr:
        out = []
        for c in cues:
            t = re.sub(r"<[^>]+>", "", c["raw"]).strip()
            if not t:
                continue
            out.append({"id": f"yt_{idx + 1}", "start": c["start"], "end": c["end"], "text": t})
            idx += 1
        return out

    cues.sort(key=lambda c: c["start"])
    out = []
    consumed = ""
    for c in cues:
        t = re.sub(r"<[^>]+>", "", c["raw"]).strip()
        if not t:
            continue
        if t.startswith(consumed):
            new = t[len(consumed):].strip()
        else:
            # Strip the longest prefix of t that matches a suffix of what we have
            # already absorbed (handles sentence resets / overlapping windows).
            new = t
            for k in range(min(len(t), len(consumed)), 0, -1):
                if consumed.endswith(t[:k]):
                    new = t[k:].strip()
                    break
        if new:
            out.append({"id": f"yt_{idx + 1}", "start": c["start"], "end": c["end"], "text": new})
            idx += 1
            consumed = t
    return out


def _vtt_time_to_sec(s: str) -> float:
    s = s.strip()
    # Formats: HH:MM:SS.mmm or MM:SS.mmm
    parts = s.split(":")
    parts = [float(p) for p in parts]
    if len(parts) == 3:
        h, m, sec = parts
    else:
        h, m, sec = 0, parts[0], parts[1]
    return h * 3600 + m * 60 + sec


def _read_subtitle_file(td: str):
    """Return (lines, language, is_auto) for the best usable subtitle file.

    Hand-written subtitles are preferred over auto-generated ones; this matters
    most for Bilibili, where real tracks (when present) are far cleaner than the
    auto captions.
    """
    parsed = []
    # The subtitle filename is yt-dlp's %(id)s template, which for Bilibili is the
    # BV id. Capture it so the app can wire up the player/title for videos reached
    # via a b23.tv short link (where the client only has the short code).
    bvid = None
    for fname in sorted(os.listdir(td)):
        path = os.path.join(td, fname)
        if fname.endswith(".json3"):
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    raw = json.load(fh)
            except Exception:
                continue
            lines = _parse_json3(raw)
        elif fname.endswith(".vtt"):
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    raw = fh.read()
            except Exception:
                continue
            lines = _parse_vtt(raw)
        else:
            continue
        if not lines:
            continue
        if bvid is None:
            m_id = re.match(r"^(BV[0-9A-Za-z]+)\.", fname)
            if m_id:
                bvid, _ = _clean_bvid(m_id.group(1))
        m = re.search(r"\.([a-zA-Z]{2}(?:-[A-Za-z]+)?(?:-orig)?)\.(?:json3|vtt)$", fname)
        language = m.group(1) if m else "en"
        is_auto = "auto" in fname or "-orig" in fname
        parsed.append((is_auto, language, lines))
    if not parsed:
        return None
    # Real (False) sorts before auto (True), and within each group we prefer an
    # English track so the English-learning transcript is used whenever one
    # exists (covers Bilibili "ai-en" as well as standard "en"/"en-US").
    def sort_key(c):
        is_auto, language, _ = c
        return (is_auto, _lang_rank(language))

    parsed.sort(key=sort_key)
    is_auto, language, lines = parsed[0]
    return lines, language, is_auto, bvid


# ── yt-dlp invocation ────────────────────────────────────────────

# Bilibili tracking/query params that should not affect cache keys or yt-dlp extraction.
_BILI_NOISE_PARAMS = {
    "spm_id_from",
    "from_source",
    "from_spmid",
    "vd_source",
    "seid",
    "bvid",  # already in path; harmless but keeps URL tidy
}


def _normalize_bilibili_url(raw_url: str) -> str:
    """Strip Bilibili share/tracking params and trivial path variants so the same video shares a cache key."""
    parsed = urllib.parse.urlparse(raw_url)
    if parsed.netloc and "bilibili" not in parsed.netloc.lower():
        return raw_url
    # Force canonical scheme/host, keep www. for consistency with URLs the app
    # reconstructs, and remove a trailing slash from the path (e.g. /video/BVxx/
    # vs /video/BVxx normalize to the same key).
    netloc = parsed.netloc.lower()
    # Canonicalize any bilibili.com subdomain (m.bilibili.com, etc.) to www.
    if netloc.endswith(".bilibili.com") or netloc == "bilibili.com":
        netloc = "www.bilibili.com"
    path = parsed.path
    if path.endswith("/") and len(path) > 1:
        path = path[:-1]
    qs = urllib.parse.parse_qs(parsed.query)
    kept = {k: v for k, v in qs.items() if k not in _BILI_NOISE_PARAMS}
    new_qs = urllib.parse.urlencode(kept, doseq=True)
    parsed = parsed._replace(scheme="https", netloc=netloc, path=path, query=new_qs)
    return urllib.parse.urlunparse(parsed)


def _extract_part(raw_url: str):
    """Pull a Bilibili `?p=N` part selector out of a URL.

    Returns (clean_url, part) where clean_url has the selector stripped and
    part is an int (>1) or None. yt-dlp then selects the part via
    --playlist-items rather than the URL param, which is unambiguous.
    Tracking params are also stripped so share URLs with different UTM-like
    parameters hit the same cache entry.
    """
    raw_url = _normalize_bilibili_url(raw_url)
    parsed = urllib.parse.urlparse(raw_url)
    qs = urllib.parse.parse_qs(parsed.query)
    part = None
    if "p" in qs:
        try:
            part = int(qs["p"][0])
        except (ValueError, IndexError):
            part = None
        kept = {k: v for k, v in qs.items() if k != "p"}
        new_qs = urllib.parse.urlencode(kept, doseq=True)
        parsed = parsed._replace(query=new_qs)
        raw_url = urllib.parse.urlunparse(parsed)
    return raw_url, (part if part and part > 1 else None)


def _playlist_flag(part: Optional[int]) -> list:
    """yt-dlp flag selecting a specific playlist entry, or opting out."""
    if part and part > 1:
        return ["--playlist-items", str(part)]
    return ["--no-playlist"]


def _run_ytdlp(video_id_or_url: str, lang: str, *, is_url: bool = False, part: Optional[int] = None):
    target_url = video_id_or_url if is_url else f"https://www.youtube.com/watch?v={video_id_or_url}"
    sub_langs = "en,ai-en,zh-CN,ai-zh,en.*,zh.*,ai.*"  # ECHOLEARN_BILI_SUB_LANGS
    base_cmd = [
        sys.executable,
        "-m",
        "yt_dlp",
        "--js-runtimes",
        "node",
        "--remote-components",
        "ejs:github",
        "--skip-download",
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs",
        sub_langs,
        "--sub-format",
        "vtt",
        "--quiet",
        "--no-warnings",
        *_playlist_flag(part),
        "--no-overwrites",
        target_url,
    ]
    # Bilibili: yt-dlp's watch-page extractor 412s from datacenter IPs AND from
    # the proxy pool, so the proxy is useless there — run without it. (The
    # /api/asr and /api/audio routes bypass yt-dlp for Bilibili entirely via the
    # public APIs; this path only matters if a real subtitle track exists.)
    # YouTube: the TVHTML5 client bypasses the datacenter bot-check, so try NO
    # proxy first (fast, free) and only fall back to the proxy if that fails.
    if _is_bilibili(target_url):
        cmds = [(base_cmd + _site_args(target_url), _no_proxy_env())]
    else:
        cmds = [(base_cmd + _site_args(target_url), _no_proxy_env())]
        if YTDLP_PROXY:
            cmds.append((base_cmd + _site_args(target_url), _proxy_env(target_url)))
    for cmd, env in cmds:
        with tempfile.TemporaryDirectory() as td:
            full = cmd + ["-o", os.path.join(td, "%(id)s")]
            try:
                subprocess.run(
                    full,
                    cwd=td,
                    capture_output=True,
                    text=True,
                    timeout=YTDLP_TIMEOUT,
                    env=env,
                )
            except subprocess.TimeoutExpired:
                continue
            result = _read_subtitle_file(td)
            if result:
                return result
    return None


def _fetch_meta(target_url: str, part: Optional[int] = None, *, attempts: int = None, timeout: int = None) -> dict:
    """Title / uploader / duration / thumbnail via `yt-dlp -J`, memoised.

    `attempts` / `timeout` override the global YTDLP_RETRIES / YTDLP_TIMEOUT so
    callers with a tight deadline (e.g. the audio player, which must beat the
    Worker's 180s window) can fail the metadata lookup faster instead of
    burning the whole budget on a flaky proxy.
    """
    cached = _cache_get(target_url, "__info__")
    if cached is not None:
        return cached

    # Bilibili: skip yt-dlp (watch-page 412) and use the view API directly.
    if _is_bilibili(target_url):
        resolved = _resolve_bilibili_url(target_url)
        bvid = _extract_bvid(resolved)
        view = _bilibili_view(bvid) if bvid else None
        if not view:
            raise HTTPException(status_code=404, detail="Could not fetch Bilibili info")
        # A multi-part video reports the TOTAL duration in view["duration"]; for
        # the ASR/audio limit check and the player we want the selected part's
        # duration, which lives on the per-page record. Default to part 1 when no
        # explicit ?p= selector is present.
        sel = part if part else 1
        part_dur = None
        for p in view.get("pages") or []:
            if p.get("index") == sel and p.get("duration"):
                part_dur = p["duration"]
                break
        if not part_dur:
            part_dur = view["duration"]
        payload = {
            "title": view["title"],
            "ownerName": view["owner"],
            "duration": part_dur,
            "thumbnail": "",
            "bvid": bvid,
        }
        parts = _bilibili_parts(bvid) if bvid else None
        if parts:
            payload["partCount"] = parts["partCount"]
            payload["parts"] = parts["parts"]
        _cache_put(target_url, "__info__", payload)
        return payload

    attempts = attempts or YTDLP_RETRIES
    timeout = timeout or YTDLP_TIMEOUT

    cmd = [
        sys.executable,
        "-m",
        "yt_dlp",
        "--js-runtimes",
        "node",
        "--remote-components",
        "ejs:github",
        "--skip-download",
        "--dump-single-json",
        *_playlist_flag(part),
        "--quiet",
        "--no-warnings",
        target_url,
    ]
    cmd += _site_args(target_url)

    # The residential proxy is flaky for large Bilibili watch pages (tunnel
    # drops with IncompleteRead). A fresh process often lands on a stable IP.
    proc = None
    last_err = ""
    for attempt in range(1, attempts + 1):
        try:
            proc = subprocess.run(
                cmd, capture_output=True, text=True, timeout=timeout,
                env=_proxy_env(target_url),
            )
        except subprocess.TimeoutExpired:
            raise HTTPException(status_code=504, detail="Metadata lookup timed out")
        if proc.returncode == 0 and proc.stdout.strip():
            break
        last_err = proc.stderr.strip().splitlines()[-1] if proc.stderr else ""
        if attempt == attempts:
            detail = "Could not fetch video info"
            if last_err:
                detail += f" ({last_err})"
            raise HTTPException(status_code=404, detail=detail)

    if proc is None or proc.returncode != 0 or not proc.stdout.strip():
        raise HTTPException(status_code=404, detail="Could not fetch video info")

    try:
        meta = json.loads(proc.stdout)
    except json.JSONDecodeError:
        raise HTTPException(status_code=502, detail="Malformed metadata")

    payload = {
        "title": meta.get("title") or "",
        "ownerName": meta.get("uploader") or meta.get("channel") or "",
        "duration": meta.get("duration") or 0,
        "thumbnail": meta.get("thumbnail") or "",
        "bvid": _clean_bvid(meta.get("id"))[0] or "",
    }
    _cache_put(target_url, "__info__", payload)
    return payload


# ── Whisper ASR via Groq ─────────────────────────────────────────

def _multipart(fields: dict, filename: str, blob: bytes, content_type: str):
    """Minimal multipart/form-data encoder.

    Hand-rolled so the service keeps its three-package dependency list and can
    be redeployed by copying a single file — no pip install on the VPS.
    """
    boundary = "----EchoLearn" + uuid.uuid4().hex
    body = bytearray()
    for key, value in fields.items():
        body += f"--{boundary}\r\n".encode()
        body += f'Content-Disposition: form-data; name="{key}"\r\n\r\n'.encode()
        body += f"{value}\r\n".encode()
    body += f"--{boundary}\r\n".encode()
    body += (
        f'Content-Disposition: form-data; name="file"; filename="{filename}"\r\n'
    ).encode()
    body += f"Content-Type: {content_type}\r\n\r\n".encode()
    body += blob
    body += b"\r\n"
    body += f"--{boundary}--\r\n".encode()
    return bytes(body), f"multipart/form-data; boundary={boundary}"


def _download_audio(target_url: str, td: str, part: Optional[int] = None) -> Optional[str]:
    """Grab the audio track and transcode to 16 kHz mono mp3 (Whisper's native
    sample rate — anything richer just inflates the upload)."""
    cmd = [
        sys.executable,
        "-m",
        "yt_dlp",
        "--js-runtimes",
        "node",
        "--remote-components",
        "ejs:github",
        "-f",
        "bestaudio/best",
        "--extract-audio",
        "--audio-format",
        "mp3",
        "--postprocessor-args",
        "ffmpeg:-ar 16000 -ac 1 -b:a 32k",
        "--retries",
        "3",
        "--fragment-retries",
        "3",
        *_playlist_flag(part),
        "--quiet",
        "--no-warnings",
        "--no-overwrites",
        "-o",
        os.path.join(td, "audio.%(ext)s"),
        target_url,
    ]
    cmd += _site_args(target_url)
    # YouTube: try NO proxy first (TVHTML5 bypasses the datacenter bot-check),
    # then fall back to the residential proxy only if the direct attempt fails.
    envs = [_no_proxy_env()]
    if YTDLP_PROXY and _is_youtube(target_url):
        envs.append(_proxy_env(target_url))

    for env in envs:
        for attempt in range(1, YTDLP_RETRIES + 1):
            # Clear any partial download from a previous flaky attempt so the
            # --no-overwrites flag doesn't skip because of a broken fragment.
            for fname in os.listdir(td):
                try:
                    os.remove(os.path.join(td, fname))
                except OSError:
                    pass
            try:
                subprocess.run(
                    cmd, cwd=td, capture_output=True, text=True,
                    timeout=YTDLP_TIMEOUT, env=env,
                )
            except subprocess.TimeoutExpired:
                return None
            for fname in sorted(os.listdir(td)):
                if fname.endswith(".mp3"):
                    return os.path.join(td, fname)
    return None


def _audio_cache_path(target_url: str, part: Optional[int]) -> str:
    """Stable cache filename for a (url, part) pair.

    Bilibili share URLs often carry tracking params (spm_id_from, vd_source,
    etc.) that would otherwise fragment the cache. Normalize before hashing.
    """
    normalized = _normalize_bilibili_url(target_url)
    key = f"{normalized}|p={part}"
    digest = hashlib.md5(key.encode("utf-8")).hexdigest()
    return os.path.join(AUDIO_CACHE_DIR, f"{digest}.mp3")


def _audio_duration(path: str) -> float:
    """Return audio duration in seconds via ffprobe, or 0.0 on failure."""
    try:
        proc = subprocess.run(
            [
                "ffprobe", "-v", "error",
                "-show_entries", "format=duration",
                "-of", "default=noprint_wrappers=1:nokey=1",
                path,
            ],
            capture_output=True, text=True, timeout=30,
        )
        val = proc.stdout.strip()
        return float(val) if val else 0.0
    except (subprocess.TimeoutExpired, ValueError, OSError):
        return 0.0


def _audio_meta_path(out_path: str) -> str:
    return out_path + ".meta.json"


def _write_audio_meta(out_path: str, expected: int) -> None:
    """Persist the real (expected) duration next to the cached mp3 so a later
    read can detect a truncated download without re-fetching metadata."""
    try:
        with open(_audio_meta_path(out_path), "w", encoding="utf-8") as fh:
            json.dump({"expected": expected, "duration": _audio_duration(out_path)}, fh)
    except OSError:
        pass


def _cache_valid(out_path: str) -> bool:
    """True if the cached mp3 exists and isn't a clearly truncated partial.

    A legacy cache written before sidecar metadata exists is trusted as-is.
    """
    if not (os.path.exists(out_path) and os.path.getsize(out_path) > 0):
        return False
    meta_path = _audio_meta_path(out_path)
    if not os.path.exists(meta_path):
        return True
    try:
        with open(meta_path, encoding="utf-8") as fh:
            meta = json.load(fh)
        expected = int(meta.get("expected") or 0)
    except (OSError, json.JSONDecodeError):
        return True
    if expected:
        dur = _audio_duration(out_path)
        if dur and dur < expected * 0.5:
            return False
    return True


def _extract_playback_audio(target_url: str, part: Optional[int] = None) -> Optional[str]:
    """Download the audio track at a *listenable* bitrate and cache it on disk.

    Unlike _download_audio (which targets Whisper at 16 kHz/32 kbps), this keeps
    44.1 kHz mono at 64 kbps — plenty for speech, and ~¼ the size of 128k stereo
    so cold extraction through the flaky proxy is faster.
    Returns the cached .mp3 path, or None on failure.

    The residential proxy is flaky and can drop mid-download, leaving a truncated
    mp3 that still "exists" on disk. We guard against that with a duration check
    (re-extract any file clearly shorter than the real video) and by retrying the
    whole download with exponential backoff — a fresh proxy IP (rotating
    residential) often completes what the previous attempt dropped. The per-attempt
    subprocess timeout is kept well under the Cloudflare Worker's 180s budget so a
    failed attempt fails fast instead of burning the whole window.
    """
    out_path = _audio_cache_path(target_url, part)

    def _expected_duration() -> int:
        # Tight metadata budget: fail fast rather than burning the whole
        # extraction window on a flaky proxy watch-page fetch. A miss just
        # disables the truncation check below (still returns the file).
        try:
            return int(_fetch_meta(target_url, part, attempts=2, timeout=45).get("duration") or 0)
        except Exception:
            return 0

    if _cache_valid(out_path):
        return out_path

    expected = _expected_duration()

    # Hard wall-clock ceiling so we never exceed the Worker's 180s and 502
    # purely because the VPS was still working. Leave a margin for the Worker
    # to stream the result back.
    deadline = time.time() + AUDIO_OVERALL_TIMEOUT

    cmd = [
        sys.executable,
        "-m",
        "yt_dlp",
        "--js-runtimes",
        "node",
        "--remote-components",
        "ejs:github",
        "-f",
        "bestaudio/best",
        "--extract-audio",
        "--audio-format",
        "mp3",
        "--postprocessor-args",
        "ffmpeg:-ar 44100 -ac 1 -b:a 64k",
        "--retries",
        str(YTDLP_RETRIES),
        "--fragment-retries",
        str(YTDLP_RETRIES),
        *_playlist_flag(part),
        "--quiet",
        "--no-warnings",
        "-o",
        out_path,
        target_url,
    ]
    cmd += _site_args(target_url)

    backoff = 5  # seconds before the 2nd attempt; grows if more attempts allowed
    # YouTube: try NO proxy first (TVHTML5 bypasses the datacenter bot-check),
    # then alternate to the residential proxy on later attempts. Bilibili never
    # reaches here (the /api/audio route uses the API-direct path above).
    envs = [_no_proxy_env()]
    if YTDLP_PROXY and _is_youtube(target_url):
        envs.append(_proxy_env(target_url))
    for attempt in range(1, AUDIO_MAX_ATTEMPTS + 1):
        # Don't start an attempt we can't finish before the deadline — bail so
        # the frontend can auto-retry instead of us overrunning the Worker window.
        if time.time() + AUDIO_DL_TIMEOUT > deadline:
            break
        # Clear any partial file so a fresh attempt isn't skipped.
        try:
            if os.path.exists(out_path):
                os.remove(out_path)
        except OSError:
            pass
        try:
            subprocess.run(
                cmd, cwd=AUDIO_CACHE_DIR, capture_output=True, text=True,
                timeout=AUDIO_DL_TIMEOUT, env=envs[(attempt - 1) % len(envs)],
            )
        except subprocess.TimeoutExpired:
            # Don't burn the whole Worker budget on one hung attempt; let the
            # backoff + next attempt (fresh proxy IP) take a shot.
            pass
        if not (os.path.exists(out_path) and os.path.getsize(out_path) > 0):
            if attempt < AUDIO_MAX_ATTEMPTS:
                time.sleep(backoff)
                backoff = min(backoff * 2, 20)
            continue
        # Reject clearly truncated downloads (proxy dropped mid-stream).
        if expected:
            dur = _audio_duration(out_path)
            if dur and dur < expected * 0.5:
                try:
                    os.remove(out_path)
                except OSError:
                    pass
                if attempt < AUDIO_MAX_ATTEMPTS:
                    time.sleep(backoff)
                    backoff = min(backoff * 2, 20)
                continue
        _write_audio_meta(out_path, expected)
        return out_path
    return None


# Serialize concurrent extractions of the same audio so two requests (e.g. the
# background pre-warm fetch and the audio player's own fetch) don't spawn two
# yt-dlp processes that fight the flaky proxy — the second waits for the first.
_audio_inflight_lock = threading.Lock()
_audio_inflight: "dict[str, threading.Event]" = {}


def _extract_playback_audio_dedup(target_url: str, part: Optional[int]) -> Optional[str]:
    """Like _extract_playback_audio, but concurrent calls for the same url+part
    share a single extraction. The first caller does the work; later callers wait
    on an event and then read the resulting cache file."""
    key = _audio_cache_path(target_url, part)
    # Fast path: already cached (possibly by another in-flight request).
    if _cache_valid(key):
        return key
    with _audio_inflight_lock:
        ev = _audio_inflight.get(key)
        if ev is not None:
            # Another request is extracting this exact url+part; wait for it.
            ev.wait(timeout=AUDIO_OVERALL_TIMEOUT + 60)
            if _cache_valid(key):
                return key
            # The other attempt failed; fall through and try ourselves.
        ev = threading.Event()
        _audio_inflight[key] = ev
    try:
        return _extract_playback_audio(target_url, part)
    finally:
        with _audio_inflight_lock:
            _audio_inflight.pop(key, None)
            ev.set()


def _groq_transcribe(path: str) -> dict:
    """Send one audio file to Groq Whisper and return the EchoLearn payload.

    The language is deliberately auto-detected rather than hinted: the point of
    ASR on Bilibili is the English-language content hosted there, and pinning
    the hint to zh would wreck exactly those videos.
    """
    with open(path, "rb") as fh:
        blob = fh.read()

    if len(blob) > GROQ_MAX_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"Audio is {len(blob) // 1024 // 1024} MB, over the 25 MB Groq limit",
        )

    body, content_type = _multipart(
        {"model": GROQ_MODEL, "response_format": "verbose_json"},
        "audio.mp3",
        blob,
        "audio/mpeg",
    )
    req = urllib.request.Request(
        GROQ_ENDPOINT,
        data=body,
        headers={
            "Authorization": f"Bearer {GROQ_API_KEY}",
            "Content-Type": content_type,
            # Groq sits behind Cloudflare, which bans the default
            # "Python-urllib/3.x" UA with HTTP 403 / error 1010. Send a
            # non-default UA so the request is accepted.
            "User-Agent": "EchoLearn-VPS/1.0 (groq-asr)",
        },
        method="POST",
    )

    # Groq works directly from this VPS (verified end-to-end with no proxy),
    # and routing it through the residential proxy only adds a flaky hop
    # (Broken pipe / IncompleteRead). Call it directly and retry a couple of
    # times to absorb Groq's occasional transient 403/abuse throttle on the
    # free tier.
    raw = None
    last_err = ""
    for attempt in range(1, 3):
        try:
            with urllib.request.urlopen(req, timeout=GROQ_TIMEOUT) as resp:
                raw = json.load(resp)
            break
        except urllib.error.HTTPError as exc:
            last_err = exc.read().decode("utf-8", "ignore")[:400]
            # Surface 429 (out of quota) as-is; other HTTP errors may be
            # transient, so retry once.
            if exc.code == 429:
                raise HTTPException(status_code=429, detail=f"Groq HTTP 429: {last_err}")
            if attempt < 2:
                time.sleep(1)
                continue
            status = 502
            raise HTTPException(status_code=status, detail=f"Groq HTTP {exc.code}: {last_err}")
        except Exception as exc:  # noqa: BLE001 - transient network blips
            last_err = str(exc)
            if attempt < 2:
                time.sleep(1)
                continue
            raise HTTPException(status_code=502, detail=f"Groq request failed: {exc}")

    segments = raw.get("segments") or []
    lines = [
        {
            "id": f"yt_{i + 1}",
            "start": round(float(seg.get("start") or 0), 3),
            "end": round(float(seg.get("end") or 0), 3),
            "text": (seg.get("text") or "").strip(),
        }
        for i, seg in enumerate(segments)
        if (seg.get("text") or "").strip()
    ]

    if not lines:
        text = (raw.get("text") or "").strip()
        if not text:
            raise HTTPException(status_code=404, detail="Whisper returned no speech")
        lines = [{"id": "yt_1", "start": 0, "end": 0, "text": text}]

    return {
        "lines": lines,
        "language": raw.get("language") or "unknown",
        "isAutoGenerated": True,
        "source": "asr",
    }


# ── Routes ───────────────────────────────────────────────────────

@app.get("/api/transcript")
def transcript(
    video_id: Optional[str] = Query(default=None, alias="videoId"),
    url: Optional[str] = Query(default=None),
    lang: str = Query("en"),
    request: Request = None,
):
    target = url or video_id
    if not target:
        raise HTTPException(status_code=400, detail="Missing videoId or url")

    is_url = bool(url)
    clean_target = target
    part = None
    if is_url:
        if not _host_allowed(url):
            raise HTTPException(status_code=400, detail="Unsupported url host")
        clean_target, part = _extract_part(url)
    elif not _VIDEO_ID_RE.match(video_id or ""):
        raise HTTPException(status_code=400, detail="Invalid videoId")

    if YTDLP_API_KEY:
        provided = (request.headers.get("X-Api-Key") or "") if request else ""
        if provided != YTDLP_API_KEY:
            raise HTTPException(status_code=401, detail="Unauthorized")

    # Serve from cache (short TTL) to avoid re-hitting YouTube for the same
    # video+lang and to protect the single AWS IP from rate limits.
    cached = _cache_get(target, lang)
    if cached is not None:
        return JSONResponse(cached)

    result = _run_ytdlp(clean_target, lang, is_url=is_url, part=part)

    # Bilibili videos often expose only a Chinese AI subtitle ("ai-zh"). The app
    # is for English learners, so a Chinese-only transcript is useless for
    # vocabulary work. Treat a non-English-only result as "no usable transcript"
    # so the caller falls back to ASR (which returns an English transcript).
    # Videos that DO carry an English/ai-en track are served directly (fast).
    if result and _is_bilibili(clean_target) and not _is_english(result[1]):  # ECHOLEARN_BILI_ENGLISH_GATE
        result = None

    if not result:
        raise HTTPException(
            status_code=404, detail="No transcript available for this video"
        )

    lines, language, is_auto, bvid = result
    payload = {
        "lines": lines,
        "language": language,
        "isAutoGenerated": bool(is_auto),
    }
    if bvid and _is_bilibili(clean_target):
        payload["bvid"] = bvid
    _cache_put(target, lang, payload)
    return JSONResponse(payload)


@app.get("/api/info")
def info(
    url: str = Query(...),
    request: Request = None,
):
    """Lightweight metadata lookup (title / uploader / duration).

    Exists mainly so the Cloudflare Worker doesn't have to call Bilibili
    directly — Bilibili answers Cloudflare Worker egress IPs with HTTP 412,
    while the VPS IP is fine.
    """
    if not _host_allowed(url):
        raise HTTPException(status_code=400, detail="Unsupported url host")

    if YTDLP_API_KEY:
        provided = (request.headers.get("X-Api-Key") or "") if request else ""
        if provided != YTDLP_API_KEY:
            raise HTTPException(status_code=401, detail="Unauthorized")

    payload = _fetch_meta(url)
    # Surface the multi-part (分p) list so the frontend can render a part
    # picker. The view API answers the VPS IP directly (no proxy), and a
    # failure here is non-fatal — the picker just won't appear.
    if _is_bilibili(url):
        bvid = _extract_bvid(url) or payload.get("bvid")
        if bvid:
            parts = _bilibili_parts(bvid)
            if parts:
                payload["partCount"] = parts["partCount"]
                payload["parts"] = parts["parts"]
    return JSONResponse(payload)


@app.get("/api/asr")
def asr(
    url: str = Query(...),
    request: Request = None,
):
    """Transcribe a video's audio with Whisper.

    This is the fallback for videos that expose no subtitle track at all — most
    notably Bilibili, which serves audio anonymously but hides subtitle tracks
    behind a login.
    """
    clean_url, part = _extract_part(url)

    if not GROQ_API_KEY:
        raise HTTPException(status_code=503, detail="ASR not configured (no GROQ_API_KEY)")

    if not _host_allowed(clean_url):
        raise HTTPException(status_code=400, detail="Unsupported url host")

    if YTDLP_API_KEY:
        provided = (request.headers.get("X-Api-Key") or "") if request else ""
        if provided != YTDLP_API_KEY:
            raise HTTPException(status_code=401, detail="Unauthorized")

    # Bilibili: API-direct path (no proxy, no yt-dlp watch-page 412).
    if _is_bilibili(clean_url):
        cached = _cache_get(url, "__asr__")
        if cached is not None:
            return JSONResponse(cached)
        # Do not make ASR depend on a separate metadata lookup. Bilibili's
        # view API can transiently fail even while playurl/CDN audio works;
        # previously that surfaced as 404 "Could not fetch Bilibili info" and
        # prevented the actual API-direct ASR pipeline from running. The ASR
        # path below performs its own view lookup and can retry it. Duration
        # is still enforced when metadata is available, but metadata failure
        # is non-fatal here.
        try:
            duration = int(_fetch_meta(clean_url, part).get("duration") or 0)
        except HTTPException:
            duration = 0
        if duration > ASR_MAX_DURATION:
            raise HTTPException(
                status_code=413,
                detail=(
                    f"Video is {duration // 60} min, over the "
                    f"{ASR_MAX_DURATION // 60} min ASR limit"
                ),
            )
        payload = _bilibili_asr(clean_url, part)
        _cache_put(url, "__asr__", payload)
        return JSONResponse(payload)

    # ASR costs real quota, so a cache hit is worth much more here than on the
    # subtitle routes.
    cached = _cache_get(url, "__asr__")
    if cached is not None:
        return JSONResponse(cached)

    duration = int(_fetch_meta(clean_url, part).get("duration") or 0)
    if duration > ASR_MAX_DURATION:
        raise HTTPException(
            status_code=413,
            detail=(
                f"Video is {duration // 60} min, over the "
                f"{ASR_MAX_DURATION // 60} min ASR limit"
            ),
        )

    with tempfile.TemporaryDirectory() as td:
        audio_path = _download_audio(clean_url, td, part)
        if not audio_path:
            raise HTTPException(status_code=502, detail="Could not download audio")
        payload = _groq_transcribe(audio_path)

    _cache_put(url, "__asr__", payload)
    return JSONResponse(payload)


@app.get("/api/audio")
def audio(
    url: str = Query(...),
    request: Request = None,
):
    """Stream a video's audio track (mp3) for the in-app audio-only player.

    Cached on disk by URL+part so repeat plays are instant. The Cloudflare
    Worker proxies this endpoint to the browser, where a native <audio>
    element plays it and drives transcript sync via its currentTime.
    """
    clean_url, part = _extract_part(url)

    if not _host_allowed(clean_url):
        raise HTTPException(status_code=400, detail="Unsupported url host")

    if YTDLP_API_KEY:
        provided = (request.headers.get("X-Api-Key") or "") if request else ""
        if provided != YTDLP_API_KEY:
            raise HTTPException(status_code=401, detail="Unauthorized")

    path = _audio_cache_path(clean_url, part)
    if _is_bilibili(clean_url):
        # API-direct: CDN download + ffmpeg, no proxy, no yt-dlp watch-page 412.
        if not _cache_valid(path):
            if not _bilibili_audio(clean_url, part, path):
                raise HTTPException(status_code=502, detail="Could not extract audio")
        return FileResponse(
            path,
            media_type="audio/mpeg",
            filename=os.path.basename(path),
            content_disposition_type="inline",
            headers={"Cache-Control": "public, max-age=86400, immutable"},
        )

    if not (os.path.exists(path) and os.path.getsize(path) > 0):
        path = _extract_playback_audio_dedup(clean_url, part)
    if not path:
        raise HTTPException(status_code=502, detail="Could not extract audio")

    return FileResponse(
        path,
        media_type="audio/mpeg",
        filename=os.path.basename(path),
        content_disposition_type="inline",
        headers={"Cache-Control": "public, max-age=86400, immutable"},
    )


@app.get("/api/health")
def health():
    return {
        "status": "ok",
        "asr": bool(GROQ_API_KEY),
        "asrMaxDuration": ASR_MAX_DURATION,
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", "8000")))
