"""
EchoLearn — server-side YouTube transcript service (FastAPI + yt-dlp)

Runs on a small always-on VPS. yt-dlp does the heavy lifting: it rotates
YouTube client signatures (web / android / tv / ios) and the TVHTML5 client
bypasses YouTube's datacenter-IP bot check, so captions can be fetched
without a residential proxy for the vast majority of videos.

Endpoints
  GET /api/transcript?videoId=<id>&lang=<en>
  GET /api/health

Response shape (matches the EchoLearn web/Worker contract):
  {
    "lines": [{"id": "yt_1", "start": 0.0, "end": 1.23, "text": "..."}, ...],
    "language": "en",
    "isAutoGenerated": false
  }

Environment
  YTDLP_TIMEOUT   subprocess hard timeout in seconds (default 90)
  YTDLP_PROXY     optional upstream proxy passed to yt-dlp (e.g. a residential
                  proxy endpoint) for videos YouTube blocks even from datacenter
  YTDLP_API_KEY   if set, /api/transcript requires header X-Api-Key to match
  YTDLP_CACHE_TTL in-memory cache TTL in seconds for fetched transcripts (default 3600)
"""

import json
import os
import re
import subprocess
import sys
import tempfile
import time
from collections import OrderedDict
from typing import Optional

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

app = FastAPI(title="EchoLearn yt-dlp transcript service")

# Permissive CORS: this is a private service fronted by Cloudflare; the CF
# Worker calls it server-to-server (no Origin), but allow all origins so it
# can also be called directly during local testing.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "OPTIONS"],
    allow_headers=["*"],
)

YTDLP_TIMEOUT = int(os.environ.get("YTDLP_TIMEOUT", "180"))
YTDLP_PROXY = os.environ.get("YTDLP_PROXY") or ""
YTDLP_API_KEY = os.environ.get("YTDLP_API_KEY") or ""
YTDLP_CACHE_TTL = int(os.environ.get("YTDLP_CACHE_TTL", "3600"))  # seconds

_VIDEO_ID_RE = re.compile(r"^[a-zA-Z0-9_-]{6,15}$")

# ── In-memory TTL cache (keyed by video_id:lang) ──────────────
# Protects the single VPS IP from repeat YouTube hits on popular videos and
# speeds up repeated fetches of the same video+lang. Only successful results
# are cached; failures are always retried.
_CACHE: "OrderedDict[str, tuple[float, dict]]" = OrderedDict()
_CACHE_MAX = 2000


def _cache_get(video_id: str, lang: str):
    key = f"{video_id}:{lang}"
    item = _CACHE.get(key)
    if item is None:
        return None
    expiry, payload = item
    if expiry < time.time():
        _CACHE.pop(key, None)
        return None
    _CACHE.move_to_end(key)  # LRU touch
    return payload


def _cache_put(video_id: str, lang: str, payload: dict):
    key = f"{video_id}:{lang}"
    _CACHE[key] = (time.time() + YTDLP_CACHE_TTL, payload)
    _CACHE.move_to_end(key)
    if len(_CACHE) > _CACHE_MAX:
        _CACHE.popitem(last=False)  # evict oldest


# ── Parsers ───────────────────────────────────────────────────────

def _parse_json3(raw: dict) -> list:
    events = raw.get("events", []) if isinstance(raw, dict) else []
    lines = []
    idx = 0
    for ev in events:
        segs = ev.get("segs") or []
        text = "".join(s.get("utf8", "") for s in segs).strip()
        if not text:
            continue
        start = (ev.get("tStartMs") or 0) / 1000.0
        dur = ev.get("dDurationMs") or 0
        lines.append(
            {
                "id": f"yt_{idx + 1}",
                "start": round(start, 3),
                "end": round(start + dur / 1000.0, 3),
                "text": text,
            }
        )
        idx += 1
    return lines


def _parse_vtt(text: str) -> list:
    # Strip WEBVTT header and any NOTE blocks.
    lines = []
    idx = 0
    # Split into cues by blank lines.
    blocks = re.split(r"\n\s*\n", text)
    cue_re = re.compile(
        r"(\d{1,2}:)?\d{1,2}:\d{2}\.\d{1,3}\s*-->\s*(\d{1,2}:)?\d{1,2}:\d{2}\.\d{1,3}"
    )
    for block in blocks:
        block = block.strip()
        if not block or block.startswith("WEBVTT") or block.startswith("NOTE"):
            continue
        parts = block.split("\n")
        # First line may be a cue index or the timestamp; find the timestamp line.
        ts_line = None
        text_lines = []
        for line in parts:
            if cue_re.search(line):
                ts_line = line
            elif not line.strip().isdigit() or ts_line is None:
                text_lines.append(line)
        if not ts_line:
            continue
        m = cue_re.search(ts_line)
        start_str, end_str = m.group(0).split("-->")
        start = _vtt_time_to_sec(start_str.strip())
        end = _vtt_time_to_sec(end_str.strip())
        text = " ".join(text_lines).strip()
        # Strip inline tags like <c>, <i>, <00:00:00.000>
        text = re.sub(r"<[^>]+>", "", text).strip()
        if not text:
            continue
        lines.append(
            {
                "id": f"yt_{idx + 1}",
                "start": round(start, 3),
                "end": round(end, 3),
                "text": text,
            }
        )
        idx += 1
    return lines


def _vtt_time_to_sec(s: str) -> float:
    s = s.strip()
    # Formats: HH:MM:SS.mmm or MM:SS.mmm
    parts = s.split(":")
    parts = [float(p) for p in parts]
    if len(parts) == 3:
        h, m, sec = parts
    else:
        h, m, sec = 0, parts[0], parts[1]
    return h * 3600 + m * 60 + sec


def _read_subtitle_file(td: str):
    """Return (lines, language, is_auto) for the first usable subtitle file."""
    for fname in sorted(os.listdir(td)):
        path = os.path.join(td, fname)
        if fname.endswith(".json3"):
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    raw = json.load(fh)
            except Exception:
                continue
            lines = _parse_json3(raw)
        elif fname.endswith(".vtt"):
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    raw = fh.read()
            except Exception:
                continue
            lines = _parse_vtt(raw)
        else:
            continue
        if not lines:
            continue
        m = re.search(r"\.([a-zA-Z]{2}(?:-[A-Za-z]+)?(?:-orig)?)\.(?:json3|vtt)$", fname)
        language = m.group(1) if m else "en"
        is_auto = "auto" in fname or "-orig" in fname
        return lines, language, is_auto
    return None


# ── yt-dlp invocation ────────────────────────────────────────────

def _run_ytdlp(video_id_or_url: str, lang: str, *, is_url: bool = False):
    base = lang.split("-")[0]
    target_url = video_id_or_url if is_url else f"https://www.youtube.com/watch?v={video_id_or_url}"
    with tempfile.TemporaryDirectory() as td:
        out_tmpl = os.path.join(td, "%(id)s")
        # Try the exact requested lang, then its base code with variants
        # (covers en-US / en-orig auto captions).
        for sub_langs in (lang, f"{base}.*"):
            cmd = [
                sys.executable,
                "-m",
                "yt_dlp",
                "--skip-download",
                "--write-subs",
                "--write-auto-subs",
                "--sub-langs",
                sub_langs,
                "--sub-format",
                "vtt",
                "--quiet",
                "--no-warnings",
                "--no-playlist",
                "--no-overwrites",
                "-o",
                out_tmpl,
                target_url,
            ]
            if YTDLP_PROXY:
                cmd += ["--proxy", YTDLP_PROXY]
            try:
                subprocess.run(
                    cmd,
                    cwd=td,
                    capture_output=True,
                    text=True,
                    timeout=YTDLP_TIMEOUT,
                )
            except subprocess.TimeoutExpired:
                continue
            result = _read_subtitle_file(td)
            if result:
                return result
        return None


# ── Routes ───────────────────────────────────────────────────────

@app.get("/api/transcript")
def transcript(
    video_id: Optional[str] = Query(default=None, alias="videoId"),
    url: Optional[str] = Query(default=None),
    lang: str = Query("en"),
    request: Request = None,
):
    target = url or video_id
    if not target:
        raise HTTPException(status_code=400, detail="Missing videoId or url")

    is_url = bool(url)
    if not is_url and not _VIDEO_ID_RE.match(video_id or ""):
        raise HTTPException(status_code=400, detail="Invalid videoId")

    if YTDLP_API_KEY:
        provided = (request.headers.get("X-Api-Key") or "") if request else ""
        if provided != YTDLP_API_KEY:
            raise HTTPException(status_code=401, detail="Unauthorized")

    # Serve from cache (short TTL) to avoid re-hitting YouTube for the same
    # video+lang and to protect the single AWS IP from rate limits.
    cached = _cache_get(target, lang)
    if cached is not None:
        return JSONResponse(cached)

    result = _run_ytdlp(target, lang, is_url=is_url)
    if not result:
        raise HTTPException(
            status_code=404, detail="No transcript available for this video"
        )

    lines, language, is_auto = result
    payload = {
        "lines": lines,
        "language": language,
        "isAutoGenerated": bool(is_auto),
    }
    _cache_put(target, lang, payload)
    return JSONResponse(payload)


@app.get("/api/health")
def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", "8000")))
