/**
 * Vercel Serverless Function (Node.js runtime) — YouTube transcript fetcher.
 *
 * Uses the `youtube-transcript` npm package on the server side,
 * where there's no CORS issue and the server IP may not be blocked
 * by YouTube's bot detection.
 *
 * Usage: GET /api/transcript?videoId=<id>&lang=<en>
 * Returns: JSON with transcript lines
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default async function handler(req: any, res: any): Promise<void> {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  const videoId = req.query?.videoId;
  const lang = (req.query?.lang as string) || 'en';

  if (!videoId || typeof videoId !== 'string') {
    res.status(400).json({ error: 'Missing videoId parameter' });
    return;
  }

  try {
    const { YoutubeTranscript } = await import('youtube-transcript');
    const result = await YoutubeTranscript.fetchTranscript(videoId, { lang });

    if (!result || result.length === 0) {
      res.status(404).json({ error: 'No transcript found for this video' });
      return;
    }

    // Transform to our TranscriptLine format
    const lines = result.map(
      (item: { text: string; offset: number; duration: number }, i: number) => ({
        id: `yt_${i + 1}`,
        start: item.offset > 1000 ? item.offset / 1000 : item.offset,
        end:
          (item.offset > 1000 ? item.offset / 1000 : item.offset) +
          (item.duration > 1000 ? item.duration / 1000 : item.duration),
        text: item.text,
      }),
    );

    res.status(200).json({
      lines,
      language: result[0]?.lang ?? lang,
      isAutoGenerated: true,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    console.error('[transcript] Error:', message);
    res.status(500).json({ error: message });
  }
}
