/**
 * Vercel Serverless Function (Node.js runtime) — YouTube transcript fetcher.
 *
 * Uses the `youtube-transcript` npm package on the server side with
 * a CONSENT cookie to help bypass YouTube's bot detection.
 *
 * COMPLIANCE NOTE: This endpoint fetches auto-generated captions via
 * unofficial means (youtube-transcript package / InnerTube). This may
 * violate YouTube's Terms of Service. Risk is low at small scale but
 * increases with traffic. Fallback: manual transcript paste in the UI.
 *
 * Usage: GET /api/transcript?videoId=<id>&lang=<en>
 * Returns: JSON with transcript lines
 */

// Consent cookie to help bypass YouTube's bot wall
const CONSENT_COOKIE =
  'CONSENT=PENDING+987; SOCS=CAISNQgDEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjMwODI5LjA3X3AxGgJlbiACGgYIgJnSmgY';

const VPS_API_URL = 'https://yt-api.echo-learn.uk';
// Caption-only Vercel fallback budget. The client leaves a small transport
// margin above this deadline; later providers receive only the time remaining.
const TRANSCRIPT_DEADLINE_MS = 21_000;
const VPS_TIMEOUT_MS = 1_000;
const NPM_FALLBACK_TIMEOUT_MS = 6_500;
// The observed positive Supadata matrix includes a 14.352s response. Keep a
// bounded provider cap with margin while reserving time for a later fallback.
const SUPADATA_TIMEOUT_MS = 18_000;
const SUPADATA_API_URL = 'https://api.supadata.ai/v1/transcript';
const TRACE_HEADER = 'X-EchoLearn-Trace-Id';

function createTraceId(): string {
  return typeof crypto?.randomUUID === 'function'
    ? crypto.randomUUID()
    : `trace-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function logTranscriptEvent(event: string, fields: Record<string, unknown>): void {
  console.info(JSON.stringify({ service: 'vercel-transcript', event, ...fields }));
}

// ── Per-IP rate limiter (per serverless instance, best-effort) ──
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX = 20;
const rateBuckets = new Map<string, number[]>();

function isRateLimited(ip: string): boolean {
  const now = Date.now();
  const cutoff = now - RATE_LIMIT_WINDOW_MS;
  if (rateBuckets.size >= 5000) {
    for (const [k, v] of rateBuckets) {
      if (v.length === 0 || v[v.length - 1] <= cutoff) rateBuckets.delete(k);
    }
  }
  let hits = rateBuckets.get(ip);
  if (!hits) { hits = []; rateBuckets.set(ip, hits); }
  while (hits.length > 0 && hits[0] <= cutoff) hits.shift();
  if (hits.length >= RATE_LIMIT_MAX) return true;
  hits.push(now);
  return false;
}

// Origins allowed to call this endpoint via CORS.
const ALLOWED_ORIGINS = [
  'https://app.echo-learn.uk',
  'https://echo-learn.uk',
  'http://localhost:5173',
  'http://localhost:4173',
  'http://127.0.0.1:5173',
];

function resolveOrigin(origin: string | undefined): string | null {
  if (!origin) return null;
  if (ALLOWED_ORIGINS.includes(origin)) return origin;
  if (origin.endsWith('.vercel.app')) return origin; // Vercel preview deployments
  return null;
}

function isUsableTranscript(data: unknown): data is {
  lines: Array<Record<string, unknown>>;
  language?: string;
  isAutoGenerated?: boolean;
  source?: string;
} {
  if (!data || typeof data !== 'object') return false;
  const candidate = data as { lines?: unknown };
  return Array.isArray(candidate.lines) && candidate.lines.length > 0;
}

const TRANSCRIPT_FAILURE_CODES = {
  CAPTIONS_NOT_FOUND: 'captions_not_found',
  ACQUISITION_BLOCKED: 'youtube_acquisition_blocked',
  PROVIDER_TIMEOUT: 'provider_timeout',
  TRANSCRIPT_DISABLED: 'transcript_disabled',
  ASR_REQUIRED: 'asr_required',
  PROVIDER_FAILURE: 'provider_failure',
} as const;

type TranscriptFailureCode = (typeof TRANSCRIPT_FAILURE_CODES)[keyof typeof TRANSCRIPT_FAILURE_CODES];

interface TranscriptFailure {
  code: TranscriptFailureCode;
  status: number;
  message: string;
}

function failureForCode(code: TranscriptFailureCode): TranscriptFailure {
  switch (code) {
    case TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT:
      return { code, status: 504, message: 'Transcript provider timed out.' };
    case TRANSCRIPT_FAILURE_CODES.ACQUISITION_BLOCKED:
      return { code, status: 403, message: 'YouTube media acquisition is currently unavailable.' };
    case TRANSCRIPT_FAILURE_CODES.TRANSCRIPT_DISABLED:
      return { code, status: 404, message: 'Transcript is disabled on this video.' };
    case TRANSCRIPT_FAILURE_CODES.ASR_REQUIRED:
      return { code, status: 409, message: 'Explicit ASR opt-in is required for transcript recovery.' };
    case TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE:
      return { code, status: 500, message: 'Transcript provider failed.' };
    case TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND:
    default:
      return { code: TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND, status: 404, message: 'No caption transcript is available for this video.' };
  }
}

function structuredFailureCode(payload: unknown): TranscriptFailureCode | undefined {
  if (!payload || typeof payload !== 'object') return undefined;
  const candidate = payload as {
    code?: unknown;
    error?: unknown;
    detail?: { code?: unknown };
  };
  const values = [candidate.code, candidate.detail?.code, candidate.error];
  return values.find((value): value is TranscriptFailureCode =>
    typeof value === 'string'
    && Object.values(TRANSCRIPT_FAILURE_CODES).includes(value as TranscriptFailureCode),
  );
}

function classifyVpsFailure(status: number, payload: unknown): TranscriptFailure {
  const structuredCode = structuredFailureCode(payload);
  if (structuredCode) return failureForCode(structuredCode);
  if (status === 408 || status === 504) return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT);
  if (status === 404) return failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);
  return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
}

function classifyYoutubeFailure(message: string): TranscriptFailure {
  const normalized = message.toLowerCase();
  if (normalized.includes('timeout') || normalized.includes('timed out')) {
    return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT);
  }
  if (normalized.includes('disabled')) {
    return failureForCode(TRANSCRIPT_FAILURE_CODES.TRANSCRIPT_DISABLED);
  }
  if (normalized.includes('no transcripts') || normalized.includes('no transcript')) {
    return failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);
  }
  return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
}

function remainingTranscriptBudget(deadlineAt: number): number {
  return Math.max(0, deadlineAt - Date.now());
}

interface SupadataCue {
  text?: unknown;
  offset?: unknown;
  duration?: unknown;
}

function normalizeSupadataTranscript(payload: unknown, requestedLang?: string): Record<string, unknown> | null {
  if (!payload || typeof payload !== 'object') return null;
  const candidate = payload as { content?: unknown; lang?: unknown };
  if (!Array.isArray(candidate.content) || candidate.content.length === 0) return null;
  const language = typeof candidate.lang === 'string' && candidate.lang.trim()
    ? candidate.lang.trim()
    : requestedLang;
  if (!language) return null;

  const cues = candidate.content.map((item, index) => {
    if (!item || typeof item !== 'object') return null;
    const cue = item as SupadataCue;
    const text = typeof cue.text === 'string' ? cue.text.trim() : '';
    const offset = cue.offset;
    const duration = cue.duration;
    if (
      !text
      || typeof offset !== 'number'
      || typeof duration !== 'number'
      || !Number.isFinite(offset)
      || !Number.isFinite(duration)
      || offset < 0
      || duration < 0
      || !Number.isFinite(offset + duration)
    ) {
      return null;
    }
    return { index, offset, duration, text };
  });

  if (cues.some((cue) => cue === null)) return null;

  const lines = cues
    .filter((cue): cue is { index: number; offset: number; duration: number; text: string } => cue !== null)
    .sort((a, b) => a.offset - b.offset || a.index - b.index)
    .map((cue, index) => ({
      id: `supadata_${index + 1}`,
      start: cue.offset / 1000,
      end: (cue.offset + cue.duration) / 1000,
      text: cue.text,
    }));

  return { lines, language, source: 'supadata' };
}

function classifySupadataHttpFailure(status: number): TranscriptFailure {
  if (status === 408 || status === 504) {
    return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT);
  }
  return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
}

async function fetchSupadataTranscript(
  videoId: string,
  requestedLang: string | undefined,
  apiKey: string,
  traceId: string,
  deadlineAt: number,
): Promise<{ data: Record<string, unknown> | null; failure?: TranscriptFailure }> {
  const startedAt = Date.now();
  const remainingMs = remainingTranscriptBudget(deadlineAt);
  const timeoutMs = Math.min(SUPADATA_TIMEOUT_MS, remainingMs);
  if (timeoutMs <= 0) {
    const failure = failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT);
    logTranscriptEvent('provider_result', {
      traceId,
      provider: 'supadata',
      outcome: failure.code,
      latencyMs: Date.now() - startedAt,
      reason: 'deadline_exhausted',
    });
    return { data: null, failure };
  }

  const controller = new AbortController();
  let timer: ReturnType<typeof setTimeout> | undefined;
  let timedOut = false;
  const query = new URLSearchParams({
    url: `https://www.youtube.com/watch?v=${videoId}`,
    mode: 'native',
    text: 'false',
  });
  if (requestedLang) query.set('lang', requestedLang);

  try {
    const upstream = await Promise.race([
      fetch(`${SUPADATA_API_URL}?${query.toString()}`, {
        headers: { 'x-api-key': apiKey, [TRACE_HEADER]: traceId },
        signal: controller.signal,
      }),
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => {
          timedOut = true;
          controller.abort();
          reject(new Error('supadata provider timed out'));
        }, timeoutMs);
      }),
    ]);

    // Supadata uses 206 for native-caption unavailability. It is a normal
    // fallback outcome, not a timeout or generic provider failure.
    if (upstream.status === 206) {
      const failure = failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);
      logTranscriptEvent('provider_result', {
        traceId,
        provider: 'supadata',
        outcome: failure.code,
        latencyMs: Date.now() - startedAt,
        status: upstream.status,
      });
      return { data: null, failure };
    }

    if (!upstream.ok) {
      const failure = classifySupadataHttpFailure(upstream.status);
      logTranscriptEvent('provider_result', {
        traceId,
        provider: 'supadata',
        outcome: failure.code,
        latencyMs: Date.now() - startedAt,
        status: upstream.status,
      });
      return { data: null, failure };
    }

    let payload: unknown;
    try {
      payload = await upstream.json();
    } catch {
      const failure = failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
      logTranscriptEvent('provider_result', {
        traceId,
        provider: 'supadata',
        outcome: failure.code,
        latencyMs: Date.now() - startedAt,
        status: upstream.status,
        reason: 'malformed_json',
      });
      return { data: null, failure };
    }

    const data = normalizeSupadataTranscript(payload, requestedLang);
    if (!data) {
      const failure = failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
      logTranscriptEvent('provider_result', {
        traceId,
        provider: 'supadata',
        outcome: failure.code,
        latencyMs: Date.now() - startedAt,
        status: upstream.status,
        reason: 'empty_or_malformed',
      });
      return { data: null, failure };
    }

    logTranscriptEvent('provider_result', {
      traceId,
      provider: 'supadata',
      outcome: 'success',
      latencyMs: Date.now() - startedAt,
      status: upstream.status,
      lineCount: (data.lines as unknown[]).length,
    });
    return { data };
  } catch (err) {
    const failure = timedOut || (err instanceof Error && err.name === 'AbortError')
      ? failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT)
      : failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
    logTranscriptEvent('provider_result', {
      traceId,
      provider: 'supadata',
      outcome: failure.code,
      latencyMs: Date.now() - startedAt,
      reason: failure.code === TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT ? 'timeout' : 'network_error',
    });
    return { data: null, failure };
  } finally {
    if (timer) clearTimeout(timer);
  }
}

function chooseFinalFailure(
  vpsFailure: TranscriptFailure | undefined,
  supadataFailure: TranscriptFailure | undefined,
  npmFailure: TranscriptFailure | undefined,
  npmReturnedEmpty: boolean,
): TranscriptFailure {
  const existingFailure = npmFailure
    ? (npmFailure.code === TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT
      ? npmFailure
      : (vpsFailure || npmFailure))
    : (vpsFailure || (npmReturnedEmpty ? failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND) : undefined));
  const fallbackFailure = existingFailure || failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);

  // Preserve an earlier typed provider/acquisition failure and never let a
  // Supadata 206/native-unavailable result relabel it as no captions.
  if (
    supadataFailure
    && supadataFailure.code !== TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND
    && fallbackFailure.code === TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND
  ) {
    return supadataFailure;
  }
  return fallbackFailure;
}

async function fetchYoutubeTranscriptWithTimeout<T>(
  work: (signal: AbortSignal) => Promise<T>,
  timeoutMs: number,
): Promise<T> {
  if (timeoutMs <= 0) {
    const error = new Error('youtube-transcript provider timed out');
    error.name = 'AbortError';
    throw error;
  }
  const controller = new AbortController();
  let timer: ReturnType<typeof setTimeout> | undefined;
  let timedOut = false;
  try {
    try {
      return await Promise.race([
        work(controller.signal),
        new Promise<never>((_, reject) => {
          timer = setTimeout(() => {
            timedOut = true;
            controller.abort();
            reject(new Error('youtube-transcript provider timed out'));
          }, timeoutMs);
        }),
      ]);
    } catch (err) {
      // controller.abort() can make the work promise reject before the
      // synthetic timeout wins Promise.race. The local marker makes that race
      // deterministic and keeps the public error contract typed.
      if (timedOut) {
        const error = new Error('youtube-transcript provider timed out');
        error.name = 'AbortError';
        throw error;
      }
      throw err;
    }
  } finally {
    if (timer) clearTimeout(timer);
  }
}

async function fetchVpsTranscript(
  videoId: string,
  lang: string,
  apiKey: string,
  traceId: string,
  deadlineAt: number,
): Promise<{ data: Record<string, unknown> | null; failure?: TranscriptFailure }> {
  const controller = new AbortController();
  const timeoutMs = Math.min(VPS_TIMEOUT_MS, remainingTranscriptBudget(deadlineAt));
  if (timeoutMs <= 0) {
    return { data: null, failure: failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT) };
  }
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const upstream = await fetch(
      `${VPS_API_URL}/api/transcript?videoId=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(lang)}`,
      {
        headers: { 'X-Api-Key': apiKey, [TRACE_HEADER]: traceId },
        signal: controller.signal,
      },
    );
    if (!upstream.ok) {
      const payload = await upstream.json().catch(() => undefined);
      const failure = classifyVpsFailure(upstream.status, payload);
      logTranscriptEvent('vps_result', { traceId, videoId, status: upstream.status, usable: false, error: failure.code });
      return { data: null, failure };
    }
    let data: unknown;
    try {
      data = await upstream.json();
    } catch {
      const failure = failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
      logTranscriptEvent('vps_result', { traceId, videoId, status: upstream.status, usable: false, reason: 'malformed_json', error: failure.code });
      return { data: null, failure };
    }
    if (!isUsableTranscript(data)) {
      const failure = failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);
      logTranscriptEvent('vps_result', { traceId, videoId, status: upstream.status, usable: false, reason: 'empty_or_malformed', error: failure.code });
      return { data: null, failure };
    }
    logTranscriptEvent('vps_result', { traceId, videoId, status: upstream.status, usable: true, lineCount: data.lines.length });
    return { data: { ...data, source: (data as { source?: string }).source || 'vps' } };
  } catch (err) {
    logTranscriptEvent('vps_error', {
      traceId,
      videoId,
      error: err instanceof Error && err.name === 'AbortError' ? 'timeout' : 'network_or_parse',
    });
    return {
      data: null,
      failure: failureForCode(
        err instanceof Error && err.name === 'AbortError'
          ? TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT
          : TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE,
      ),
    };
  } finally {
    clearTimeout(timer);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default async function handler(req: any, res: any): Promise<void> {
  const traceId = createTraceId();
  res.setHeader(TRACE_HEADER, traceId);
  logTranscriptEvent('request_start', { traceId, method: req.method });
  // CORS headers (restricted to the app's known origins)
  const allowed = resolveOrigin(req.headers?.origin as string | undefined);
  if (allowed) res.setHeader('Access-Control-Allow-Origin', allowed);
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Expose-Headers', TRACE_HEADER);

  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  // Rate limit per IP
  const ip = (req.headers?.['x-forwarded-for'] as string)?.split(',')[0]?.trim()
    || (req.headers?.['x-real-ip'] as string)
    || (req.socket?.remoteAddress as string)
    || 'unknown';
  if (isRateLimited(ip)) {
    res.status(429).json({ error: 'Rate limit exceeded. Please slow down.' });
    return;
  }

  const videoId = req.query?.videoId;
  const requestedLang = typeof req.query?.lang === 'string' && req.query.lang.trim()
    ? req.query.lang.trim()
    : undefined;
  const lang = requestedLang || 'en';

  if (!videoId || typeof videoId !== 'string') {
    res.status(400).json({ error: 'Missing videoId parameter' });
    return;
  }

  const deadlineAt = Date.now() + TRANSCRIPT_DEADLINE_MS;
  let vpsFailure: TranscriptFailure | undefined;
  let supadataFailure: TranscriptFailure | undefined;
  let npmFailure: TranscriptFailure | undefined;
  let npmReturnedEmpty = false;
  try {
    const vpsKey = process.env.YTDLP_API_KEY;
    // This is the useful recovery path after Worker transport/generic 5xx
    // failures. It calls the VPS caption transcript route, not /api/asr;
    // frontend structured Worker outcomes stop before reaching this endpoint.
    if (vpsKey) {
      const vpsOutcome = await fetchVpsTranscript(videoId, lang, vpsKey, traceId, deadlineAt);
      vpsFailure = vpsOutcome.failure;
      if (vpsOutcome.data) {
        logTranscriptEvent('request_finish', { traceId, videoId, provider: 'vps', status: 200 });
        res.status(200).json(vpsOutcome.data);
        return;
      }
    }

    const supadataKey = process.env.SUPADATA_API_KEY;
    if (supadataKey) {
      const supadataOutcome = await fetchSupadataTranscript(
        videoId,
        requestedLang,
        supadataKey,
        traceId,
        deadlineAt,
      );
      supadataFailure = supadataOutcome.failure;
      if (supadataOutcome.data) {
        logTranscriptEvent('request_finish', {
          traceId,
          provider: 'supadata',
          status: 200,
          lineCount: (supadataOutcome.data.lines as unknown[]).length,
        });
        res.status(200).json(supadataOutcome.data);
        return;
      }
    }

    const npmTimeoutMs = Math.min(NPM_FALLBACK_TIMEOUT_MS, remainingTranscriptBudget(deadlineAt));
    if (npmTimeoutMs <= 0) {
      npmFailure = failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT);
    } else {
      const { YoutubeTranscript } = await import('youtube-transcript');

      const result = await fetchYoutubeTranscriptWithTimeout(
        (signal) => {
          // Custom fetch adds the consent cookie while retaining the remaining
          // overall caption deadline for this Vercel fallback.
          const customFetch = (url: string | URL | Request, init?: RequestInit) => {
            const headers = new Headers(init?.headers);
            headers.set('Cookie', CONSENT_COOKIE);
            if (!headers.has('User-Agent')) {
              headers.set(
                'User-Agent',
                'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
              );
            }
            return fetch(url, { ...init, headers, signal });
          };
          return YoutubeTranscript.fetchTranscript(videoId, { lang, fetch: customFetch });
        },
        npmTimeoutMs,
      );

      if (!result || result.length === 0) {
        npmReturnedEmpty = true;
      } else {
        // Transform to our TranscriptLine format
        const lines = result.map(
          (item: { text: string; offset: number; duration: number }, i: number) => ({
            id: `yt_${i + 1}`,
            start: item.offset > 1000 ? item.offset / 1000 : item.offset,
            end:
              (item.offset > 1000 ? item.offset / 1000 : item.offset) +
              (item.duration > 1000 ? item.duration / 1000 : item.duration),
            text: item.text,
          }),
        );

        logTranscriptEvent('request_finish', { traceId, videoId, provider: 'youtube-transcript', status: 200, lineCount: lines.length });
        res.status(200).json({
          lines,
          language: result[0]?.lang ?? lang,
          isAutoGenerated: true,
        });
        return;
      }
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    npmFailure = classifyYoutubeFailure(message);
  }

  const failure = chooseFinalFailure(vpsFailure, supadataFailure, npmFailure, npmReturnedEmpty);
  logTranscriptEvent('request_error', { traceId, videoId, status: failure.status, error: failure.code });
  res.status(failure.status).json({ error: failure.code, code: failure.code, message: failure.message });
}
