/**
 * Vercel Serverless Function (Node.js runtime) — YouTube transcript fetcher.
 *
 * Uses the `youtube-transcript` npm package on the server side with
 * a CONSENT cookie to help bypass YouTube's bot detection.
 *
 * COMPLIANCE NOTE: This endpoint fetches auto-generated captions via
 * unofficial means (youtube-transcript package / InnerTube). This may
 * violate YouTube's Terms of Service. Risk is low at small scale but
 * increases with traffic. Fallback: manual transcript paste in the UI.
 *
 * Usage: GET /api/transcript?videoId=<id>&lang=<en>
 * Returns: JSON with transcript lines
 */

// Consent cookie to help bypass YouTube's bot wall
const CONSENT_COOKIE =
  'CONSENT=PENDING+987; SOCS=CAISNQgDEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjMwODI5LjA3X3AxGgJlbiACGgYIgJnSmgY';

const VPS_API_URL = 'https://yt-api.echo-learn.uk';
const VPS_TIMEOUT_MS = 45_000;
const TRACE_HEADER = 'X-EchoLearn-Trace-Id';

function createTraceId(): string {
  return typeof crypto?.randomUUID === 'function'
    ? crypto.randomUUID()
    : `trace-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function logTranscriptEvent(event: string, fields: Record<string, unknown>): void {
  console.info(JSON.stringify({ service: 'vercel-transcript', event, ...fields }));
}

// ── Per-IP rate limiter (per serverless instance, best-effort) ──
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX = 20;
const rateBuckets = new Map<string, number[]>();

function isRateLimited(ip: string): boolean {
  const now = Date.now();
  const cutoff = now - RATE_LIMIT_WINDOW_MS;
  if (rateBuckets.size >= 5000) {
    for (const [k, v] of rateBuckets) {
      if (v.length === 0 || v[v.length - 1] <= cutoff) rateBuckets.delete(k);
    }
  }
  let hits = rateBuckets.get(ip);
  if (!hits) { hits = []; rateBuckets.set(ip, hits); }
  while (hits.length > 0 && hits[0] <= cutoff) hits.shift();
  if (hits.length >= RATE_LIMIT_MAX) return true;
  hits.push(now);
  return false;
}

// Origins allowed to call this endpoint via CORS.
const ALLOWED_ORIGINS = [
  'https://app.echo-learn.uk',
  'https://echo-learn.uk',
  'http://localhost:5173',
  'http://localhost:4173',
  'http://127.0.0.1:5173',
];

function resolveOrigin(origin: string | undefined): string | null {
  if (!origin) return null;
  if (ALLOWED_ORIGINS.includes(origin)) return origin;
  if (origin.endsWith('.vercel.app')) return origin; // Vercel preview deployments
  return null;
}

function isUsableTranscript(data: unknown): data is {
  lines: Array<Record<string, unknown>>;
  language?: string;
  isAutoGenerated?: boolean;
  source?: string;
} {
  if (!data || typeof data !== 'object') return false;
  const candidate = data as { lines?: unknown };
  return Array.isArray(candidate.lines) && candidate.lines.length > 0;
}

const TRANSCRIPT_FAILURE_CODES = {
  CAPTIONS_NOT_FOUND: 'captions_not_found',
  ACQUISITION_BLOCKED: 'youtube_acquisition_blocked',
  PROVIDER_TIMEOUT: 'provider_timeout',
  TRANSCRIPT_DISABLED: 'transcript_disabled',
  ASR_REQUIRED: 'asr_required',
  PROVIDER_FAILURE: 'provider_failure',
} as const;

type TranscriptFailureCode = (typeof TRANSCRIPT_FAILURE_CODES)[keyof typeof TRANSCRIPT_FAILURE_CODES];

interface TranscriptFailure {
  code: TranscriptFailureCode;
  status: number;
  message: string;
}

function failureForCode(code: TranscriptFailureCode): TranscriptFailure {
  switch (code) {
    case TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT:
      return { code, status: 504, message: 'Transcript provider timed out.' };
    case TRANSCRIPT_FAILURE_CODES.ACQUISITION_BLOCKED:
      return { code, status: 403, message: 'YouTube media acquisition is currently unavailable.' };
    case TRANSCRIPT_FAILURE_CODES.TRANSCRIPT_DISABLED:
      return { code, status: 404, message: 'Transcript is disabled on this video.' };
    case TRANSCRIPT_FAILURE_CODES.ASR_REQUIRED:
      return { code, status: 409, message: 'Explicit ASR opt-in is required for transcript recovery.' };
    case TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE:
      return { code, status: 500, message: 'Transcript provider failed.' };
    case TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND:
    default:
      return { code: TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND, status: 404, message: 'No caption transcript is available for this video.' };
  }
}

function structuredFailureCode(payload: unknown): TranscriptFailureCode | undefined {
  if (!payload || typeof payload !== 'object') return undefined;
  const candidate = payload as {
    code?: unknown;
    error?: unknown;
    detail?: { code?: unknown };
  };
  const values = [candidate.code, candidate.detail?.code, candidate.error];
  return values.find((value): value is TranscriptFailureCode =>
    typeof value === 'string'
    && Object.values(TRANSCRIPT_FAILURE_CODES).includes(value as TranscriptFailureCode),
  );
}

function classifyVpsFailure(status: number, payload: unknown): TranscriptFailure {
  const structuredCode = structuredFailureCode(payload);
  if (structuredCode) return failureForCode(structuredCode);
  if (status === 408 || status === 504) return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT);
  if (status === 404) return failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);
  return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
}

function classifyYoutubeFailure(message: string): TranscriptFailure {
  const normalized = message.toLowerCase();
  if (normalized.includes('timeout') || normalized.includes('timed out')) {
    return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT);
  }
  if (normalized.includes('disabled')) {
    return failureForCode(TRANSCRIPT_FAILURE_CODES.TRANSCRIPT_DISABLED);
  }
  if (normalized.includes('no transcripts') || normalized.includes('no transcript')) {
    return failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);
  }
  return failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
}

async function fetchVpsTranscript(
  videoId: string,
  lang: string,
  apiKey: string,
  traceId: string,
): Promise<{ data: Record<string, unknown> | null; failure?: TranscriptFailure }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), VPS_TIMEOUT_MS);
  try {
    const upstream = await fetch(
      `${VPS_API_URL}/api/transcript?videoId=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(lang)}`,
      {
        headers: { 'X-Api-Key': apiKey, [TRACE_HEADER]: traceId },
        signal: controller.signal,
      },
    );
    if (!upstream.ok) {
      const payload = await upstream.json().catch(() => undefined);
      const failure = classifyVpsFailure(upstream.status, payload);
      logTranscriptEvent('vps_result', { traceId, videoId, status: upstream.status, usable: false, error: failure.code });
      return { data: null, failure };
    }
    let data: unknown;
    try {
      data = await upstream.json();
    } catch {
      const failure = failureForCode(TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE);
      logTranscriptEvent('vps_result', { traceId, videoId, status: upstream.status, usable: false, reason: 'malformed_json', error: failure.code });
      return { data: null, failure };
    }
    if (!isUsableTranscript(data)) {
      const failure = failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);
      logTranscriptEvent('vps_result', { traceId, videoId, status: upstream.status, usable: false, reason: 'empty_or_malformed', error: failure.code });
      return { data: null, failure };
    }
    logTranscriptEvent('vps_result', { traceId, videoId, status: upstream.status, usable: true, lineCount: data.lines.length });
    return { data: { ...data, source: (data as { source?: string }).source || 'vps' } };
  } catch (err) {
    logTranscriptEvent('vps_error', {
      traceId,
      videoId,
      error: err instanceof Error && err.name === 'AbortError' ? 'timeout' : 'network_or_parse',
    });
    return {
      data: null,
      failure: failureForCode(
        err instanceof Error && err.name === 'AbortError'
          ? TRANSCRIPT_FAILURE_CODES.PROVIDER_TIMEOUT
          : TRANSCRIPT_FAILURE_CODES.PROVIDER_FAILURE,
      ),
    };
  } finally {
    clearTimeout(timer);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default async function handler(req: any, res: any): Promise<void> {
  const traceId = createTraceId();
  res.setHeader(TRACE_HEADER, traceId);
  logTranscriptEvent('request_start', { traceId, method: req.method });
  // CORS headers (restricted to the app's known origins)
  const allowed = resolveOrigin(req.headers?.origin as string | undefined);
  if (allowed) res.setHeader('Access-Control-Allow-Origin', allowed);
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Expose-Headers', TRACE_HEADER);

  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  // Rate limit per IP
  const ip = (req.headers?.['x-forwarded-for'] as string)?.split(',')[0]?.trim()
    || (req.headers?.['x-real-ip'] as string)
    || (req.socket?.remoteAddress as string)
    || 'unknown';
  if (isRateLimited(ip)) {
    res.status(429).json({ error: 'Rate limit exceeded. Please slow down.' });
    return;
  }

  const videoId = req.query?.videoId;
  const lang = (req.query?.lang as string) || 'en';

  if (!videoId || typeof videoId !== 'string') {
    res.status(400).json({ error: 'Missing videoId parameter' });
    return;
  }

  let vpsFailure: TranscriptFailure | undefined;
  try {
    const vpsKey = process.env.YTDLP_API_KEY;
    // This is the useful recovery path after Worker transport/generic 5xx
    // failures. It calls the VPS caption transcript route, not /api/asr;
    // frontend structured Worker outcomes stop before reaching this endpoint.
    if (vpsKey) {
      const vpsOutcome = await fetchVpsTranscript(videoId, lang, vpsKey, traceId);
      vpsFailure = vpsOutcome.failure;
      if (vpsOutcome.data) {
        logTranscriptEvent('request_finish', { traceId, videoId, provider: 'vps', status: 200 });
        res.status(200).json(vpsOutcome.data);
        return;
      }
    }

    const { YoutubeTranscript } = await import('youtube-transcript');

    // Custom fetch that adds CONSENT cookie to all YouTube requests
    const customFetch = (url: string | URL | Request, init?: RequestInit) => {
      const headers = new Headers(init?.headers);
      headers.set('Cookie', CONSENT_COOKIE);
      // Also set a realistic browser UA as fallback
      if (!headers.has('User-Agent')) {
        headers.set(
          'User-Agent',
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
        );
      }
      return fetch(url, { ...init, headers });
    };

    const result = await YoutubeTranscript.fetchTranscript(videoId, {
      lang,
      fetch: customFetch,
    });

    if (!result || result.length === 0) {
      const failure = vpsFailure || failureForCode(TRANSCRIPT_FAILURE_CODES.CAPTIONS_NOT_FOUND);
      res.status(failure.status).json({ error: failure.code, code: failure.code, message: failure.message });
      return;
    }

    // Transform to our TranscriptLine format
    const lines = result.map(
      (item: { text: string; offset: number; duration: number }, i: number) => ({
        id: `yt_${i + 1}`,
        start: item.offset > 1000 ? item.offset / 1000 : item.offset,
        end:
          (item.offset > 1000 ? item.offset / 1000 : item.offset) +
          (item.duration > 1000 ? item.duration / 1000 : item.duration),
        text: item.text,
      }),
    );

    logTranscriptEvent('request_finish', { traceId, videoId, provider: 'youtube-transcript', status: 200, lineCount: lines.length });
    res.status(200).json({
      lines,
      language: result[0]?.lang ?? lang,
      isAutoGenerated: true,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    const failure = vpsFailure || classifyYoutubeFailure(message);
    logTranscriptEvent('request_error', { traceId, videoId, status: failure.status, error: failure.code });
    res.status(failure.status).json({ error: failure.code, code: failure.code, message: failure.message });
  }
}
